// Code generated by SQLBoiler 4.19.5 (https://github.com/aarondl/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dto

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/aarondl/sqlboiler/v4/boil"
	"github.com/aarondl/sqlboiler/v4/queries"
	"github.com/aarondl/sqlboiler/v4/queries/qm"
	"github.com/aarondl/sqlboiler/v4/queries/qmhelper"
	"github.com/aarondl/strmangle"
	"github.com/friendsofgo/errors"
)

// DataLesson is an object representing the database table.
type DataLesson struct {
	ID        int       `boil:"id" json:"id" toml:"id" yaml:"id"`
	Campus    string    `boil:"campus" json:"campus" toml:"campus" yaml:"campus"`
	Name      string    `boil:"name" json:"name" toml:"name" yaml:"name"`
	Duration  int       `boil:"duration" json:"duration" toml:"duration" yaml:"duration"`
	CreatedAt time.Time `boil:"created_at" json:"created_at" toml:"created_at" yaml:"created_at"`
	UpdatedAt time.Time `boil:"updated_at" json:"updated_at" toml:"updated_at" yaml:"updated_at"`

	R *dataLessonR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L dataLessonL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var DataLessonColumns = struct {
	ID        string
	Campus    string
	Name      string
	Duration  string
	CreatedAt string
	UpdatedAt string
}{
	ID:        "id",
	Campus:    "campus",
	Name:      "name",
	Duration:  "duration",
	CreatedAt: "created_at",
	UpdatedAt: "updated_at",
}

var DataLessonTableColumns = struct {
	ID        string
	Campus    string
	Name      string
	Duration  string
	CreatedAt string
	UpdatedAt string
}{
	ID:        "data_lessons.id",
	Campus:    "data_lessons.campus",
	Name:      "data_lessons.name",
	Duration:  "data_lessons.duration",
	CreatedAt: "data_lessons.created_at",
	UpdatedAt: "data_lessons.updated_at",
}

// Generated where

var DataLessonWhere = struct {
	ID        whereHelperint
	Campus    whereHelperstring
	Name      whereHelperstring
	Duration  whereHelperint
	CreatedAt whereHelpertime_Time
	UpdatedAt whereHelpertime_Time
}{
	ID:        whereHelperint{field: "`data_lessons`.`id`"},
	Campus:    whereHelperstring{field: "`data_lessons`.`campus`"},
	Name:      whereHelperstring{field: "`data_lessons`.`name`"},
	Duration:  whereHelperint{field: "`data_lessons`.`duration`"},
	CreatedAt: whereHelpertime_Time{field: "`data_lessons`.`created_at`"},
	UpdatedAt: whereHelpertime_Time{field: "`data_lessons`.`updated_at`"},
}

// DataLessonRels is where relationship names are stored.
var DataLessonRels = struct {
	CampusDataCampuse      string
	LessonTBLScheduleItems string
}{
	CampusDataCampuse:      "CampusDataCampuse",
	LessonTBLScheduleItems: "LessonTBLScheduleItems",
}

// dataLessonR is where relationships are stored.
type dataLessonR struct {
	CampusDataCampuse      *DataCampuse         `boil:"CampusDataCampuse" json:"CampusDataCampuse" toml:"CampusDataCampuse" yaml:"CampusDataCampuse"`
	LessonTBLScheduleItems TBLScheduleItemSlice `boil:"LessonTBLScheduleItems" json:"LessonTBLScheduleItems" toml:"LessonTBLScheduleItems" yaml:"LessonTBLScheduleItems"`
}

// NewStruct creates a new relationship struct
func (*dataLessonR) NewStruct() *dataLessonR {
	return &dataLessonR{}
}

func (o *DataLesson) GetCampusDataCampuse() *DataCampuse {
	if o == nil {
		return nil
	}

	return o.R.GetCampusDataCampuse()
}

func (r *dataLessonR) GetCampusDataCampuse() *DataCampuse {
	if r == nil {
		return nil
	}

	return r.CampusDataCampuse
}

func (o *DataLesson) GetLessonTBLScheduleItems() TBLScheduleItemSlice {
	if o == nil {
		return nil
	}

	return o.R.GetLessonTBLScheduleItems()
}

func (r *dataLessonR) GetLessonTBLScheduleItems() TBLScheduleItemSlice {
	if r == nil {
		return nil
	}

	return r.LessonTBLScheduleItems
}

// dataLessonL is where Load methods for each relationship are stored.
type dataLessonL struct{}

var (
	dataLessonAllColumns            = []string{"id", "campus", "name", "duration", "created_at", "updated_at"}
	dataLessonColumnsWithoutDefault = []string{"campus", "name", "duration"}
	dataLessonColumnsWithDefault    = []string{"id", "created_at", "updated_at"}
	dataLessonPrimaryKeyColumns     = []string{"id"}
	dataLessonGeneratedColumns      = []string{}
)

type (
	// DataLessonSlice is an alias for a slice of pointers to DataLesson.
	// This should almost always be used instead of []DataLesson.
	DataLessonSlice []*DataLesson
	// DataLessonHook is the signature for custom DataLesson hook methods
	DataLessonHook func(context.Context, boil.ContextExecutor, *DataLesson) error

	dataLessonQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	dataLessonType                 = reflect.TypeOf(&DataLesson{})
	dataLessonMapping              = queries.MakeStructMapping(dataLessonType)
	dataLessonPrimaryKeyMapping, _ = queries.BindMapping(dataLessonType, dataLessonMapping, dataLessonPrimaryKeyColumns)
	dataLessonInsertCacheMut       sync.RWMutex
	dataLessonInsertCache          = make(map[string]insertCache)
	dataLessonUpdateCacheMut       sync.RWMutex
	dataLessonUpdateCache          = make(map[string]updateCache)
	dataLessonUpsertCacheMut       sync.RWMutex
	dataLessonUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

var dataLessonAfterSelectMu sync.Mutex
var dataLessonAfterSelectHooks []DataLessonHook

var dataLessonBeforeInsertMu sync.Mutex
var dataLessonBeforeInsertHooks []DataLessonHook
var dataLessonAfterInsertMu sync.Mutex
var dataLessonAfterInsertHooks []DataLessonHook

var dataLessonBeforeUpdateMu sync.Mutex
var dataLessonBeforeUpdateHooks []DataLessonHook
var dataLessonAfterUpdateMu sync.Mutex
var dataLessonAfterUpdateHooks []DataLessonHook

var dataLessonBeforeDeleteMu sync.Mutex
var dataLessonBeforeDeleteHooks []DataLessonHook
var dataLessonAfterDeleteMu sync.Mutex
var dataLessonAfterDeleteHooks []DataLessonHook

var dataLessonBeforeUpsertMu sync.Mutex
var dataLessonBeforeUpsertHooks []DataLessonHook
var dataLessonAfterUpsertMu sync.Mutex
var dataLessonAfterUpsertHooks []DataLessonHook

// doAfterSelectHooks executes all "after Select" hooks.
func (o *DataLesson) doAfterSelectHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range dataLessonAfterSelectHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *DataLesson) doBeforeInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range dataLessonBeforeInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *DataLesson) doAfterInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range dataLessonAfterInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpdateHooks executes all "before Update" hooks.
func (o *DataLesson) doBeforeUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range dataLessonBeforeUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpdateHooks executes all "after Update" hooks.
func (o *DataLesson) doAfterUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range dataLessonAfterUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeDeleteHooks executes all "before Delete" hooks.
func (o *DataLesson) doBeforeDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range dataLessonBeforeDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterDeleteHooks executes all "after Delete" hooks.
func (o *DataLesson) doAfterDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range dataLessonAfterDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *DataLesson) doBeforeUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range dataLessonBeforeUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *DataLesson) doAfterUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range dataLessonAfterUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddDataLessonHook registers your hook function for all future operations.
func AddDataLessonHook(hookPoint boil.HookPoint, dataLessonHook DataLessonHook) {
	switch hookPoint {
	case boil.AfterSelectHook:
		dataLessonAfterSelectMu.Lock()
		dataLessonAfterSelectHooks = append(dataLessonAfterSelectHooks, dataLessonHook)
		dataLessonAfterSelectMu.Unlock()
	case boil.BeforeInsertHook:
		dataLessonBeforeInsertMu.Lock()
		dataLessonBeforeInsertHooks = append(dataLessonBeforeInsertHooks, dataLessonHook)
		dataLessonBeforeInsertMu.Unlock()
	case boil.AfterInsertHook:
		dataLessonAfterInsertMu.Lock()
		dataLessonAfterInsertHooks = append(dataLessonAfterInsertHooks, dataLessonHook)
		dataLessonAfterInsertMu.Unlock()
	case boil.BeforeUpdateHook:
		dataLessonBeforeUpdateMu.Lock()
		dataLessonBeforeUpdateHooks = append(dataLessonBeforeUpdateHooks, dataLessonHook)
		dataLessonBeforeUpdateMu.Unlock()
	case boil.AfterUpdateHook:
		dataLessonAfterUpdateMu.Lock()
		dataLessonAfterUpdateHooks = append(dataLessonAfterUpdateHooks, dataLessonHook)
		dataLessonAfterUpdateMu.Unlock()
	case boil.BeforeDeleteHook:
		dataLessonBeforeDeleteMu.Lock()
		dataLessonBeforeDeleteHooks = append(dataLessonBeforeDeleteHooks, dataLessonHook)
		dataLessonBeforeDeleteMu.Unlock()
	case boil.AfterDeleteHook:
		dataLessonAfterDeleteMu.Lock()
		dataLessonAfterDeleteHooks = append(dataLessonAfterDeleteHooks, dataLessonHook)
		dataLessonAfterDeleteMu.Unlock()
	case boil.BeforeUpsertHook:
		dataLessonBeforeUpsertMu.Lock()
		dataLessonBeforeUpsertHooks = append(dataLessonBeforeUpsertHooks, dataLessonHook)
		dataLessonBeforeUpsertMu.Unlock()
	case boil.AfterUpsertHook:
		dataLessonAfterUpsertMu.Lock()
		dataLessonAfterUpsertHooks = append(dataLessonAfterUpsertHooks, dataLessonHook)
		dataLessonAfterUpsertMu.Unlock()
	}
}

// One returns a single dataLesson record from the query.
func (q dataLessonQuery) One(ctx context.Context, exec boil.ContextExecutor) (*DataLesson, error) {
	o := &DataLesson{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "dto: failed to execute a one query for data_lessons")
	}

	if err := o.doAfterSelectHooks(ctx, exec); err != nil {
		return o, err
	}

	return o, nil
}

// All returns all DataLesson records from the query.
func (q dataLessonQuery) All(ctx context.Context, exec boil.ContextExecutor) (DataLessonSlice, error) {
	var o []*DataLesson

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "dto: failed to assign all query results to DataLesson slice")
	}

	if len(dataLessonAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(ctx, exec); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// Count returns the count of all DataLesson records in the query.
func (q dataLessonQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "dto: failed to count data_lessons rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q dataLessonQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "dto: failed to check if data_lessons exists")
	}

	return count > 0, nil
}

// CampusDataCampuse pointed to by the foreign key.
func (o *DataLesson) CampusDataCampuse(mods ...qm.QueryMod) dataCampuseQuery {
	queryMods := []qm.QueryMod{
		qm.Where("`campus` = ?", o.Campus),
	}

	queryMods = append(queryMods, mods...)

	return DataCampuses(queryMods...)
}

// LessonTBLScheduleItems retrieves all the tbl_schedule_item's TBLScheduleItems with an executor via lesson_id column.
func (o *DataLesson) LessonTBLScheduleItems(mods ...qm.QueryMod) tblScheduleItemQuery {
	var queryMods []qm.QueryMod
	if len(mods) != 0 {
		queryMods = append(queryMods, mods...)
	}

	queryMods = append(queryMods,
		qm.Where("`tbl_schedule_items`.`lesson_id`=?", o.ID),
	)

	return TBLScheduleItems(queryMods...)
}

// LoadCampusDataCampuse allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (dataLessonL) LoadCampusDataCampuse(ctx context.Context, e boil.ContextExecutor, singular bool, maybeDataLesson interface{}, mods queries.Applicator) error {
	var slice []*DataLesson
	var object *DataLesson

	if singular {
		var ok bool
		object, ok = maybeDataLesson.(*DataLesson)
		if !ok {
			object = new(DataLesson)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeDataLesson)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeDataLesson))
			}
		}
	} else {
		s, ok := maybeDataLesson.(*[]*DataLesson)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeDataLesson)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeDataLesson))
			}
		}
	}

	args := make(map[interface{}]struct{})
	if singular {
		if object.R == nil {
			object.R = &dataLessonR{}
		}
		args[object.Campus] = struct{}{}

	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &dataLessonR{}
			}

			args[obj.Campus] = struct{}{}

		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]interface{}, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`data_campuses`),
		qm.WhereIn(`data_campuses.campus in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load DataCampuse")
	}

	var resultSlice []*DataCampuse
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice DataCampuse")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for data_campuses")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for data_campuses")
	}

	if len(dataCampuseAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.CampusDataCampuse = foreign
		if foreign.R == nil {
			foreign.R = &dataCampuseR{}
		}
		foreign.R.CampusDataLessons = append(foreign.R.CampusDataLessons, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if local.Campus == foreign.Campus {
				local.R.CampusDataCampuse = foreign
				if foreign.R == nil {
					foreign.R = &dataCampuseR{}
				}
				foreign.R.CampusDataLessons = append(foreign.R.CampusDataLessons, local)
				break
			}
		}
	}

	return nil
}

// LoadLessonTBLScheduleItems allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for a 1-M or N-M relationship.
func (dataLessonL) LoadLessonTBLScheduleItems(ctx context.Context, e boil.ContextExecutor, singular bool, maybeDataLesson interface{}, mods queries.Applicator) error {
	var slice []*DataLesson
	var object *DataLesson

	if singular {
		var ok bool
		object, ok = maybeDataLesson.(*DataLesson)
		if !ok {
			object = new(DataLesson)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeDataLesson)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeDataLesson))
			}
		}
	} else {
		s, ok := maybeDataLesson.(*[]*DataLesson)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeDataLesson)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeDataLesson))
			}
		}
	}

	args := make(map[interface{}]struct{})
	if singular {
		if object.R == nil {
			object.R = &dataLessonR{}
		}
		args[object.ID] = struct{}{}
	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &dataLessonR{}
			}
			args[obj.ID] = struct{}{}
		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]interface{}, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`tbl_schedule_items`),
		qm.WhereIn(`tbl_schedule_items.lesson_id in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load tbl_schedule_items")
	}

	var resultSlice []*TBLScheduleItem
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice tbl_schedule_items")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results in eager load on tbl_schedule_items")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for tbl_schedule_items")
	}

	if len(tblScheduleItemAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}
	if singular {
		object.R.LessonTBLScheduleItems = resultSlice
		for _, foreign := range resultSlice {
			if foreign.R == nil {
				foreign.R = &tblScheduleItemR{}
			}
			foreign.R.Lesson = object
		}
		return nil
	}

	for _, foreign := range resultSlice {
		for _, local := range slice {
			if local.ID == foreign.LessonID {
				local.R.LessonTBLScheduleItems = append(local.R.LessonTBLScheduleItems, foreign)
				if foreign.R == nil {
					foreign.R = &tblScheduleItemR{}
				}
				foreign.R.Lesson = local
				break
			}
		}
	}

	return nil
}

// SetCampusDataCampuse of the dataLesson to the related item.
// Sets o.R.CampusDataCampuse to related.
// Adds o to related.R.CampusDataLessons.
func (o *DataLesson) SetCampusDataCampuse(ctx context.Context, exec boil.ContextExecutor, insert bool, related *DataCampuse) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE `data_lessons` SET %s WHERE %s",
		strmangle.SetParamNames("`", "`", 0, []string{"campus"}),
		strmangle.WhereClause("`", "`", 0, dataLessonPrimaryKeyColumns),
	)
	values := []interface{}{related.Campus, o.ID}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, updateQuery)
		fmt.Fprintln(writer, values)
	}
	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	o.Campus = related.Campus
	if o.R == nil {
		o.R = &dataLessonR{
			CampusDataCampuse: related,
		}
	} else {
		o.R.CampusDataCampuse = related
	}

	if related.R == nil {
		related.R = &dataCampuseR{
			CampusDataLessons: DataLessonSlice{o},
		}
	} else {
		related.R.CampusDataLessons = append(related.R.CampusDataLessons, o)
	}

	return nil
}

// AddLessonTBLScheduleItems adds the given related objects to the existing relationships
// of the data_lesson, optionally inserting them as new records.
// Appends related to o.R.LessonTBLScheduleItems.
// Sets related.R.Lesson appropriately.
func (o *DataLesson) AddLessonTBLScheduleItems(ctx context.Context, exec boil.ContextExecutor, insert bool, related ...*TBLScheduleItem) error {
	var err error
	for _, rel := range related {
		if insert {
			rel.LessonID = o.ID
			if err = rel.Insert(ctx, exec, boil.Infer()); err != nil {
				return errors.Wrap(err, "failed to insert into foreign table")
			}
		} else {
			updateQuery := fmt.Sprintf(
				"UPDATE `tbl_schedule_items` SET %s WHERE %s",
				strmangle.SetParamNames("`", "`", 0, []string{"lesson_id"}),
				strmangle.WhereClause("`", "`", 0, tblScheduleItemPrimaryKeyColumns),
			)
			values := []interface{}{o.ID, rel.ID}

			if boil.IsDebug(ctx) {
				writer := boil.DebugWriterFrom(ctx)
				fmt.Fprintln(writer, updateQuery)
				fmt.Fprintln(writer, values)
			}
			if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
				return errors.Wrap(err, "failed to update foreign table")
			}

			rel.LessonID = o.ID
		}
	}

	if o.R == nil {
		o.R = &dataLessonR{
			LessonTBLScheduleItems: related,
		}
	} else {
		o.R.LessonTBLScheduleItems = append(o.R.LessonTBLScheduleItems, related...)
	}

	for _, rel := range related {
		if rel.R == nil {
			rel.R = &tblScheduleItemR{
				Lesson: o,
			}
		} else {
			rel.R.Lesson = o
		}
	}
	return nil
}

// DataLessons retrieves all the records using an executor.
func DataLessons(mods ...qm.QueryMod) dataLessonQuery {
	mods = append(mods, qm.From("`data_lessons`"))
	q := NewQuery(mods...)
	if len(queries.GetSelect(q)) == 0 {
		queries.SetSelect(q, []string{"`data_lessons`.*"})
	}

	return dataLessonQuery{q}
}

// FindDataLesson retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindDataLesson(ctx context.Context, exec boil.ContextExecutor, iD int, selectCols ...string) (*DataLesson, error) {
	dataLessonObj := &DataLesson{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from `data_lessons` where `id`=?", sel,
	)

	q := queries.Raw(query, iD)

	err := q.Bind(ctx, exec, dataLessonObj)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "dto: unable to select from data_lessons")
	}

	if err = dataLessonObj.doAfterSelectHooks(ctx, exec); err != nil {
		return dataLessonObj, err
	}

	return dataLessonObj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *DataLesson) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("dto: no data_lessons provided for insertion")
	}

	var err error

	if err := o.doBeforeInsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(dataLessonColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	dataLessonInsertCacheMut.RLock()
	cache, cached := dataLessonInsertCache[key]
	dataLessonInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			dataLessonAllColumns,
			dataLessonColumnsWithDefault,
			dataLessonColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(dataLessonType, dataLessonMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(dataLessonType, dataLessonMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO `data_lessons` (`%s`) %%sVALUES (%s)%%s", strings.Join(wl, "`,`"), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO `data_lessons` () VALUES ()%s%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			cache.retQuery = fmt.Sprintf("SELECT `%s` FROM `data_lessons` WHERE %s", strings.Join(returnColumns, "`,`"), strmangle.WhereClause("`", "`", 0, dataLessonPrimaryKeyColumns))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	result, err := exec.ExecContext(ctx, cache.query, vals...)

	if err != nil {
		return errors.Wrap(err, "dto: unable to insert into data_lessons")
	}

	var lastID int64
	var identifierCols []interface{}

	if len(cache.retMapping) == 0 {
		goto CacheNoHooks
	}

	lastID, err = result.LastInsertId()
	if err != nil {
		return ErrSyncFail
	}

	o.ID = int(lastID)
	if lastID != 0 && len(cache.retMapping) == 1 && cache.retMapping[0] == dataLessonMapping["id"] {
		goto CacheNoHooks
	}

	identifierCols = []interface{}{
		o.ID,
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.retQuery)
		fmt.Fprintln(writer, identifierCols...)
	}
	err = exec.QueryRowContext(ctx, cache.retQuery, identifierCols...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	if err != nil {
		return errors.Wrap(err, "dto: unable to populate default values for data_lessons")
	}

CacheNoHooks:
	if !cached {
		dataLessonInsertCacheMut.Lock()
		dataLessonInsertCache[key] = cache
		dataLessonInsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(ctx, exec)
}

// Update uses an executor to update the DataLesson.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *DataLesson) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	var err error
	if err = o.doBeforeUpdateHooks(ctx, exec); err != nil {
		return 0, err
	}
	key := makeCacheKey(columns, nil)
	dataLessonUpdateCacheMut.RLock()
	cache, cached := dataLessonUpdateCache[key]
	dataLessonUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			dataLessonAllColumns,
			dataLessonPrimaryKeyColumns,
		)
		if len(wl) == 0 {
			return 0, errors.New("dto: unable to update data_lessons, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE `data_lessons` SET %s WHERE %s",
			strmangle.SetParamNames("`", "`", 0, wl),
			strmangle.WhereClause("`", "`", 0, dataLessonPrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(dataLessonType, dataLessonMapping, append(wl, dataLessonPrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "dto: unable to update data_lessons row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "dto: failed to get rows affected by update for data_lessons")
	}

	if !cached {
		dataLessonUpdateCacheMut.Lock()
		dataLessonUpdateCache[key] = cache
		dataLessonUpdateCacheMut.Unlock()
	}

	return rowsAff, o.doAfterUpdateHooks(ctx, exec)
}

// UpdateAll updates all rows with the specified column values.
func (q dataLessonQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "dto: unable to update all for data_lessons")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "dto: unable to retrieve rows affected for data_lessons")
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o DataLessonSlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("dto: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), dataLessonPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE `data_lessons` SET %s WHERE %s",
		strmangle.SetParamNames("`", "`", 0, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, dataLessonPrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "dto: unable to update all in dataLesson slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "dto: unable to retrieve rows affected all in update all dataLesson")
	}
	return rowsAff, nil
}

var mySQLDataLessonUniqueColumns = []string{
	"id",
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *DataLesson) Upsert(ctx context.Context, exec boil.ContextExecutor, updateColumns, insertColumns boil.Columns) error {
	if o == nil {
		return errors.New("dto: no data_lessons provided for upsert")
	}

	if err := o.doBeforeUpsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(dataLessonColumnsWithDefault, o)
	nzUniques := queries.NonZeroDefaultSet(mySQLDataLessonUniqueColumns, o)

	if len(nzUniques) == 0 {
		return errors.New("cannot upsert with a table that cannot conflict on a unique column")
	}

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzUniques {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	dataLessonUpsertCacheMut.RLock()
	cache, cached := dataLessonUpsertCache[key]
	dataLessonUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, _ := insertColumns.InsertColumnSet(
			dataLessonAllColumns,
			dataLessonColumnsWithDefault,
			dataLessonColumnsWithoutDefault,
			nzDefaults,
		)

		update := updateColumns.UpdateColumnSet(
			dataLessonAllColumns,
			dataLessonPrimaryKeyColumns,
		)

		if !updateColumns.IsNone() && len(update) == 0 {
			return errors.New("dto: unable to upsert data_lessons, could not build update column list")
		}

		ret := strmangle.SetComplement(dataLessonAllColumns, strmangle.SetIntersect(insert, update))

		cache.query = buildUpsertQueryMySQL(dialect, "`data_lessons`", update, insert)
		cache.retQuery = fmt.Sprintf(
			"SELECT %s FROM `data_lessons` WHERE %s",
			strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, ret), ","),
			strmangle.WhereClause("`", "`", 0, nzUniques),
		)

		cache.valueMapping, err = queries.BindMapping(dataLessonType, dataLessonMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(dataLessonType, dataLessonMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	result, err := exec.ExecContext(ctx, cache.query, vals...)

	if err != nil {
		return errors.Wrap(err, "dto: unable to upsert for data_lessons")
	}

	var lastID int64
	var uniqueMap []uint64
	var nzUniqueCols []interface{}

	if len(cache.retMapping) == 0 {
		goto CacheNoHooks
	}

	lastID, err = result.LastInsertId()
	if err != nil {
		return ErrSyncFail
	}

	o.ID = int(lastID)
	if lastID != 0 && len(cache.retMapping) == 1 && cache.retMapping[0] == dataLessonMapping["id"] {
		goto CacheNoHooks
	}

	uniqueMap, err = queries.BindMapping(dataLessonType, dataLessonMapping, nzUniques)
	if err != nil {
		return errors.Wrap(err, "dto: unable to retrieve unique values for data_lessons")
	}
	nzUniqueCols = queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), uniqueMap)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.retQuery)
		fmt.Fprintln(writer, nzUniqueCols...)
	}
	err = exec.QueryRowContext(ctx, cache.retQuery, nzUniqueCols...).Scan(returns...)
	if err != nil {
		return errors.Wrap(err, "dto: unable to populate default values for data_lessons")
	}

CacheNoHooks:
	if !cached {
		dataLessonUpsertCacheMut.Lock()
		dataLessonUpsertCache[key] = cache
		dataLessonUpsertCacheMut.Unlock()
	}

	return o.doAfterUpsertHooks(ctx, exec)
}

// Delete deletes a single DataLesson record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *DataLesson) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("dto: no DataLesson provided for delete")
	}

	if err := o.doBeforeDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), dataLessonPrimaryKeyMapping)
	sql := "DELETE FROM `data_lessons` WHERE `id`=?"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "dto: unable to delete from data_lessons")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "dto: failed to get rows affected by delete for data_lessons")
	}

	if err := o.doAfterDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	return rowsAff, nil
}

// DeleteAll deletes all matching rows.
func (q dataLessonQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("dto: no dataLessonQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "dto: unable to delete all from data_lessons")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "dto: failed to get rows affected by deleteall for data_lessons")
	}

	return rowsAff, nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o DataLessonSlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	if len(dataLessonBeforeDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doBeforeDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), dataLessonPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM `data_lessons` WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, dataLessonPrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "dto: unable to delete all from dataLesson slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "dto: failed to get rows affected by deleteall for data_lessons")
	}

	if len(dataLessonAfterDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	return rowsAff, nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *DataLesson) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindDataLesson(ctx, exec, o.ID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *DataLessonSlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := DataLessonSlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), dataLessonPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT `data_lessons`.* FROM `data_lessons` WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, dataLessonPrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "dto: unable to reload all in DataLessonSlice")
	}

	*o = slice

	return nil
}

// DataLessonExists checks if the DataLesson row exists.
func DataLessonExists(ctx context.Context, exec boil.ContextExecutor, iD int) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from `data_lessons` where `id`=? limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, iD)
	}
	row := exec.QueryRowContext(ctx, sql, iD)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "dto: unable to check if data_lessons exists")
	}

	return exists, nil
}

// Exists checks if the DataLesson row exists.
func (o *DataLesson) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	return DataLessonExists(ctx, exec, o.ID)
}
