// Code generated by SQLBoiler 4.19.5 (https://github.com/aarondl/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dto

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/aarondl/sqlboiler/v4/boil"
	"github.com/aarondl/sqlboiler/v4/queries"
	"github.com/aarondl/sqlboiler/v4/queries/qm"
	"github.com/aarondl/sqlboiler/v4/queries/qmhelper"
	"github.com/aarondl/strmangle"
	"github.com/friendsofgo/errors"
)

// SysSession is an object representing the database table.
type SysSession struct {
	SessionID string    `boil:"session_id" json:"session_id" toml:"session_id" yaml:"session_id"`
	UserID    int       `boil:"user_id" json:"user_id" toml:"user_id" yaml:"user_id"`
	Value     string    `boil:"value" json:"value" toml:"value" yaml:"value"`
	UpdatedAt time.Time `boil:"updated_at" json:"updated_at" toml:"updated_at" yaml:"updated_at"`
	CreatedAt time.Time `boil:"created_at" json:"created_at" toml:"created_at" yaml:"created_at"`

	R *sysSessionR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L sysSessionL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var SysSessionColumns = struct {
	SessionID string
	UserID    string
	Value     string
	UpdatedAt string
	CreatedAt string
}{
	SessionID: "session_id",
	UserID:    "user_id",
	Value:     "value",
	UpdatedAt: "updated_at",
	CreatedAt: "created_at",
}

var SysSessionTableColumns = struct {
	SessionID string
	UserID    string
	Value     string
	UpdatedAt string
	CreatedAt string
}{
	SessionID: "sys_sessions.session_id",
	UserID:    "sys_sessions.user_id",
	Value:     "sys_sessions.value",
	UpdatedAt: "sys_sessions.updated_at",
	CreatedAt: "sys_sessions.created_at",
}

// Generated where

var SysSessionWhere = struct {
	SessionID whereHelperstring
	UserID    whereHelperint
	Value     whereHelperstring
	UpdatedAt whereHelpertime_Time
	CreatedAt whereHelpertime_Time
}{
	SessionID: whereHelperstring{field: "`sys_sessions`.`session_id`"},
	UserID:    whereHelperint{field: "`sys_sessions`.`user_id`"},
	Value:     whereHelperstring{field: "`sys_sessions`.`value`"},
	UpdatedAt: whereHelpertime_Time{field: "`sys_sessions`.`updated_at`"},
	CreatedAt: whereHelpertime_Time{field: "`sys_sessions`.`created_at`"},
}

// SysSessionRels is where relationship names are stored.
var SysSessionRels = struct {
}{}

// sysSessionR is where relationships are stored.
type sysSessionR struct {
}

// NewStruct creates a new relationship struct
func (*sysSessionR) NewStruct() *sysSessionR {
	return &sysSessionR{}
}

// sysSessionL is where Load methods for each relationship are stored.
type sysSessionL struct{}

var (
	sysSessionAllColumns            = []string{"session_id", "user_id", "value", "updated_at", "created_at"}
	sysSessionColumnsWithoutDefault = []string{"session_id", "user_id", "value"}
	sysSessionColumnsWithDefault    = []string{"updated_at", "created_at"}
	sysSessionPrimaryKeyColumns     = []string{"session_id"}
	sysSessionGeneratedColumns      = []string{}
)

type (
	// SysSessionSlice is an alias for a slice of pointers to SysSession.
	// This should almost always be used instead of []SysSession.
	SysSessionSlice []*SysSession
	// SysSessionHook is the signature for custom SysSession hook methods
	SysSessionHook func(context.Context, boil.ContextExecutor, *SysSession) error

	sysSessionQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	sysSessionType                 = reflect.TypeOf(&SysSession{})
	sysSessionMapping              = queries.MakeStructMapping(sysSessionType)
	sysSessionPrimaryKeyMapping, _ = queries.BindMapping(sysSessionType, sysSessionMapping, sysSessionPrimaryKeyColumns)
	sysSessionInsertCacheMut       sync.RWMutex
	sysSessionInsertCache          = make(map[string]insertCache)
	sysSessionUpdateCacheMut       sync.RWMutex
	sysSessionUpdateCache          = make(map[string]updateCache)
	sysSessionUpsertCacheMut       sync.RWMutex
	sysSessionUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

var sysSessionAfterSelectMu sync.Mutex
var sysSessionAfterSelectHooks []SysSessionHook

var sysSessionBeforeInsertMu sync.Mutex
var sysSessionBeforeInsertHooks []SysSessionHook
var sysSessionAfterInsertMu sync.Mutex
var sysSessionAfterInsertHooks []SysSessionHook

var sysSessionBeforeUpdateMu sync.Mutex
var sysSessionBeforeUpdateHooks []SysSessionHook
var sysSessionAfterUpdateMu sync.Mutex
var sysSessionAfterUpdateHooks []SysSessionHook

var sysSessionBeforeDeleteMu sync.Mutex
var sysSessionBeforeDeleteHooks []SysSessionHook
var sysSessionAfterDeleteMu sync.Mutex
var sysSessionAfterDeleteHooks []SysSessionHook

var sysSessionBeforeUpsertMu sync.Mutex
var sysSessionBeforeUpsertHooks []SysSessionHook
var sysSessionAfterUpsertMu sync.Mutex
var sysSessionAfterUpsertHooks []SysSessionHook

// doAfterSelectHooks executes all "after Select" hooks.
func (o *SysSession) doAfterSelectHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range sysSessionAfterSelectHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *SysSession) doBeforeInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range sysSessionBeforeInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *SysSession) doAfterInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range sysSessionAfterInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpdateHooks executes all "before Update" hooks.
func (o *SysSession) doBeforeUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range sysSessionBeforeUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpdateHooks executes all "after Update" hooks.
func (o *SysSession) doAfterUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range sysSessionAfterUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeDeleteHooks executes all "before Delete" hooks.
func (o *SysSession) doBeforeDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range sysSessionBeforeDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterDeleteHooks executes all "after Delete" hooks.
func (o *SysSession) doAfterDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range sysSessionAfterDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *SysSession) doBeforeUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range sysSessionBeforeUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *SysSession) doAfterUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range sysSessionAfterUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddSysSessionHook registers your hook function for all future operations.
func AddSysSessionHook(hookPoint boil.HookPoint, sysSessionHook SysSessionHook) {
	switch hookPoint {
	case boil.AfterSelectHook:
		sysSessionAfterSelectMu.Lock()
		sysSessionAfterSelectHooks = append(sysSessionAfterSelectHooks, sysSessionHook)
		sysSessionAfterSelectMu.Unlock()
	case boil.BeforeInsertHook:
		sysSessionBeforeInsertMu.Lock()
		sysSessionBeforeInsertHooks = append(sysSessionBeforeInsertHooks, sysSessionHook)
		sysSessionBeforeInsertMu.Unlock()
	case boil.AfterInsertHook:
		sysSessionAfterInsertMu.Lock()
		sysSessionAfterInsertHooks = append(sysSessionAfterInsertHooks, sysSessionHook)
		sysSessionAfterInsertMu.Unlock()
	case boil.BeforeUpdateHook:
		sysSessionBeforeUpdateMu.Lock()
		sysSessionBeforeUpdateHooks = append(sysSessionBeforeUpdateHooks, sysSessionHook)
		sysSessionBeforeUpdateMu.Unlock()
	case boil.AfterUpdateHook:
		sysSessionAfterUpdateMu.Lock()
		sysSessionAfterUpdateHooks = append(sysSessionAfterUpdateHooks, sysSessionHook)
		sysSessionAfterUpdateMu.Unlock()
	case boil.BeforeDeleteHook:
		sysSessionBeforeDeleteMu.Lock()
		sysSessionBeforeDeleteHooks = append(sysSessionBeforeDeleteHooks, sysSessionHook)
		sysSessionBeforeDeleteMu.Unlock()
	case boil.AfterDeleteHook:
		sysSessionAfterDeleteMu.Lock()
		sysSessionAfterDeleteHooks = append(sysSessionAfterDeleteHooks, sysSessionHook)
		sysSessionAfterDeleteMu.Unlock()
	case boil.BeforeUpsertHook:
		sysSessionBeforeUpsertMu.Lock()
		sysSessionBeforeUpsertHooks = append(sysSessionBeforeUpsertHooks, sysSessionHook)
		sysSessionBeforeUpsertMu.Unlock()
	case boil.AfterUpsertHook:
		sysSessionAfterUpsertMu.Lock()
		sysSessionAfterUpsertHooks = append(sysSessionAfterUpsertHooks, sysSessionHook)
		sysSessionAfterUpsertMu.Unlock()
	}
}

// One returns a single sysSession record from the query.
func (q sysSessionQuery) One(ctx context.Context, exec boil.ContextExecutor) (*SysSession, error) {
	o := &SysSession{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "dto: failed to execute a one query for sys_sessions")
	}

	if err := o.doAfterSelectHooks(ctx, exec); err != nil {
		return o, err
	}

	return o, nil
}

// All returns all SysSession records from the query.
func (q sysSessionQuery) All(ctx context.Context, exec boil.ContextExecutor) (SysSessionSlice, error) {
	var o []*SysSession

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "dto: failed to assign all query results to SysSession slice")
	}

	if len(sysSessionAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(ctx, exec); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// Count returns the count of all SysSession records in the query.
func (q sysSessionQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "dto: failed to count sys_sessions rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q sysSessionQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "dto: failed to check if sys_sessions exists")
	}

	return count > 0, nil
}

// SysSessions retrieves all the records using an executor.
func SysSessions(mods ...qm.QueryMod) sysSessionQuery {
	mods = append(mods, qm.From("`sys_sessions`"))
	q := NewQuery(mods...)
	if len(queries.GetSelect(q)) == 0 {
		queries.SetSelect(q, []string{"`sys_sessions`.*"})
	}

	return sysSessionQuery{q}
}

// FindSysSession retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindSysSession(ctx context.Context, exec boil.ContextExecutor, sessionID string, selectCols ...string) (*SysSession, error) {
	sysSessionObj := &SysSession{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from `sys_sessions` where `session_id`=?", sel,
	)

	q := queries.Raw(query, sessionID)

	err := q.Bind(ctx, exec, sysSessionObj)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "dto: unable to select from sys_sessions")
	}

	if err = sysSessionObj.doAfterSelectHooks(ctx, exec); err != nil {
		return sysSessionObj, err
	}

	return sysSessionObj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *SysSession) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("dto: no sys_sessions provided for insertion")
	}

	var err error

	if err := o.doBeforeInsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(sysSessionColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	sysSessionInsertCacheMut.RLock()
	cache, cached := sysSessionInsertCache[key]
	sysSessionInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			sysSessionAllColumns,
			sysSessionColumnsWithDefault,
			sysSessionColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(sysSessionType, sysSessionMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(sysSessionType, sysSessionMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO `sys_sessions` (`%s`) %%sVALUES (%s)%%s", strings.Join(wl, "`,`"), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO `sys_sessions` () VALUES ()%s%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			cache.retQuery = fmt.Sprintf("SELECT `%s` FROM `sys_sessions` WHERE %s", strings.Join(returnColumns, "`,`"), strmangle.WhereClause("`", "`", 0, sysSessionPrimaryKeyColumns))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	_, err = exec.ExecContext(ctx, cache.query, vals...)

	if err != nil {
		return errors.Wrap(err, "dto: unable to insert into sys_sessions")
	}

	var identifierCols []interface{}

	if len(cache.retMapping) == 0 {
		goto CacheNoHooks
	}

	identifierCols = []interface{}{
		o.SessionID,
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.retQuery)
		fmt.Fprintln(writer, identifierCols...)
	}
	err = exec.QueryRowContext(ctx, cache.retQuery, identifierCols...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	if err != nil {
		return errors.Wrap(err, "dto: unable to populate default values for sys_sessions")
	}

CacheNoHooks:
	if !cached {
		sysSessionInsertCacheMut.Lock()
		sysSessionInsertCache[key] = cache
		sysSessionInsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(ctx, exec)
}

// Update uses an executor to update the SysSession.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *SysSession) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	var err error
	if err = o.doBeforeUpdateHooks(ctx, exec); err != nil {
		return 0, err
	}
	key := makeCacheKey(columns, nil)
	sysSessionUpdateCacheMut.RLock()
	cache, cached := sysSessionUpdateCache[key]
	sysSessionUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			sysSessionAllColumns,
			sysSessionPrimaryKeyColumns,
		)
		if len(wl) == 0 {
			return 0, errors.New("dto: unable to update sys_sessions, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE `sys_sessions` SET %s WHERE %s",
			strmangle.SetParamNames("`", "`", 0, wl),
			strmangle.WhereClause("`", "`", 0, sysSessionPrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(sysSessionType, sysSessionMapping, append(wl, sysSessionPrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "dto: unable to update sys_sessions row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "dto: failed to get rows affected by update for sys_sessions")
	}

	if !cached {
		sysSessionUpdateCacheMut.Lock()
		sysSessionUpdateCache[key] = cache
		sysSessionUpdateCacheMut.Unlock()
	}

	return rowsAff, o.doAfterUpdateHooks(ctx, exec)
}

// UpdateAll updates all rows with the specified column values.
func (q sysSessionQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "dto: unable to update all for sys_sessions")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "dto: unable to retrieve rows affected for sys_sessions")
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o SysSessionSlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("dto: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), sysSessionPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE `sys_sessions` SET %s WHERE %s",
		strmangle.SetParamNames("`", "`", 0, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, sysSessionPrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "dto: unable to update all in sysSession slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "dto: unable to retrieve rows affected all in update all sysSession")
	}
	return rowsAff, nil
}

var mySQLSysSessionUniqueColumns = []string{
	"session_id",
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *SysSession) Upsert(ctx context.Context, exec boil.ContextExecutor, updateColumns, insertColumns boil.Columns) error {
	if o == nil {
		return errors.New("dto: no sys_sessions provided for upsert")
	}

	if err := o.doBeforeUpsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(sysSessionColumnsWithDefault, o)
	nzUniques := queries.NonZeroDefaultSet(mySQLSysSessionUniqueColumns, o)

	if len(nzUniques) == 0 {
		return errors.New("cannot upsert with a table that cannot conflict on a unique column")
	}

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzUniques {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	sysSessionUpsertCacheMut.RLock()
	cache, cached := sysSessionUpsertCache[key]
	sysSessionUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, _ := insertColumns.InsertColumnSet(
			sysSessionAllColumns,
			sysSessionColumnsWithDefault,
			sysSessionColumnsWithoutDefault,
			nzDefaults,
		)

		update := updateColumns.UpdateColumnSet(
			sysSessionAllColumns,
			sysSessionPrimaryKeyColumns,
		)

		if !updateColumns.IsNone() && len(update) == 0 {
			return errors.New("dto: unable to upsert sys_sessions, could not build update column list")
		}

		ret := strmangle.SetComplement(sysSessionAllColumns, strmangle.SetIntersect(insert, update))

		cache.query = buildUpsertQueryMySQL(dialect, "`sys_sessions`", update, insert)
		cache.retQuery = fmt.Sprintf(
			"SELECT %s FROM `sys_sessions` WHERE %s",
			strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, ret), ","),
			strmangle.WhereClause("`", "`", 0, nzUniques),
		)

		cache.valueMapping, err = queries.BindMapping(sysSessionType, sysSessionMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(sysSessionType, sysSessionMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	_, err = exec.ExecContext(ctx, cache.query, vals...)

	if err != nil {
		return errors.Wrap(err, "dto: unable to upsert for sys_sessions")
	}

	var uniqueMap []uint64
	var nzUniqueCols []interface{}

	if len(cache.retMapping) == 0 {
		goto CacheNoHooks
	}

	uniqueMap, err = queries.BindMapping(sysSessionType, sysSessionMapping, nzUniques)
	if err != nil {
		return errors.Wrap(err, "dto: unable to retrieve unique values for sys_sessions")
	}
	nzUniqueCols = queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), uniqueMap)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.retQuery)
		fmt.Fprintln(writer, nzUniqueCols...)
	}
	err = exec.QueryRowContext(ctx, cache.retQuery, nzUniqueCols...).Scan(returns...)
	if err != nil {
		return errors.Wrap(err, "dto: unable to populate default values for sys_sessions")
	}

CacheNoHooks:
	if !cached {
		sysSessionUpsertCacheMut.Lock()
		sysSessionUpsertCache[key] = cache
		sysSessionUpsertCacheMut.Unlock()
	}

	return o.doAfterUpsertHooks(ctx, exec)
}

// Delete deletes a single SysSession record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *SysSession) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("dto: no SysSession provided for delete")
	}

	if err := o.doBeforeDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), sysSessionPrimaryKeyMapping)
	sql := "DELETE FROM `sys_sessions` WHERE `session_id`=?"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "dto: unable to delete from sys_sessions")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "dto: failed to get rows affected by delete for sys_sessions")
	}

	if err := o.doAfterDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	return rowsAff, nil
}

// DeleteAll deletes all matching rows.
func (q sysSessionQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("dto: no sysSessionQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "dto: unable to delete all from sys_sessions")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "dto: failed to get rows affected by deleteall for sys_sessions")
	}

	return rowsAff, nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o SysSessionSlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	if len(sysSessionBeforeDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doBeforeDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), sysSessionPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM `sys_sessions` WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, sysSessionPrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "dto: unable to delete all from sysSession slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "dto: failed to get rows affected by deleteall for sys_sessions")
	}

	if len(sysSessionAfterDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	return rowsAff, nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *SysSession) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindSysSession(ctx, exec, o.SessionID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *SysSessionSlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := SysSessionSlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), sysSessionPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT `sys_sessions`.* FROM `sys_sessions` WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, sysSessionPrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "dto: unable to reload all in SysSessionSlice")
	}

	*o = slice

	return nil
}

// SysSessionExists checks if the SysSession row exists.
func SysSessionExists(ctx context.Context, exec boil.ContextExecutor, sessionID string) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from `sys_sessions` where `session_id`=? limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, sessionID)
	}
	row := exec.QueryRowContext(ctx, sql, sessionID)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "dto: unable to check if sys_sessions exists")
	}

	return exists, nil
}

// Exists checks if the SysSession row exists.
func (o *SysSession) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	return SysSessionExists(ctx, exec, o.SessionID)
}
