// Code generated by SQLBoiler 4.19.5 (https://github.com/aarondl/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dto

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/aarondl/sqlboiler/v4/boil"
	"github.com/aarondl/sqlboiler/v4/queries"
	"github.com/aarondl/sqlboiler/v4/queries/qm"
	"github.com/aarondl/sqlboiler/v4/queries/qmhelper"
	"github.com/aarondl/strmangle"
	"github.com/friendsofgo/errors"
)

// TBLScheduleItem is an object representing the database table.
type TBLScheduleItem struct {
	ID           int    `boil:"id" json:"id" toml:"id" yaml:"id"`
	ScheduleID   int    `boil:"schedule_id" json:"schedule_id" toml:"schedule_id" yaml:"schedule_id"`
	HistoryIndex int    `boil:"history_index" json:"history_index" toml:"history_index" yaml:"history_index"`
	LessonID     int    `boil:"lesson_id" json:"lesson_id" toml:"lesson_id" yaml:"lesson_id"`
	Identifier   string `boil:"identifier" json:"identifier" toml:"identifier" yaml:"identifier"`
	Duration     int    `boil:"duration" json:"duration" toml:"duration" yaml:"duration"`

	R *tblScheduleItemR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L tblScheduleItemL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var TBLScheduleItemColumns = struct {
	ID           string
	ScheduleID   string
	HistoryIndex string
	LessonID     string
	Identifier   string
	Duration     string
}{
	ID:           "id",
	ScheduleID:   "schedule_id",
	HistoryIndex: "history_index",
	LessonID:     "lesson_id",
	Identifier:   "identifier",
	Duration:     "duration",
}

var TBLScheduleItemTableColumns = struct {
	ID           string
	ScheduleID   string
	HistoryIndex string
	LessonID     string
	Identifier   string
	Duration     string
}{
	ID:           "tbl_schedule_items.id",
	ScheduleID:   "tbl_schedule_items.schedule_id",
	HistoryIndex: "tbl_schedule_items.history_index",
	LessonID:     "tbl_schedule_items.lesson_id",
	Identifier:   "tbl_schedule_items.identifier",
	Duration:     "tbl_schedule_items.duration",
}

// Generated where

var TBLScheduleItemWhere = struct {
	ID           whereHelperint
	ScheduleID   whereHelperint
	HistoryIndex whereHelperint
	LessonID     whereHelperint
	Identifier   whereHelperstring
	Duration     whereHelperint
}{
	ID:           whereHelperint{field: "`tbl_schedule_items`.`id`"},
	ScheduleID:   whereHelperint{field: "`tbl_schedule_items`.`schedule_id`"},
	HistoryIndex: whereHelperint{field: "`tbl_schedule_items`.`history_index`"},
	LessonID:     whereHelperint{field: "`tbl_schedule_items`.`lesson_id`"},
	Identifier:   whereHelperstring{field: "`tbl_schedule_items`.`identifier`"},
	Duration:     whereHelperint{field: "`tbl_schedule_items`.`duration`"},
}

// TBLScheduleItemRels is where relationship names are stored.
var TBLScheduleItemRels = struct {
	Schedule string
	Lesson   string
}{
	Schedule: "Schedule",
	Lesson:   "Lesson",
}

// tblScheduleItemR is where relationships are stored.
type tblScheduleItemR struct {
	Schedule *TBLSchedule `boil:"Schedule" json:"Schedule" toml:"Schedule" yaml:"Schedule"`
	Lesson   *DataLesson  `boil:"Lesson" json:"Lesson" toml:"Lesson" yaml:"Lesson"`
}

// NewStruct creates a new relationship struct
func (*tblScheduleItemR) NewStruct() *tblScheduleItemR {
	return &tblScheduleItemR{}
}

func (o *TBLScheduleItem) GetSchedule() *TBLSchedule {
	if o == nil {
		return nil
	}

	return o.R.GetSchedule()
}

func (r *tblScheduleItemR) GetSchedule() *TBLSchedule {
	if r == nil {
		return nil
	}

	return r.Schedule
}

func (o *TBLScheduleItem) GetLesson() *DataLesson {
	if o == nil {
		return nil
	}

	return o.R.GetLesson()
}

func (r *tblScheduleItemR) GetLesson() *DataLesson {
	if r == nil {
		return nil
	}

	return r.Lesson
}

// tblScheduleItemL is where Load methods for each relationship are stored.
type tblScheduleItemL struct{}

var (
	tblScheduleItemAllColumns            = []string{"id", "schedule_id", "history_index", "lesson_id", "identifier", "duration"}
	tblScheduleItemColumnsWithoutDefault = []string{"schedule_id", "history_index", "lesson_id", "identifier", "duration"}
	tblScheduleItemColumnsWithDefault    = []string{"id"}
	tblScheduleItemPrimaryKeyColumns     = []string{"id"}
	tblScheduleItemGeneratedColumns      = []string{}
)

type (
	// TBLScheduleItemSlice is an alias for a slice of pointers to TBLScheduleItem.
	// This should almost always be used instead of []TBLScheduleItem.
	TBLScheduleItemSlice []*TBLScheduleItem
	// TBLScheduleItemHook is the signature for custom TBLScheduleItem hook methods
	TBLScheduleItemHook func(context.Context, boil.ContextExecutor, *TBLScheduleItem) error

	tblScheduleItemQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	tblScheduleItemType                 = reflect.TypeOf(&TBLScheduleItem{})
	tblScheduleItemMapping              = queries.MakeStructMapping(tblScheduleItemType)
	tblScheduleItemPrimaryKeyMapping, _ = queries.BindMapping(tblScheduleItemType, tblScheduleItemMapping, tblScheduleItemPrimaryKeyColumns)
	tblScheduleItemInsertCacheMut       sync.RWMutex
	tblScheduleItemInsertCache          = make(map[string]insertCache)
	tblScheduleItemUpdateCacheMut       sync.RWMutex
	tblScheduleItemUpdateCache          = make(map[string]updateCache)
	tblScheduleItemUpsertCacheMut       sync.RWMutex
	tblScheduleItemUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

var tblScheduleItemAfterSelectMu sync.Mutex
var tblScheduleItemAfterSelectHooks []TBLScheduleItemHook

var tblScheduleItemBeforeInsertMu sync.Mutex
var tblScheduleItemBeforeInsertHooks []TBLScheduleItemHook
var tblScheduleItemAfterInsertMu sync.Mutex
var tblScheduleItemAfterInsertHooks []TBLScheduleItemHook

var tblScheduleItemBeforeUpdateMu sync.Mutex
var tblScheduleItemBeforeUpdateHooks []TBLScheduleItemHook
var tblScheduleItemAfterUpdateMu sync.Mutex
var tblScheduleItemAfterUpdateHooks []TBLScheduleItemHook

var tblScheduleItemBeforeDeleteMu sync.Mutex
var tblScheduleItemBeforeDeleteHooks []TBLScheduleItemHook
var tblScheduleItemAfterDeleteMu sync.Mutex
var tblScheduleItemAfterDeleteHooks []TBLScheduleItemHook

var tblScheduleItemBeforeUpsertMu sync.Mutex
var tblScheduleItemBeforeUpsertHooks []TBLScheduleItemHook
var tblScheduleItemAfterUpsertMu sync.Mutex
var tblScheduleItemAfterUpsertHooks []TBLScheduleItemHook

// doAfterSelectHooks executes all "after Select" hooks.
func (o *TBLScheduleItem) doAfterSelectHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range tblScheduleItemAfterSelectHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *TBLScheduleItem) doBeforeInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range tblScheduleItemBeforeInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *TBLScheduleItem) doAfterInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range tblScheduleItemAfterInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpdateHooks executes all "before Update" hooks.
func (o *TBLScheduleItem) doBeforeUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range tblScheduleItemBeforeUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpdateHooks executes all "after Update" hooks.
func (o *TBLScheduleItem) doAfterUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range tblScheduleItemAfterUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeDeleteHooks executes all "before Delete" hooks.
func (o *TBLScheduleItem) doBeforeDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range tblScheduleItemBeforeDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterDeleteHooks executes all "after Delete" hooks.
func (o *TBLScheduleItem) doAfterDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range tblScheduleItemAfterDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *TBLScheduleItem) doBeforeUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range tblScheduleItemBeforeUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *TBLScheduleItem) doAfterUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range tblScheduleItemAfterUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddTBLScheduleItemHook registers your hook function for all future operations.
func AddTBLScheduleItemHook(hookPoint boil.HookPoint, tblScheduleItemHook TBLScheduleItemHook) {
	switch hookPoint {
	case boil.AfterSelectHook:
		tblScheduleItemAfterSelectMu.Lock()
		tblScheduleItemAfterSelectHooks = append(tblScheduleItemAfterSelectHooks, tblScheduleItemHook)
		tblScheduleItemAfterSelectMu.Unlock()
	case boil.BeforeInsertHook:
		tblScheduleItemBeforeInsertMu.Lock()
		tblScheduleItemBeforeInsertHooks = append(tblScheduleItemBeforeInsertHooks, tblScheduleItemHook)
		tblScheduleItemBeforeInsertMu.Unlock()
	case boil.AfterInsertHook:
		tblScheduleItemAfterInsertMu.Lock()
		tblScheduleItemAfterInsertHooks = append(tblScheduleItemAfterInsertHooks, tblScheduleItemHook)
		tblScheduleItemAfterInsertMu.Unlock()
	case boil.BeforeUpdateHook:
		tblScheduleItemBeforeUpdateMu.Lock()
		tblScheduleItemBeforeUpdateHooks = append(tblScheduleItemBeforeUpdateHooks, tblScheduleItemHook)
		tblScheduleItemBeforeUpdateMu.Unlock()
	case boil.AfterUpdateHook:
		tblScheduleItemAfterUpdateMu.Lock()
		tblScheduleItemAfterUpdateHooks = append(tblScheduleItemAfterUpdateHooks, tblScheduleItemHook)
		tblScheduleItemAfterUpdateMu.Unlock()
	case boil.BeforeDeleteHook:
		tblScheduleItemBeforeDeleteMu.Lock()
		tblScheduleItemBeforeDeleteHooks = append(tblScheduleItemBeforeDeleteHooks, tblScheduleItemHook)
		tblScheduleItemBeforeDeleteMu.Unlock()
	case boil.AfterDeleteHook:
		tblScheduleItemAfterDeleteMu.Lock()
		tblScheduleItemAfterDeleteHooks = append(tblScheduleItemAfterDeleteHooks, tblScheduleItemHook)
		tblScheduleItemAfterDeleteMu.Unlock()
	case boil.BeforeUpsertHook:
		tblScheduleItemBeforeUpsertMu.Lock()
		tblScheduleItemBeforeUpsertHooks = append(tblScheduleItemBeforeUpsertHooks, tblScheduleItemHook)
		tblScheduleItemBeforeUpsertMu.Unlock()
	case boil.AfterUpsertHook:
		tblScheduleItemAfterUpsertMu.Lock()
		tblScheduleItemAfterUpsertHooks = append(tblScheduleItemAfterUpsertHooks, tblScheduleItemHook)
		tblScheduleItemAfterUpsertMu.Unlock()
	}
}

// One returns a single tblScheduleItem record from the query.
func (q tblScheduleItemQuery) One(ctx context.Context, exec boil.ContextExecutor) (*TBLScheduleItem, error) {
	o := &TBLScheduleItem{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "dto: failed to execute a one query for tbl_schedule_items")
	}

	if err := o.doAfterSelectHooks(ctx, exec); err != nil {
		return o, err
	}

	return o, nil
}

// All returns all TBLScheduleItem records from the query.
func (q tblScheduleItemQuery) All(ctx context.Context, exec boil.ContextExecutor) (TBLScheduleItemSlice, error) {
	var o []*TBLScheduleItem

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "dto: failed to assign all query results to TBLScheduleItem slice")
	}

	if len(tblScheduleItemAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(ctx, exec); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// Count returns the count of all TBLScheduleItem records in the query.
func (q tblScheduleItemQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "dto: failed to count tbl_schedule_items rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q tblScheduleItemQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "dto: failed to check if tbl_schedule_items exists")
	}

	return count > 0, nil
}

// Schedule pointed to by the foreign key.
func (o *TBLScheduleItem) Schedule(mods ...qm.QueryMod) tblScheduleQuery {
	queryMods := []qm.QueryMod{
		qm.Where("`id` = ?", o.ScheduleID),
	}

	queryMods = append(queryMods, mods...)

	return TBLSchedules(queryMods...)
}

// Lesson pointed to by the foreign key.
func (o *TBLScheduleItem) Lesson(mods ...qm.QueryMod) dataLessonQuery {
	queryMods := []qm.QueryMod{
		qm.Where("`id` = ?", o.LessonID),
	}

	queryMods = append(queryMods, mods...)

	return DataLessons(queryMods...)
}

// LoadSchedule allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (tblScheduleItemL) LoadSchedule(ctx context.Context, e boil.ContextExecutor, singular bool, maybeTBLScheduleItem interface{}, mods queries.Applicator) error {
	var slice []*TBLScheduleItem
	var object *TBLScheduleItem

	if singular {
		var ok bool
		object, ok = maybeTBLScheduleItem.(*TBLScheduleItem)
		if !ok {
			object = new(TBLScheduleItem)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeTBLScheduleItem)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeTBLScheduleItem))
			}
		}
	} else {
		s, ok := maybeTBLScheduleItem.(*[]*TBLScheduleItem)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeTBLScheduleItem)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeTBLScheduleItem))
			}
		}
	}

	args := make(map[interface{}]struct{})
	if singular {
		if object.R == nil {
			object.R = &tblScheduleItemR{}
		}
		args[object.ScheduleID] = struct{}{}

	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &tblScheduleItemR{}
			}

			args[obj.ScheduleID] = struct{}{}

		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]interface{}, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`tbl_schedules`),
		qm.WhereIn(`tbl_schedules.id in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load TBLSchedule")
	}

	var resultSlice []*TBLSchedule
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice TBLSchedule")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for tbl_schedules")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for tbl_schedules")
	}

	if len(tblScheduleAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.Schedule = foreign
		if foreign.R == nil {
			foreign.R = &tblScheduleR{}
		}
		foreign.R.ScheduleTBLScheduleItems = append(foreign.R.ScheduleTBLScheduleItems, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if local.ScheduleID == foreign.ID {
				local.R.Schedule = foreign
				if foreign.R == nil {
					foreign.R = &tblScheduleR{}
				}
				foreign.R.ScheduleTBLScheduleItems = append(foreign.R.ScheduleTBLScheduleItems, local)
				break
			}
		}
	}

	return nil
}

// LoadLesson allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (tblScheduleItemL) LoadLesson(ctx context.Context, e boil.ContextExecutor, singular bool, maybeTBLScheduleItem interface{}, mods queries.Applicator) error {
	var slice []*TBLScheduleItem
	var object *TBLScheduleItem

	if singular {
		var ok bool
		object, ok = maybeTBLScheduleItem.(*TBLScheduleItem)
		if !ok {
			object = new(TBLScheduleItem)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeTBLScheduleItem)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeTBLScheduleItem))
			}
		}
	} else {
		s, ok := maybeTBLScheduleItem.(*[]*TBLScheduleItem)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeTBLScheduleItem)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeTBLScheduleItem))
			}
		}
	}

	args := make(map[interface{}]struct{})
	if singular {
		if object.R == nil {
			object.R = &tblScheduleItemR{}
		}
		args[object.LessonID] = struct{}{}

	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &tblScheduleItemR{}
			}

			args[obj.LessonID] = struct{}{}

		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]interface{}, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`data_lessons`),
		qm.WhereIn(`data_lessons.id in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load DataLesson")
	}

	var resultSlice []*DataLesson
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice DataLesson")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for data_lessons")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for data_lessons")
	}

	if len(dataLessonAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.Lesson = foreign
		if foreign.R == nil {
			foreign.R = &dataLessonR{}
		}
		foreign.R.LessonTBLScheduleItems = append(foreign.R.LessonTBLScheduleItems, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if local.LessonID == foreign.ID {
				local.R.Lesson = foreign
				if foreign.R == nil {
					foreign.R = &dataLessonR{}
				}
				foreign.R.LessonTBLScheduleItems = append(foreign.R.LessonTBLScheduleItems, local)
				break
			}
		}
	}

	return nil
}

// SetSchedule of the tblScheduleItem to the related item.
// Sets o.R.Schedule to related.
// Adds o to related.R.ScheduleTBLScheduleItems.
func (o *TBLScheduleItem) SetSchedule(ctx context.Context, exec boil.ContextExecutor, insert bool, related *TBLSchedule) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE `tbl_schedule_items` SET %s WHERE %s",
		strmangle.SetParamNames("`", "`", 0, []string{"schedule_id"}),
		strmangle.WhereClause("`", "`", 0, tblScheduleItemPrimaryKeyColumns),
	)
	values := []interface{}{related.ID, o.ID}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, updateQuery)
		fmt.Fprintln(writer, values)
	}
	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	o.ScheduleID = related.ID
	if o.R == nil {
		o.R = &tblScheduleItemR{
			Schedule: related,
		}
	} else {
		o.R.Schedule = related
	}

	if related.R == nil {
		related.R = &tblScheduleR{
			ScheduleTBLScheduleItems: TBLScheduleItemSlice{o},
		}
	} else {
		related.R.ScheduleTBLScheduleItems = append(related.R.ScheduleTBLScheduleItems, o)
	}

	return nil
}

// SetLesson of the tblScheduleItem to the related item.
// Sets o.R.Lesson to related.
// Adds o to related.R.LessonTBLScheduleItems.
func (o *TBLScheduleItem) SetLesson(ctx context.Context, exec boil.ContextExecutor, insert bool, related *DataLesson) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE `tbl_schedule_items` SET %s WHERE %s",
		strmangle.SetParamNames("`", "`", 0, []string{"lesson_id"}),
		strmangle.WhereClause("`", "`", 0, tblScheduleItemPrimaryKeyColumns),
	)
	values := []interface{}{related.ID, o.ID}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, updateQuery)
		fmt.Fprintln(writer, values)
	}
	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	o.LessonID = related.ID
	if o.R == nil {
		o.R = &tblScheduleItemR{
			Lesson: related,
		}
	} else {
		o.R.Lesson = related
	}

	if related.R == nil {
		related.R = &dataLessonR{
			LessonTBLScheduleItems: TBLScheduleItemSlice{o},
		}
	} else {
		related.R.LessonTBLScheduleItems = append(related.R.LessonTBLScheduleItems, o)
	}

	return nil
}

// TBLScheduleItems retrieves all the records using an executor.
func TBLScheduleItems(mods ...qm.QueryMod) tblScheduleItemQuery {
	mods = append(mods, qm.From("`tbl_schedule_items`"))
	q := NewQuery(mods...)
	if len(queries.GetSelect(q)) == 0 {
		queries.SetSelect(q, []string{"`tbl_schedule_items`.*"})
	}

	return tblScheduleItemQuery{q}
}

// FindTBLScheduleItem retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindTBLScheduleItem(ctx context.Context, exec boil.ContextExecutor, iD int, selectCols ...string) (*TBLScheduleItem, error) {
	tblScheduleItemObj := &TBLScheduleItem{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from `tbl_schedule_items` where `id`=?", sel,
	)

	q := queries.Raw(query, iD)

	err := q.Bind(ctx, exec, tblScheduleItemObj)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "dto: unable to select from tbl_schedule_items")
	}

	if err = tblScheduleItemObj.doAfterSelectHooks(ctx, exec); err != nil {
		return tblScheduleItemObj, err
	}

	return tblScheduleItemObj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *TBLScheduleItem) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("dto: no tbl_schedule_items provided for insertion")
	}

	var err error

	if err := o.doBeforeInsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(tblScheduleItemColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	tblScheduleItemInsertCacheMut.RLock()
	cache, cached := tblScheduleItemInsertCache[key]
	tblScheduleItemInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			tblScheduleItemAllColumns,
			tblScheduleItemColumnsWithDefault,
			tblScheduleItemColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(tblScheduleItemType, tblScheduleItemMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(tblScheduleItemType, tblScheduleItemMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO `tbl_schedule_items` (`%s`) %%sVALUES (%s)%%s", strings.Join(wl, "`,`"), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO `tbl_schedule_items` () VALUES ()%s%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			cache.retQuery = fmt.Sprintf("SELECT `%s` FROM `tbl_schedule_items` WHERE %s", strings.Join(returnColumns, "`,`"), strmangle.WhereClause("`", "`", 0, tblScheduleItemPrimaryKeyColumns))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	result, err := exec.ExecContext(ctx, cache.query, vals...)

	if err != nil {
		return errors.Wrap(err, "dto: unable to insert into tbl_schedule_items")
	}

	var lastID int64
	var identifierCols []interface{}

	if len(cache.retMapping) == 0 {
		goto CacheNoHooks
	}

	lastID, err = result.LastInsertId()
	if err != nil {
		return ErrSyncFail
	}

	o.ID = int(lastID)
	if lastID != 0 && len(cache.retMapping) == 1 && cache.retMapping[0] == tblScheduleItemMapping["id"] {
		goto CacheNoHooks
	}

	identifierCols = []interface{}{
		o.ID,
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.retQuery)
		fmt.Fprintln(writer, identifierCols...)
	}
	err = exec.QueryRowContext(ctx, cache.retQuery, identifierCols...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	if err != nil {
		return errors.Wrap(err, "dto: unable to populate default values for tbl_schedule_items")
	}

CacheNoHooks:
	if !cached {
		tblScheduleItemInsertCacheMut.Lock()
		tblScheduleItemInsertCache[key] = cache
		tblScheduleItemInsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(ctx, exec)
}

// Update uses an executor to update the TBLScheduleItem.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *TBLScheduleItem) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	var err error
	if err = o.doBeforeUpdateHooks(ctx, exec); err != nil {
		return 0, err
	}
	key := makeCacheKey(columns, nil)
	tblScheduleItemUpdateCacheMut.RLock()
	cache, cached := tblScheduleItemUpdateCache[key]
	tblScheduleItemUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			tblScheduleItemAllColumns,
			tblScheduleItemPrimaryKeyColumns,
		)
		if len(wl) == 0 {
			return 0, errors.New("dto: unable to update tbl_schedule_items, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE `tbl_schedule_items` SET %s WHERE %s",
			strmangle.SetParamNames("`", "`", 0, wl),
			strmangle.WhereClause("`", "`", 0, tblScheduleItemPrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(tblScheduleItemType, tblScheduleItemMapping, append(wl, tblScheduleItemPrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "dto: unable to update tbl_schedule_items row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "dto: failed to get rows affected by update for tbl_schedule_items")
	}

	if !cached {
		tblScheduleItemUpdateCacheMut.Lock()
		tblScheduleItemUpdateCache[key] = cache
		tblScheduleItemUpdateCacheMut.Unlock()
	}

	return rowsAff, o.doAfterUpdateHooks(ctx, exec)
}

// UpdateAll updates all rows with the specified column values.
func (q tblScheduleItemQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "dto: unable to update all for tbl_schedule_items")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "dto: unable to retrieve rows affected for tbl_schedule_items")
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o TBLScheduleItemSlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("dto: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), tblScheduleItemPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE `tbl_schedule_items` SET %s WHERE %s",
		strmangle.SetParamNames("`", "`", 0, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, tblScheduleItemPrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "dto: unable to update all in tblScheduleItem slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "dto: unable to retrieve rows affected all in update all tblScheduleItem")
	}
	return rowsAff, nil
}

var mySQLTBLScheduleItemUniqueColumns = []string{
	"id",
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *TBLScheduleItem) Upsert(ctx context.Context, exec boil.ContextExecutor, updateColumns, insertColumns boil.Columns) error {
	if o == nil {
		return errors.New("dto: no tbl_schedule_items provided for upsert")
	}

	if err := o.doBeforeUpsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(tblScheduleItemColumnsWithDefault, o)
	nzUniques := queries.NonZeroDefaultSet(mySQLTBLScheduleItemUniqueColumns, o)

	if len(nzUniques) == 0 {
		return errors.New("cannot upsert with a table that cannot conflict on a unique column")
	}

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzUniques {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	tblScheduleItemUpsertCacheMut.RLock()
	cache, cached := tblScheduleItemUpsertCache[key]
	tblScheduleItemUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, _ := insertColumns.InsertColumnSet(
			tblScheduleItemAllColumns,
			tblScheduleItemColumnsWithDefault,
			tblScheduleItemColumnsWithoutDefault,
			nzDefaults,
		)

		update := updateColumns.UpdateColumnSet(
			tblScheduleItemAllColumns,
			tblScheduleItemPrimaryKeyColumns,
		)

		if !updateColumns.IsNone() && len(update) == 0 {
			return errors.New("dto: unable to upsert tbl_schedule_items, could not build update column list")
		}

		ret := strmangle.SetComplement(tblScheduleItemAllColumns, strmangle.SetIntersect(insert, update))

		cache.query = buildUpsertQueryMySQL(dialect, "`tbl_schedule_items`", update, insert)
		cache.retQuery = fmt.Sprintf(
			"SELECT %s FROM `tbl_schedule_items` WHERE %s",
			strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, ret), ","),
			strmangle.WhereClause("`", "`", 0, nzUniques),
		)

		cache.valueMapping, err = queries.BindMapping(tblScheduleItemType, tblScheduleItemMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(tblScheduleItemType, tblScheduleItemMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	result, err := exec.ExecContext(ctx, cache.query, vals...)

	if err != nil {
		return errors.Wrap(err, "dto: unable to upsert for tbl_schedule_items")
	}

	var lastID int64
	var uniqueMap []uint64
	var nzUniqueCols []interface{}

	if len(cache.retMapping) == 0 {
		goto CacheNoHooks
	}

	lastID, err = result.LastInsertId()
	if err != nil {
		return ErrSyncFail
	}

	o.ID = int(lastID)
	if lastID != 0 && len(cache.retMapping) == 1 && cache.retMapping[0] == tblScheduleItemMapping["id"] {
		goto CacheNoHooks
	}

	uniqueMap, err = queries.BindMapping(tblScheduleItemType, tblScheduleItemMapping, nzUniques)
	if err != nil {
		return errors.Wrap(err, "dto: unable to retrieve unique values for tbl_schedule_items")
	}
	nzUniqueCols = queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), uniqueMap)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.retQuery)
		fmt.Fprintln(writer, nzUniqueCols...)
	}
	err = exec.QueryRowContext(ctx, cache.retQuery, nzUniqueCols...).Scan(returns...)
	if err != nil {
		return errors.Wrap(err, "dto: unable to populate default values for tbl_schedule_items")
	}

CacheNoHooks:
	if !cached {
		tblScheduleItemUpsertCacheMut.Lock()
		tblScheduleItemUpsertCache[key] = cache
		tblScheduleItemUpsertCacheMut.Unlock()
	}

	return o.doAfterUpsertHooks(ctx, exec)
}

// Delete deletes a single TBLScheduleItem record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *TBLScheduleItem) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("dto: no TBLScheduleItem provided for delete")
	}

	if err := o.doBeforeDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), tblScheduleItemPrimaryKeyMapping)
	sql := "DELETE FROM `tbl_schedule_items` WHERE `id`=?"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "dto: unable to delete from tbl_schedule_items")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "dto: failed to get rows affected by delete for tbl_schedule_items")
	}

	if err := o.doAfterDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	return rowsAff, nil
}

// DeleteAll deletes all matching rows.
func (q tblScheduleItemQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("dto: no tblScheduleItemQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "dto: unable to delete all from tbl_schedule_items")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "dto: failed to get rows affected by deleteall for tbl_schedule_items")
	}

	return rowsAff, nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o TBLScheduleItemSlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	if len(tblScheduleItemBeforeDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doBeforeDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), tblScheduleItemPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM `tbl_schedule_items` WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, tblScheduleItemPrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "dto: unable to delete all from tblScheduleItem slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "dto: failed to get rows affected by deleteall for tbl_schedule_items")
	}

	if len(tblScheduleItemAfterDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	return rowsAff, nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *TBLScheduleItem) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindTBLScheduleItem(ctx, exec, o.ID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *TBLScheduleItemSlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := TBLScheduleItemSlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), tblScheduleItemPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT `tbl_schedule_items`.* FROM `tbl_schedule_items` WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, tblScheduleItemPrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "dto: unable to reload all in TBLScheduleItemSlice")
	}

	*o = slice

	return nil
}

// TBLScheduleItemExists checks if the TBLScheduleItem row exists.
func TBLScheduleItemExists(ctx context.Context, exec boil.ContextExecutor, iD int) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from `tbl_schedule_items` where `id`=? limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, iD)
	}
	row := exec.QueryRowContext(ctx, sql, iD)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "dto: unable to check if tbl_schedule_items exists")
	}

	return exists, nil
}

// Exists checks if the TBLScheduleItem row exists.
func (o *TBLScheduleItem) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	return TBLScheduleItemExists(ctx, exec, o.ID)
}
