// Code generated by SQLBoiler 4.19.5 (https://github.com/aarondl/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dto

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/aarondl/sqlboiler/v4/boil"
	"github.com/aarondl/sqlboiler/v4/queries"
	"github.com/aarondl/sqlboiler/v4/queries/qm"
	"github.com/aarondl/sqlboiler/v4/queries/qmhelper"
	"github.com/aarondl/strmangle"
	"github.com/friendsofgo/errors"
)

// TBLScheduleRoomItem is an object representing the database table.
type TBLScheduleRoomItem struct {
	ID               int    `boil:"id" json:"id" toml:"id" yaml:"id"`
	ScheduleID       int    `boil:"schedule_id" json:"schedule_id" toml:"schedule_id" yaml:"schedule_id"`
	HistoryIndex     int    `boil:"history_index" json:"history_index" toml:"history_index" yaml:"history_index"`
	ItemTag          string `boil:"item_tag" json:"item_tag" toml:"item_tag" yaml:"item_tag"`
	LessonID         int    `boil:"lesson_id" json:"lesson_id" toml:"lesson_id" yaml:"lesson_id"`
	Identifier       string `boil:"identifier" json:"identifier" toml:"identifier" yaml:"identifier"`
	Duration         int    `boil:"duration" json:"duration" toml:"duration" yaml:"duration"`
	StartTimeHour    int    `boil:"start_time_hour" json:"start_time_hour" toml:"start_time_hour" yaml:"start_time_hour"`
	StartTimeMinutes int    `boil:"start_time_minutes" json:"start_time_minutes" toml:"start_time_minutes" yaml:"start_time_minutes"`
	EndTimeHour      int    `boil:"end_time_hour" json:"end_time_hour" toml:"end_time_hour" yaml:"end_time_hour"`
	EndTimeMinutes   int    `boil:"end_time_minutes" json:"end_time_minutes" toml:"end_time_minutes" yaml:"end_time_minutes"`
	RoomIndex        int    `boil:"room_index" json:"room_index" toml:"room_index" yaml:"room_index"`

	R *tblScheduleRoomItemR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L tblScheduleRoomItemL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var TBLScheduleRoomItemColumns = struct {
	ID               string
	ScheduleID       string
	HistoryIndex     string
	ItemTag          string
	LessonID         string
	Identifier       string
	Duration         string
	StartTimeHour    string
	StartTimeMinutes string
	EndTimeHour      string
	EndTimeMinutes   string
	RoomIndex        string
}{
	ID:               "id",
	ScheduleID:       "schedule_id",
	HistoryIndex:     "history_index",
	ItemTag:          "item_tag",
	LessonID:         "lesson_id",
	Identifier:       "identifier",
	Duration:         "duration",
	StartTimeHour:    "start_time_hour",
	StartTimeMinutes: "start_time_minutes",
	EndTimeHour:      "end_time_hour",
	EndTimeMinutes:   "end_time_minutes",
	RoomIndex:        "room_index",
}

var TBLScheduleRoomItemTableColumns = struct {
	ID               string
	ScheduleID       string
	HistoryIndex     string
	ItemTag          string
	LessonID         string
	Identifier       string
	Duration         string
	StartTimeHour    string
	StartTimeMinutes string
	EndTimeHour      string
	EndTimeMinutes   string
	RoomIndex        string
}{
	ID:               "tbl_schedule_room_items.id",
	ScheduleID:       "tbl_schedule_room_items.schedule_id",
	HistoryIndex:     "tbl_schedule_room_items.history_index",
	ItemTag:          "tbl_schedule_room_items.item_tag",
	LessonID:         "tbl_schedule_room_items.lesson_id",
	Identifier:       "tbl_schedule_room_items.identifier",
	Duration:         "tbl_schedule_room_items.duration",
	StartTimeHour:    "tbl_schedule_room_items.start_time_hour",
	StartTimeMinutes: "tbl_schedule_room_items.start_time_minutes",
	EndTimeHour:      "tbl_schedule_room_items.end_time_hour",
	EndTimeMinutes:   "tbl_schedule_room_items.end_time_minutes",
	RoomIndex:        "tbl_schedule_room_items.room_index",
}

// Generated where

var TBLScheduleRoomItemWhere = struct {
	ID               whereHelperint
	ScheduleID       whereHelperint
	HistoryIndex     whereHelperint
	ItemTag          whereHelperstring
	LessonID         whereHelperint
	Identifier       whereHelperstring
	Duration         whereHelperint
	StartTimeHour    whereHelperint
	StartTimeMinutes whereHelperint
	EndTimeHour      whereHelperint
	EndTimeMinutes   whereHelperint
	RoomIndex        whereHelperint
}{
	ID:               whereHelperint{field: "`tbl_schedule_room_items`.`id`"},
	ScheduleID:       whereHelperint{field: "`tbl_schedule_room_items`.`schedule_id`"},
	HistoryIndex:     whereHelperint{field: "`tbl_schedule_room_items`.`history_index`"},
	ItemTag:          whereHelperstring{field: "`tbl_schedule_room_items`.`item_tag`"},
	LessonID:         whereHelperint{field: "`tbl_schedule_room_items`.`lesson_id`"},
	Identifier:       whereHelperstring{field: "`tbl_schedule_room_items`.`identifier`"},
	Duration:         whereHelperint{field: "`tbl_schedule_room_items`.`duration`"},
	StartTimeHour:    whereHelperint{field: "`tbl_schedule_room_items`.`start_time_hour`"},
	StartTimeMinutes: whereHelperint{field: "`tbl_schedule_room_items`.`start_time_minutes`"},
	EndTimeHour:      whereHelperint{field: "`tbl_schedule_room_items`.`end_time_hour`"},
	EndTimeMinutes:   whereHelperint{field: "`tbl_schedule_room_items`.`end_time_minutes`"},
	RoomIndex:        whereHelperint{field: "`tbl_schedule_room_items`.`room_index`"},
}

// TBLScheduleRoomItemRels is where relationship names are stored.
var TBLScheduleRoomItemRels = struct {
	Schedule string
}{
	Schedule: "Schedule",
}

// tblScheduleRoomItemR is where relationships are stored.
type tblScheduleRoomItemR struct {
	Schedule *TBLSchedule `boil:"Schedule" json:"Schedule" toml:"Schedule" yaml:"Schedule"`
}

// NewStruct creates a new relationship struct
func (*tblScheduleRoomItemR) NewStruct() *tblScheduleRoomItemR {
	return &tblScheduleRoomItemR{}
}

func (o *TBLScheduleRoomItem) GetSchedule() *TBLSchedule {
	if o == nil {
		return nil
	}

	return o.R.GetSchedule()
}

func (r *tblScheduleRoomItemR) GetSchedule() *TBLSchedule {
	if r == nil {
		return nil
	}

	return r.Schedule
}

// tblScheduleRoomItemL is where Load methods for each relationship are stored.
type tblScheduleRoomItemL struct{}

var (
	tblScheduleRoomItemAllColumns            = []string{"id", "schedule_id", "history_index", "item_tag", "lesson_id", "identifier", "duration", "start_time_hour", "start_time_minutes", "end_time_hour", "end_time_minutes", "room_index"}
	tblScheduleRoomItemColumnsWithoutDefault = []string{"schedule_id", "history_index", "item_tag", "lesson_id", "identifier", "duration", "start_time_hour", "start_time_minutes", "end_time_hour", "end_time_minutes", "room_index"}
	tblScheduleRoomItemColumnsWithDefault    = []string{"id"}
	tblScheduleRoomItemPrimaryKeyColumns     = []string{"id"}
	tblScheduleRoomItemGeneratedColumns      = []string{}
)

type (
	// TBLScheduleRoomItemSlice is an alias for a slice of pointers to TBLScheduleRoomItem.
	// This should almost always be used instead of []TBLScheduleRoomItem.
	TBLScheduleRoomItemSlice []*TBLScheduleRoomItem
	// TBLScheduleRoomItemHook is the signature for custom TBLScheduleRoomItem hook methods
	TBLScheduleRoomItemHook func(context.Context, boil.ContextExecutor, *TBLScheduleRoomItem) error

	tblScheduleRoomItemQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	tblScheduleRoomItemType                 = reflect.TypeOf(&TBLScheduleRoomItem{})
	tblScheduleRoomItemMapping              = queries.MakeStructMapping(tblScheduleRoomItemType)
	tblScheduleRoomItemPrimaryKeyMapping, _ = queries.BindMapping(tblScheduleRoomItemType, tblScheduleRoomItemMapping, tblScheduleRoomItemPrimaryKeyColumns)
	tblScheduleRoomItemInsertCacheMut       sync.RWMutex
	tblScheduleRoomItemInsertCache          = make(map[string]insertCache)
	tblScheduleRoomItemUpdateCacheMut       sync.RWMutex
	tblScheduleRoomItemUpdateCache          = make(map[string]updateCache)
	tblScheduleRoomItemUpsertCacheMut       sync.RWMutex
	tblScheduleRoomItemUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

var tblScheduleRoomItemAfterSelectMu sync.Mutex
var tblScheduleRoomItemAfterSelectHooks []TBLScheduleRoomItemHook

var tblScheduleRoomItemBeforeInsertMu sync.Mutex
var tblScheduleRoomItemBeforeInsertHooks []TBLScheduleRoomItemHook
var tblScheduleRoomItemAfterInsertMu sync.Mutex
var tblScheduleRoomItemAfterInsertHooks []TBLScheduleRoomItemHook

var tblScheduleRoomItemBeforeUpdateMu sync.Mutex
var tblScheduleRoomItemBeforeUpdateHooks []TBLScheduleRoomItemHook
var tblScheduleRoomItemAfterUpdateMu sync.Mutex
var tblScheduleRoomItemAfterUpdateHooks []TBLScheduleRoomItemHook

var tblScheduleRoomItemBeforeDeleteMu sync.Mutex
var tblScheduleRoomItemBeforeDeleteHooks []TBLScheduleRoomItemHook
var tblScheduleRoomItemAfterDeleteMu sync.Mutex
var tblScheduleRoomItemAfterDeleteHooks []TBLScheduleRoomItemHook

var tblScheduleRoomItemBeforeUpsertMu sync.Mutex
var tblScheduleRoomItemBeforeUpsertHooks []TBLScheduleRoomItemHook
var tblScheduleRoomItemAfterUpsertMu sync.Mutex
var tblScheduleRoomItemAfterUpsertHooks []TBLScheduleRoomItemHook

// doAfterSelectHooks executes all "after Select" hooks.
func (o *TBLScheduleRoomItem) doAfterSelectHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range tblScheduleRoomItemAfterSelectHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *TBLScheduleRoomItem) doBeforeInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range tblScheduleRoomItemBeforeInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *TBLScheduleRoomItem) doAfterInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range tblScheduleRoomItemAfterInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpdateHooks executes all "before Update" hooks.
func (o *TBLScheduleRoomItem) doBeforeUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range tblScheduleRoomItemBeforeUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpdateHooks executes all "after Update" hooks.
func (o *TBLScheduleRoomItem) doAfterUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range tblScheduleRoomItemAfterUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeDeleteHooks executes all "before Delete" hooks.
func (o *TBLScheduleRoomItem) doBeforeDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range tblScheduleRoomItemBeforeDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterDeleteHooks executes all "after Delete" hooks.
func (o *TBLScheduleRoomItem) doAfterDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range tblScheduleRoomItemAfterDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *TBLScheduleRoomItem) doBeforeUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range tblScheduleRoomItemBeforeUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *TBLScheduleRoomItem) doAfterUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range tblScheduleRoomItemAfterUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddTBLScheduleRoomItemHook registers your hook function for all future operations.
func AddTBLScheduleRoomItemHook(hookPoint boil.HookPoint, tblScheduleRoomItemHook TBLScheduleRoomItemHook) {
	switch hookPoint {
	case boil.AfterSelectHook:
		tblScheduleRoomItemAfterSelectMu.Lock()
		tblScheduleRoomItemAfterSelectHooks = append(tblScheduleRoomItemAfterSelectHooks, tblScheduleRoomItemHook)
		tblScheduleRoomItemAfterSelectMu.Unlock()
	case boil.BeforeInsertHook:
		tblScheduleRoomItemBeforeInsertMu.Lock()
		tblScheduleRoomItemBeforeInsertHooks = append(tblScheduleRoomItemBeforeInsertHooks, tblScheduleRoomItemHook)
		tblScheduleRoomItemBeforeInsertMu.Unlock()
	case boil.AfterInsertHook:
		tblScheduleRoomItemAfterInsertMu.Lock()
		tblScheduleRoomItemAfterInsertHooks = append(tblScheduleRoomItemAfterInsertHooks, tblScheduleRoomItemHook)
		tblScheduleRoomItemAfterInsertMu.Unlock()
	case boil.BeforeUpdateHook:
		tblScheduleRoomItemBeforeUpdateMu.Lock()
		tblScheduleRoomItemBeforeUpdateHooks = append(tblScheduleRoomItemBeforeUpdateHooks, tblScheduleRoomItemHook)
		tblScheduleRoomItemBeforeUpdateMu.Unlock()
	case boil.AfterUpdateHook:
		tblScheduleRoomItemAfterUpdateMu.Lock()
		tblScheduleRoomItemAfterUpdateHooks = append(tblScheduleRoomItemAfterUpdateHooks, tblScheduleRoomItemHook)
		tblScheduleRoomItemAfterUpdateMu.Unlock()
	case boil.BeforeDeleteHook:
		tblScheduleRoomItemBeforeDeleteMu.Lock()
		tblScheduleRoomItemBeforeDeleteHooks = append(tblScheduleRoomItemBeforeDeleteHooks, tblScheduleRoomItemHook)
		tblScheduleRoomItemBeforeDeleteMu.Unlock()
	case boil.AfterDeleteHook:
		tblScheduleRoomItemAfterDeleteMu.Lock()
		tblScheduleRoomItemAfterDeleteHooks = append(tblScheduleRoomItemAfterDeleteHooks, tblScheduleRoomItemHook)
		tblScheduleRoomItemAfterDeleteMu.Unlock()
	case boil.BeforeUpsertHook:
		tblScheduleRoomItemBeforeUpsertMu.Lock()
		tblScheduleRoomItemBeforeUpsertHooks = append(tblScheduleRoomItemBeforeUpsertHooks, tblScheduleRoomItemHook)
		tblScheduleRoomItemBeforeUpsertMu.Unlock()
	case boil.AfterUpsertHook:
		tblScheduleRoomItemAfterUpsertMu.Lock()
		tblScheduleRoomItemAfterUpsertHooks = append(tblScheduleRoomItemAfterUpsertHooks, tblScheduleRoomItemHook)
		tblScheduleRoomItemAfterUpsertMu.Unlock()
	}
}

// One returns a single tblScheduleRoomItem record from the query.
func (q tblScheduleRoomItemQuery) One(ctx context.Context, exec boil.ContextExecutor) (*TBLScheduleRoomItem, error) {
	o := &TBLScheduleRoomItem{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "dto: failed to execute a one query for tbl_schedule_room_items")
	}

	if err := o.doAfterSelectHooks(ctx, exec); err != nil {
		return o, err
	}

	return o, nil
}

// All returns all TBLScheduleRoomItem records from the query.
func (q tblScheduleRoomItemQuery) All(ctx context.Context, exec boil.ContextExecutor) (TBLScheduleRoomItemSlice, error) {
	var o []*TBLScheduleRoomItem

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "dto: failed to assign all query results to TBLScheduleRoomItem slice")
	}

	if len(tblScheduleRoomItemAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(ctx, exec); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// Count returns the count of all TBLScheduleRoomItem records in the query.
func (q tblScheduleRoomItemQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "dto: failed to count tbl_schedule_room_items rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q tblScheduleRoomItemQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "dto: failed to check if tbl_schedule_room_items exists")
	}

	return count > 0, nil
}

// Schedule pointed to by the foreign key.
func (o *TBLScheduleRoomItem) Schedule(mods ...qm.QueryMod) tblScheduleQuery {
	queryMods := []qm.QueryMod{
		qm.Where("`id` = ?", o.ScheduleID),
	}

	queryMods = append(queryMods, mods...)

	return TBLSchedules(queryMods...)
}

// LoadSchedule allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (tblScheduleRoomItemL) LoadSchedule(ctx context.Context, e boil.ContextExecutor, singular bool, maybeTBLScheduleRoomItem interface{}, mods queries.Applicator) error {
	var slice []*TBLScheduleRoomItem
	var object *TBLScheduleRoomItem

	if singular {
		var ok bool
		object, ok = maybeTBLScheduleRoomItem.(*TBLScheduleRoomItem)
		if !ok {
			object = new(TBLScheduleRoomItem)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeTBLScheduleRoomItem)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeTBLScheduleRoomItem))
			}
		}
	} else {
		s, ok := maybeTBLScheduleRoomItem.(*[]*TBLScheduleRoomItem)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeTBLScheduleRoomItem)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeTBLScheduleRoomItem))
			}
		}
	}

	args := make(map[interface{}]struct{})
	if singular {
		if object.R == nil {
			object.R = &tblScheduleRoomItemR{}
		}
		args[object.ScheduleID] = struct{}{}

	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &tblScheduleRoomItemR{}
			}

			args[obj.ScheduleID] = struct{}{}

		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]interface{}, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`tbl_schedules`),
		qm.WhereIn(`tbl_schedules.id in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load TBLSchedule")
	}

	var resultSlice []*TBLSchedule
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice TBLSchedule")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for tbl_schedules")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for tbl_schedules")
	}

	if len(tblScheduleAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.Schedule = foreign
		if foreign.R == nil {
			foreign.R = &tblScheduleR{}
		}
		foreign.R.ScheduleTBLScheduleRoomItems = append(foreign.R.ScheduleTBLScheduleRoomItems, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if local.ScheduleID == foreign.ID {
				local.R.Schedule = foreign
				if foreign.R == nil {
					foreign.R = &tblScheduleR{}
				}
				foreign.R.ScheduleTBLScheduleRoomItems = append(foreign.R.ScheduleTBLScheduleRoomItems, local)
				break
			}
		}
	}

	return nil
}

// SetSchedule of the tblScheduleRoomItem to the related item.
// Sets o.R.Schedule to related.
// Adds o to related.R.ScheduleTBLScheduleRoomItems.
func (o *TBLScheduleRoomItem) SetSchedule(ctx context.Context, exec boil.ContextExecutor, insert bool, related *TBLSchedule) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE `tbl_schedule_room_items` SET %s WHERE %s",
		strmangle.SetParamNames("`", "`", 0, []string{"schedule_id"}),
		strmangle.WhereClause("`", "`", 0, tblScheduleRoomItemPrimaryKeyColumns),
	)
	values := []interface{}{related.ID, o.ID}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, updateQuery)
		fmt.Fprintln(writer, values)
	}
	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	o.ScheduleID = related.ID
	if o.R == nil {
		o.R = &tblScheduleRoomItemR{
			Schedule: related,
		}
	} else {
		o.R.Schedule = related
	}

	if related.R == nil {
		related.R = &tblScheduleR{
			ScheduleTBLScheduleRoomItems: TBLScheduleRoomItemSlice{o},
		}
	} else {
		related.R.ScheduleTBLScheduleRoomItems = append(related.R.ScheduleTBLScheduleRoomItems, o)
	}

	return nil
}

// TBLScheduleRoomItems retrieves all the records using an executor.
func TBLScheduleRoomItems(mods ...qm.QueryMod) tblScheduleRoomItemQuery {
	mods = append(mods, qm.From("`tbl_schedule_room_items`"))
	q := NewQuery(mods...)
	if len(queries.GetSelect(q)) == 0 {
		queries.SetSelect(q, []string{"`tbl_schedule_room_items`.*"})
	}

	return tblScheduleRoomItemQuery{q}
}

// FindTBLScheduleRoomItem retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindTBLScheduleRoomItem(ctx context.Context, exec boil.ContextExecutor, iD int, selectCols ...string) (*TBLScheduleRoomItem, error) {
	tblScheduleRoomItemObj := &TBLScheduleRoomItem{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from `tbl_schedule_room_items` where `id`=?", sel,
	)

	q := queries.Raw(query, iD)

	err := q.Bind(ctx, exec, tblScheduleRoomItemObj)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "dto: unable to select from tbl_schedule_room_items")
	}

	if err = tblScheduleRoomItemObj.doAfterSelectHooks(ctx, exec); err != nil {
		return tblScheduleRoomItemObj, err
	}

	return tblScheduleRoomItemObj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *TBLScheduleRoomItem) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("dto: no tbl_schedule_room_items provided for insertion")
	}

	var err error

	if err := o.doBeforeInsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(tblScheduleRoomItemColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	tblScheduleRoomItemInsertCacheMut.RLock()
	cache, cached := tblScheduleRoomItemInsertCache[key]
	tblScheduleRoomItemInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			tblScheduleRoomItemAllColumns,
			tblScheduleRoomItemColumnsWithDefault,
			tblScheduleRoomItemColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(tblScheduleRoomItemType, tblScheduleRoomItemMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(tblScheduleRoomItemType, tblScheduleRoomItemMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO `tbl_schedule_room_items` (`%s`) %%sVALUES (%s)%%s", strings.Join(wl, "`,`"), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO `tbl_schedule_room_items` () VALUES ()%s%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			cache.retQuery = fmt.Sprintf("SELECT `%s` FROM `tbl_schedule_room_items` WHERE %s", strings.Join(returnColumns, "`,`"), strmangle.WhereClause("`", "`", 0, tblScheduleRoomItemPrimaryKeyColumns))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	result, err := exec.ExecContext(ctx, cache.query, vals...)

	if err != nil {
		return errors.Wrap(err, "dto: unable to insert into tbl_schedule_room_items")
	}

	var lastID int64
	var identifierCols []interface{}

	if len(cache.retMapping) == 0 {
		goto CacheNoHooks
	}

	lastID, err = result.LastInsertId()
	if err != nil {
		return ErrSyncFail
	}

	o.ID = int(lastID)
	if lastID != 0 && len(cache.retMapping) == 1 && cache.retMapping[0] == tblScheduleRoomItemMapping["id"] {
		goto CacheNoHooks
	}

	identifierCols = []interface{}{
		o.ID,
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.retQuery)
		fmt.Fprintln(writer, identifierCols...)
	}
	err = exec.QueryRowContext(ctx, cache.retQuery, identifierCols...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	if err != nil {
		return errors.Wrap(err, "dto: unable to populate default values for tbl_schedule_room_items")
	}

CacheNoHooks:
	if !cached {
		tblScheduleRoomItemInsertCacheMut.Lock()
		tblScheduleRoomItemInsertCache[key] = cache
		tblScheduleRoomItemInsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(ctx, exec)
}

// Update uses an executor to update the TBLScheduleRoomItem.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *TBLScheduleRoomItem) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	var err error
	if err = o.doBeforeUpdateHooks(ctx, exec); err != nil {
		return 0, err
	}
	key := makeCacheKey(columns, nil)
	tblScheduleRoomItemUpdateCacheMut.RLock()
	cache, cached := tblScheduleRoomItemUpdateCache[key]
	tblScheduleRoomItemUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			tblScheduleRoomItemAllColumns,
			tblScheduleRoomItemPrimaryKeyColumns,
		)
		if len(wl) == 0 {
			return 0, errors.New("dto: unable to update tbl_schedule_room_items, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE `tbl_schedule_room_items` SET %s WHERE %s",
			strmangle.SetParamNames("`", "`", 0, wl),
			strmangle.WhereClause("`", "`", 0, tblScheduleRoomItemPrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(tblScheduleRoomItemType, tblScheduleRoomItemMapping, append(wl, tblScheduleRoomItemPrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "dto: unable to update tbl_schedule_room_items row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "dto: failed to get rows affected by update for tbl_schedule_room_items")
	}

	if !cached {
		tblScheduleRoomItemUpdateCacheMut.Lock()
		tblScheduleRoomItemUpdateCache[key] = cache
		tblScheduleRoomItemUpdateCacheMut.Unlock()
	}

	return rowsAff, o.doAfterUpdateHooks(ctx, exec)
}

// UpdateAll updates all rows with the specified column values.
func (q tblScheduleRoomItemQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "dto: unable to update all for tbl_schedule_room_items")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "dto: unable to retrieve rows affected for tbl_schedule_room_items")
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o TBLScheduleRoomItemSlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("dto: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), tblScheduleRoomItemPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE `tbl_schedule_room_items` SET %s WHERE %s",
		strmangle.SetParamNames("`", "`", 0, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, tblScheduleRoomItemPrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "dto: unable to update all in tblScheduleRoomItem slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "dto: unable to retrieve rows affected all in update all tblScheduleRoomItem")
	}
	return rowsAff, nil
}

var mySQLTBLScheduleRoomItemUniqueColumns = []string{
	"id",
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *TBLScheduleRoomItem) Upsert(ctx context.Context, exec boil.ContextExecutor, updateColumns, insertColumns boil.Columns) error {
	if o == nil {
		return errors.New("dto: no tbl_schedule_room_items provided for upsert")
	}

	if err := o.doBeforeUpsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(tblScheduleRoomItemColumnsWithDefault, o)
	nzUniques := queries.NonZeroDefaultSet(mySQLTBLScheduleRoomItemUniqueColumns, o)

	if len(nzUniques) == 0 {
		return errors.New("cannot upsert with a table that cannot conflict on a unique column")
	}

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzUniques {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	tblScheduleRoomItemUpsertCacheMut.RLock()
	cache, cached := tblScheduleRoomItemUpsertCache[key]
	tblScheduleRoomItemUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, _ := insertColumns.InsertColumnSet(
			tblScheduleRoomItemAllColumns,
			tblScheduleRoomItemColumnsWithDefault,
			tblScheduleRoomItemColumnsWithoutDefault,
			nzDefaults,
		)

		update := updateColumns.UpdateColumnSet(
			tblScheduleRoomItemAllColumns,
			tblScheduleRoomItemPrimaryKeyColumns,
		)

		if !updateColumns.IsNone() && len(update) == 0 {
			return errors.New("dto: unable to upsert tbl_schedule_room_items, could not build update column list")
		}

		ret := strmangle.SetComplement(tblScheduleRoomItemAllColumns, strmangle.SetIntersect(insert, update))

		cache.query = buildUpsertQueryMySQL(dialect, "`tbl_schedule_room_items`", update, insert)
		cache.retQuery = fmt.Sprintf(
			"SELECT %s FROM `tbl_schedule_room_items` WHERE %s",
			strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, ret), ","),
			strmangle.WhereClause("`", "`", 0, nzUniques),
		)

		cache.valueMapping, err = queries.BindMapping(tblScheduleRoomItemType, tblScheduleRoomItemMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(tblScheduleRoomItemType, tblScheduleRoomItemMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	result, err := exec.ExecContext(ctx, cache.query, vals...)

	if err != nil {
		return errors.Wrap(err, "dto: unable to upsert for tbl_schedule_room_items")
	}

	var lastID int64
	var uniqueMap []uint64
	var nzUniqueCols []interface{}

	if len(cache.retMapping) == 0 {
		goto CacheNoHooks
	}

	lastID, err = result.LastInsertId()
	if err != nil {
		return ErrSyncFail
	}

	o.ID = int(lastID)
	if lastID != 0 && len(cache.retMapping) == 1 && cache.retMapping[0] == tblScheduleRoomItemMapping["id"] {
		goto CacheNoHooks
	}

	uniqueMap, err = queries.BindMapping(tblScheduleRoomItemType, tblScheduleRoomItemMapping, nzUniques)
	if err != nil {
		return errors.Wrap(err, "dto: unable to retrieve unique values for tbl_schedule_room_items")
	}
	nzUniqueCols = queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), uniqueMap)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.retQuery)
		fmt.Fprintln(writer, nzUniqueCols...)
	}
	err = exec.QueryRowContext(ctx, cache.retQuery, nzUniqueCols...).Scan(returns...)
	if err != nil {
		return errors.Wrap(err, "dto: unable to populate default values for tbl_schedule_room_items")
	}

CacheNoHooks:
	if !cached {
		tblScheduleRoomItemUpsertCacheMut.Lock()
		tblScheduleRoomItemUpsertCache[key] = cache
		tblScheduleRoomItemUpsertCacheMut.Unlock()
	}

	return o.doAfterUpsertHooks(ctx, exec)
}

// Delete deletes a single TBLScheduleRoomItem record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *TBLScheduleRoomItem) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("dto: no TBLScheduleRoomItem provided for delete")
	}

	if err := o.doBeforeDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), tblScheduleRoomItemPrimaryKeyMapping)
	sql := "DELETE FROM `tbl_schedule_room_items` WHERE `id`=?"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "dto: unable to delete from tbl_schedule_room_items")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "dto: failed to get rows affected by delete for tbl_schedule_room_items")
	}

	if err := o.doAfterDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	return rowsAff, nil
}

// DeleteAll deletes all matching rows.
func (q tblScheduleRoomItemQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("dto: no tblScheduleRoomItemQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "dto: unable to delete all from tbl_schedule_room_items")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "dto: failed to get rows affected by deleteall for tbl_schedule_room_items")
	}

	return rowsAff, nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o TBLScheduleRoomItemSlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	if len(tblScheduleRoomItemBeforeDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doBeforeDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), tblScheduleRoomItemPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM `tbl_schedule_room_items` WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, tblScheduleRoomItemPrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "dto: unable to delete all from tblScheduleRoomItem slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "dto: failed to get rows affected by deleteall for tbl_schedule_room_items")
	}

	if len(tblScheduleRoomItemAfterDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	return rowsAff, nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *TBLScheduleRoomItem) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindTBLScheduleRoomItem(ctx, exec, o.ID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *TBLScheduleRoomItemSlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := TBLScheduleRoomItemSlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), tblScheduleRoomItemPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT `tbl_schedule_room_items`.* FROM `tbl_schedule_room_items` WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, tblScheduleRoomItemPrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "dto: unable to reload all in TBLScheduleRoomItemSlice")
	}

	*o = slice

	return nil
}

// TBLScheduleRoomItemExists checks if the TBLScheduleRoomItem row exists.
func TBLScheduleRoomItemExists(ctx context.Context, exec boil.ContextExecutor, iD int) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from `tbl_schedule_room_items` where `id`=? limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, iD)
	}
	row := exec.QueryRowContext(ctx, sql, iD)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "dto: unable to check if tbl_schedule_room_items exists")
	}

	return exists, nil
}

// Exists checks if the TBLScheduleRoomItem row exists.
func (o *TBLScheduleRoomItem) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	return TBLScheduleRoomItemExists(ctx, exec, o.ID)
}
