// Code generated by SQLBoiler 4.19.5 (https://github.com/aarondl/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dto

var TableNames = struct {
	DataCampuses              string
	DataLessons               string
	DataRoles                 string
	DataRooms                 string
	SysSessions               string
	TBLScheduleInvisibleRooms string
	TBLScheduleItems          string
	TBLScheduleRoomItems      string
	TBLSchedules              string
	TBLUsers                  string
}{
	DataCampuses:              "data_campuses",
	DataLessons:               "data_lessons",
	DataRoles:                 "data_roles",
	DataRooms:                 "data_rooms",
	SysSessions:               "sys_sessions",
	TBLScheduleInvisibleRooms: "tbl_schedule_invisible_rooms",
	TBLScheduleItems:          "tbl_schedule_items",
	TBLScheduleRoomItems:      "tbl_schedule_room_items",
	TBLSchedules:              "tbl_schedules",
	TBLUsers:                  "tbl_users",
}
