// Code generated by SQLBoiler 4.19.5 (https://github.com/aarondl/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dto

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/aarondl/sqlboiler/v4/boil"
	"github.com/aarondl/sqlboiler/v4/queries"
	"github.com/aarondl/sqlboiler/v4/queries/qm"
	"github.com/aarondl/sqlboiler/v4/queries/qmhelper"
	"github.com/aarondl/strmangle"
	"github.com/friendsofgo/errors"
)

// DataCampuse is an object representing the database table.
type DataCampuse struct {
	ID         int       `boil:"id" json:"id" toml:"id" yaml:"id"`
	Campus     string    `boil:"campus" json:"campus" toml:"campus" yaml:"campus"`
	CampusName string    `boil:"campus_name" json:"campus_name" toml:"campus_name" yaml:"campus_name"`
	OrderIndex int       `boil:"order_index" json:"order_index" toml:"order_index" yaml:"order_index"`
	CreatedAt  time.Time `boil:"created_at" json:"created_at" toml:"created_at" yaml:"created_at"`
	UpdatedAt  time.Time `boil:"updated_at" json:"updated_at" toml:"updated_at" yaml:"updated_at"`

	R *dataCampuseR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L dataCampuseL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var DataCampuseColumns = struct {
	ID         string
	Campus     string
	CampusName string
	OrderIndex string
	CreatedAt  string
	UpdatedAt  string
}{
	ID:         "id",
	Campus:     "campus",
	CampusName: "campus_name",
	OrderIndex: "order_index",
	CreatedAt:  "created_at",
	UpdatedAt:  "updated_at",
}

var DataCampuseTableColumns = struct {
	ID         string
	Campus     string
	CampusName string
	OrderIndex string
	CreatedAt  string
	UpdatedAt  string
}{
	ID:         "data_campuses.id",
	Campus:     "data_campuses.campus",
	CampusName: "data_campuses.campus_name",
	OrderIndex: "data_campuses.order_index",
	CreatedAt:  "data_campuses.created_at",
	UpdatedAt:  "data_campuses.updated_at",
}

// Generated where

type whereHelperint struct{ field string }

func (w whereHelperint) EQ(x int) qm.QueryMod  { return qmhelper.Where(w.field, qmhelper.EQ, x) }
func (w whereHelperint) NEQ(x int) qm.QueryMod { return qmhelper.Where(w.field, qmhelper.NEQ, x) }
func (w whereHelperint) LT(x int) qm.QueryMod  { return qmhelper.Where(w.field, qmhelper.LT, x) }
func (w whereHelperint) LTE(x int) qm.QueryMod { return qmhelper.Where(w.field, qmhelper.LTE, x) }
func (w whereHelperint) GT(x int) qm.QueryMod  { return qmhelper.Where(w.field, qmhelper.GT, x) }
func (w whereHelperint) GTE(x int) qm.QueryMod { return qmhelper.Where(w.field, qmhelper.GTE, x) }
func (w whereHelperint) IN(slice []int) qm.QueryMod {
	values := make([]interface{}, 0, len(slice))
	for _, value := range slice {
		values = append(values, value)
	}
	return qm.WhereIn(fmt.Sprintf("%s IN ?", w.field), values...)
}
func (w whereHelperint) NIN(slice []int) qm.QueryMod {
	values := make([]interface{}, 0, len(slice))
	for _, value := range slice {
		values = append(values, value)
	}
	return qm.WhereNotIn(fmt.Sprintf("%s NOT IN ?", w.field), values...)
}

type whereHelperstring struct{ field string }

func (w whereHelperstring) EQ(x string) qm.QueryMod    { return qmhelper.Where(w.field, qmhelper.EQ, x) }
func (w whereHelperstring) NEQ(x string) qm.QueryMod   { return qmhelper.Where(w.field, qmhelper.NEQ, x) }
func (w whereHelperstring) LT(x string) qm.QueryMod    { return qmhelper.Where(w.field, qmhelper.LT, x) }
func (w whereHelperstring) LTE(x string) qm.QueryMod   { return qmhelper.Where(w.field, qmhelper.LTE, x) }
func (w whereHelperstring) GT(x string) qm.QueryMod    { return qmhelper.Where(w.field, qmhelper.GT, x) }
func (w whereHelperstring) GTE(x string) qm.QueryMod   { return qmhelper.Where(w.field, qmhelper.GTE, x) }
func (w whereHelperstring) LIKE(x string) qm.QueryMod  { return qm.Where(w.field+" LIKE ?", x) }
func (w whereHelperstring) NLIKE(x string) qm.QueryMod { return qm.Where(w.field+" NOT LIKE ?", x) }
func (w whereHelperstring) IN(slice []string) qm.QueryMod {
	values := make([]interface{}, 0, len(slice))
	for _, value := range slice {
		values = append(values, value)
	}
	return qm.WhereIn(fmt.Sprintf("%s IN ?", w.field), values...)
}
func (w whereHelperstring) NIN(slice []string) qm.QueryMod {
	values := make([]interface{}, 0, len(slice))
	for _, value := range slice {
		values = append(values, value)
	}
	return qm.WhereNotIn(fmt.Sprintf("%s NOT IN ?", w.field), values...)
}

type whereHelpertime_Time struct{ field string }

func (w whereHelpertime_Time) EQ(x time.Time) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.EQ, x)
}
func (w whereHelpertime_Time) NEQ(x time.Time) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.NEQ, x)
}
func (w whereHelpertime_Time) LT(x time.Time) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.LT, x)
}
func (w whereHelpertime_Time) LTE(x time.Time) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.LTE, x)
}
func (w whereHelpertime_Time) GT(x time.Time) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.GT, x)
}
func (w whereHelpertime_Time) GTE(x time.Time) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.GTE, x)
}

var DataCampuseWhere = struct {
	ID         whereHelperint
	Campus     whereHelperstring
	CampusName whereHelperstring
	OrderIndex whereHelperint
	CreatedAt  whereHelpertime_Time
	UpdatedAt  whereHelpertime_Time
}{
	ID:         whereHelperint{field: "`data_campuses`.`id`"},
	Campus:     whereHelperstring{field: "`data_campuses`.`campus`"},
	CampusName: whereHelperstring{field: "`data_campuses`.`campus_name`"},
	OrderIndex: whereHelperint{field: "`data_campuses`.`order_index`"},
	CreatedAt:  whereHelpertime_Time{field: "`data_campuses`.`created_at`"},
	UpdatedAt:  whereHelpertime_Time{field: "`data_campuses`.`updated_at`"},
}

// DataCampuseRels is where relationship names are stored.
var DataCampuseRels = struct {
	CampusDataLessons  string
	CampusDataRooms    string
	CampusTBLSchedules string
}{
	CampusDataLessons:  "CampusDataLessons",
	CampusDataRooms:    "CampusDataRooms",
	CampusTBLSchedules: "CampusTBLSchedules",
}

// dataCampuseR is where relationships are stored.
type dataCampuseR struct {
	CampusDataLessons  DataLessonSlice  `boil:"CampusDataLessons" json:"CampusDataLessons" toml:"CampusDataLessons" yaml:"CampusDataLessons"`
	CampusDataRooms    DataRoomSlice    `boil:"CampusDataRooms" json:"CampusDataRooms" toml:"CampusDataRooms" yaml:"CampusDataRooms"`
	CampusTBLSchedules TBLScheduleSlice `boil:"CampusTBLSchedules" json:"CampusTBLSchedules" toml:"CampusTBLSchedules" yaml:"CampusTBLSchedules"`
}

// NewStruct creates a new relationship struct
func (*dataCampuseR) NewStruct() *dataCampuseR {
	return &dataCampuseR{}
}

func (o *DataCampuse) GetCampusDataLessons() DataLessonSlice {
	if o == nil {
		return nil
	}

	return o.R.GetCampusDataLessons()
}

func (r *dataCampuseR) GetCampusDataLessons() DataLessonSlice {
	if r == nil {
		return nil
	}

	return r.CampusDataLessons
}

func (o *DataCampuse) GetCampusDataRooms() DataRoomSlice {
	if o == nil {
		return nil
	}

	return o.R.GetCampusDataRooms()
}

func (r *dataCampuseR) GetCampusDataRooms() DataRoomSlice {
	if r == nil {
		return nil
	}

	return r.CampusDataRooms
}

func (o *DataCampuse) GetCampusTBLSchedules() TBLScheduleSlice {
	if o == nil {
		return nil
	}

	return o.R.GetCampusTBLSchedules()
}

func (r *dataCampuseR) GetCampusTBLSchedules() TBLScheduleSlice {
	if r == nil {
		return nil
	}

	return r.CampusTBLSchedules
}

// dataCampuseL is where Load methods for each relationship are stored.
type dataCampuseL struct{}

var (
	dataCampuseAllColumns            = []string{"id", "campus", "campus_name", "order_index", "created_at", "updated_at"}
	dataCampuseColumnsWithoutDefault = []string{"campus", "campus_name", "order_index"}
	dataCampuseColumnsWithDefault    = []string{"id", "created_at", "updated_at"}
	dataCampusePrimaryKeyColumns     = []string{"id"}
	dataCampuseGeneratedColumns      = []string{}
)

type (
	// DataCampuseSlice is an alias for a slice of pointers to DataCampuse.
	// This should almost always be used instead of []DataCampuse.
	DataCampuseSlice []*DataCampuse
	// DataCampuseHook is the signature for custom DataCampuse hook methods
	DataCampuseHook func(context.Context, boil.ContextExecutor, *DataCampuse) error

	dataCampuseQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	dataCampuseType                 = reflect.TypeOf(&DataCampuse{})
	dataCampuseMapping              = queries.MakeStructMapping(dataCampuseType)
	dataCampusePrimaryKeyMapping, _ = queries.BindMapping(dataCampuseType, dataCampuseMapping, dataCampusePrimaryKeyColumns)
	dataCampuseInsertCacheMut       sync.RWMutex
	dataCampuseInsertCache          = make(map[string]insertCache)
	dataCampuseUpdateCacheMut       sync.RWMutex
	dataCampuseUpdateCache          = make(map[string]updateCache)
	dataCampuseUpsertCacheMut       sync.RWMutex
	dataCampuseUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

var dataCampuseAfterSelectMu sync.Mutex
var dataCampuseAfterSelectHooks []DataCampuseHook

var dataCampuseBeforeInsertMu sync.Mutex
var dataCampuseBeforeInsertHooks []DataCampuseHook
var dataCampuseAfterInsertMu sync.Mutex
var dataCampuseAfterInsertHooks []DataCampuseHook

var dataCampuseBeforeUpdateMu sync.Mutex
var dataCampuseBeforeUpdateHooks []DataCampuseHook
var dataCampuseAfterUpdateMu sync.Mutex
var dataCampuseAfterUpdateHooks []DataCampuseHook

var dataCampuseBeforeDeleteMu sync.Mutex
var dataCampuseBeforeDeleteHooks []DataCampuseHook
var dataCampuseAfterDeleteMu sync.Mutex
var dataCampuseAfterDeleteHooks []DataCampuseHook

var dataCampuseBeforeUpsertMu sync.Mutex
var dataCampuseBeforeUpsertHooks []DataCampuseHook
var dataCampuseAfterUpsertMu sync.Mutex
var dataCampuseAfterUpsertHooks []DataCampuseHook

// doAfterSelectHooks executes all "after Select" hooks.
func (o *DataCampuse) doAfterSelectHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range dataCampuseAfterSelectHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *DataCampuse) doBeforeInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range dataCampuseBeforeInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *DataCampuse) doAfterInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range dataCampuseAfterInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpdateHooks executes all "before Update" hooks.
func (o *DataCampuse) doBeforeUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range dataCampuseBeforeUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpdateHooks executes all "after Update" hooks.
func (o *DataCampuse) doAfterUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range dataCampuseAfterUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeDeleteHooks executes all "before Delete" hooks.
func (o *DataCampuse) doBeforeDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range dataCampuseBeforeDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterDeleteHooks executes all "after Delete" hooks.
func (o *DataCampuse) doAfterDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range dataCampuseAfterDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *DataCampuse) doBeforeUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range dataCampuseBeforeUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *DataCampuse) doAfterUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range dataCampuseAfterUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddDataCampuseHook registers your hook function for all future operations.
func AddDataCampuseHook(hookPoint boil.HookPoint, dataCampuseHook DataCampuseHook) {
	switch hookPoint {
	case boil.AfterSelectHook:
		dataCampuseAfterSelectMu.Lock()
		dataCampuseAfterSelectHooks = append(dataCampuseAfterSelectHooks, dataCampuseHook)
		dataCampuseAfterSelectMu.Unlock()
	case boil.BeforeInsertHook:
		dataCampuseBeforeInsertMu.Lock()
		dataCampuseBeforeInsertHooks = append(dataCampuseBeforeInsertHooks, dataCampuseHook)
		dataCampuseBeforeInsertMu.Unlock()
	case boil.AfterInsertHook:
		dataCampuseAfterInsertMu.Lock()
		dataCampuseAfterInsertHooks = append(dataCampuseAfterInsertHooks, dataCampuseHook)
		dataCampuseAfterInsertMu.Unlock()
	case boil.BeforeUpdateHook:
		dataCampuseBeforeUpdateMu.Lock()
		dataCampuseBeforeUpdateHooks = append(dataCampuseBeforeUpdateHooks, dataCampuseHook)
		dataCampuseBeforeUpdateMu.Unlock()
	case boil.AfterUpdateHook:
		dataCampuseAfterUpdateMu.Lock()
		dataCampuseAfterUpdateHooks = append(dataCampuseAfterUpdateHooks, dataCampuseHook)
		dataCampuseAfterUpdateMu.Unlock()
	case boil.BeforeDeleteHook:
		dataCampuseBeforeDeleteMu.Lock()
		dataCampuseBeforeDeleteHooks = append(dataCampuseBeforeDeleteHooks, dataCampuseHook)
		dataCampuseBeforeDeleteMu.Unlock()
	case boil.AfterDeleteHook:
		dataCampuseAfterDeleteMu.Lock()
		dataCampuseAfterDeleteHooks = append(dataCampuseAfterDeleteHooks, dataCampuseHook)
		dataCampuseAfterDeleteMu.Unlock()
	case boil.BeforeUpsertHook:
		dataCampuseBeforeUpsertMu.Lock()
		dataCampuseBeforeUpsertHooks = append(dataCampuseBeforeUpsertHooks, dataCampuseHook)
		dataCampuseBeforeUpsertMu.Unlock()
	case boil.AfterUpsertHook:
		dataCampuseAfterUpsertMu.Lock()
		dataCampuseAfterUpsertHooks = append(dataCampuseAfterUpsertHooks, dataCampuseHook)
		dataCampuseAfterUpsertMu.Unlock()
	}
}

// One returns a single dataCampuse record from the query.
func (q dataCampuseQuery) One(ctx context.Context, exec boil.ContextExecutor) (*DataCampuse, error) {
	o := &DataCampuse{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "dto: failed to execute a one query for data_campuses")
	}

	if err := o.doAfterSelectHooks(ctx, exec); err != nil {
		return o, err
	}

	return o, nil
}

// All returns all DataCampuse records from the query.
func (q dataCampuseQuery) All(ctx context.Context, exec boil.ContextExecutor) (DataCampuseSlice, error) {
	var o []*DataCampuse

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "dto: failed to assign all query results to DataCampuse slice")
	}

	if len(dataCampuseAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(ctx, exec); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// Count returns the count of all DataCampuse records in the query.
func (q dataCampuseQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "dto: failed to count data_campuses rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q dataCampuseQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "dto: failed to check if data_campuses exists")
	}

	return count > 0, nil
}

// CampusDataLessons retrieves all the data_lesson's DataLessons with an executor via campus column.
func (o *DataCampuse) CampusDataLessons(mods ...qm.QueryMod) dataLessonQuery {
	var queryMods []qm.QueryMod
	if len(mods) != 0 {
		queryMods = append(queryMods, mods...)
	}

	queryMods = append(queryMods,
		qm.Where("`data_lessons`.`campus`=?", o.Campus),
	)

	return DataLessons(queryMods...)
}

// CampusDataRooms retrieves all the data_room's DataRooms with an executor via campus column.
func (o *DataCampuse) CampusDataRooms(mods ...qm.QueryMod) dataRoomQuery {
	var queryMods []qm.QueryMod
	if len(mods) != 0 {
		queryMods = append(queryMods, mods...)
	}

	queryMods = append(queryMods,
		qm.Where("`data_rooms`.`campus`=?", o.Campus),
	)

	return DataRooms(queryMods...)
}

// CampusTBLSchedules retrieves all the tbl_schedule's TBLSchedules with an executor via campus column.
func (o *DataCampuse) CampusTBLSchedules(mods ...qm.QueryMod) tblScheduleQuery {
	var queryMods []qm.QueryMod
	if len(mods) != 0 {
		queryMods = append(queryMods, mods...)
	}

	queryMods = append(queryMods,
		qm.Where("`tbl_schedules`.`campus`=?", o.Campus),
	)

	return TBLSchedules(queryMods...)
}

// LoadCampusDataLessons allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for a 1-M or N-M relationship.
func (dataCampuseL) LoadCampusDataLessons(ctx context.Context, e boil.ContextExecutor, singular bool, maybeDataCampuse interface{}, mods queries.Applicator) error {
	var slice []*DataCampuse
	var object *DataCampuse

	if singular {
		var ok bool
		object, ok = maybeDataCampuse.(*DataCampuse)
		if !ok {
			object = new(DataCampuse)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeDataCampuse)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeDataCampuse))
			}
		}
	} else {
		s, ok := maybeDataCampuse.(*[]*DataCampuse)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeDataCampuse)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeDataCampuse))
			}
		}
	}

	args := make(map[interface{}]struct{})
	if singular {
		if object.R == nil {
			object.R = &dataCampuseR{}
		}
		args[object.Campus] = struct{}{}
	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &dataCampuseR{}
			}
			args[obj.Campus] = struct{}{}
		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]interface{}, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`data_lessons`),
		qm.WhereIn(`data_lessons.campus in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load data_lessons")
	}

	var resultSlice []*DataLesson
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice data_lessons")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results in eager load on data_lessons")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for data_lessons")
	}

	if len(dataLessonAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}
	if singular {
		object.R.CampusDataLessons = resultSlice
		for _, foreign := range resultSlice {
			if foreign.R == nil {
				foreign.R = &dataLessonR{}
			}
			foreign.R.CampusDataCampuse = object
		}
		return nil
	}

	for _, foreign := range resultSlice {
		for _, local := range slice {
			if local.Campus == foreign.Campus {
				local.R.CampusDataLessons = append(local.R.CampusDataLessons, foreign)
				if foreign.R == nil {
					foreign.R = &dataLessonR{}
				}
				foreign.R.CampusDataCampuse = local
				break
			}
		}
	}

	return nil
}

// LoadCampusDataRooms allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for a 1-M or N-M relationship.
func (dataCampuseL) LoadCampusDataRooms(ctx context.Context, e boil.ContextExecutor, singular bool, maybeDataCampuse interface{}, mods queries.Applicator) error {
	var slice []*DataCampuse
	var object *DataCampuse

	if singular {
		var ok bool
		object, ok = maybeDataCampuse.(*DataCampuse)
		if !ok {
			object = new(DataCampuse)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeDataCampuse)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeDataCampuse))
			}
		}
	} else {
		s, ok := maybeDataCampuse.(*[]*DataCampuse)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeDataCampuse)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeDataCampuse))
			}
		}
	}

	args := make(map[interface{}]struct{})
	if singular {
		if object.R == nil {
			object.R = &dataCampuseR{}
		}
		args[object.Campus] = struct{}{}
	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &dataCampuseR{}
			}
			args[obj.Campus] = struct{}{}
		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]interface{}, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`data_rooms`),
		qm.WhereIn(`data_rooms.campus in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load data_rooms")
	}

	var resultSlice []*DataRoom
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice data_rooms")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results in eager load on data_rooms")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for data_rooms")
	}

	if len(dataRoomAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}
	if singular {
		object.R.CampusDataRooms = resultSlice
		for _, foreign := range resultSlice {
			if foreign.R == nil {
				foreign.R = &dataRoomR{}
			}
			foreign.R.CampusDataCampuse = object
		}
		return nil
	}

	for _, foreign := range resultSlice {
		for _, local := range slice {
			if local.Campus == foreign.Campus {
				local.R.CampusDataRooms = append(local.R.CampusDataRooms, foreign)
				if foreign.R == nil {
					foreign.R = &dataRoomR{}
				}
				foreign.R.CampusDataCampuse = local
				break
			}
		}
	}

	return nil
}

// LoadCampusTBLSchedules allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for a 1-M or N-M relationship.
func (dataCampuseL) LoadCampusTBLSchedules(ctx context.Context, e boil.ContextExecutor, singular bool, maybeDataCampuse interface{}, mods queries.Applicator) error {
	var slice []*DataCampuse
	var object *DataCampuse

	if singular {
		var ok bool
		object, ok = maybeDataCampuse.(*DataCampuse)
		if !ok {
			object = new(DataCampuse)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeDataCampuse)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeDataCampuse))
			}
		}
	} else {
		s, ok := maybeDataCampuse.(*[]*DataCampuse)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeDataCampuse)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeDataCampuse))
			}
		}
	}

	args := make(map[interface{}]struct{})
	if singular {
		if object.R == nil {
			object.R = &dataCampuseR{}
		}
		args[object.Campus] = struct{}{}
	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &dataCampuseR{}
			}
			args[obj.Campus] = struct{}{}
		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]interface{}, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`tbl_schedules`),
		qm.WhereIn(`tbl_schedules.campus in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load tbl_schedules")
	}

	var resultSlice []*TBLSchedule
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice tbl_schedules")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results in eager load on tbl_schedules")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for tbl_schedules")
	}

	if len(tblScheduleAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}
	if singular {
		object.R.CampusTBLSchedules = resultSlice
		for _, foreign := range resultSlice {
			if foreign.R == nil {
				foreign.R = &tblScheduleR{}
			}
			foreign.R.CampusDataCampuse = object
		}
		return nil
	}

	for _, foreign := range resultSlice {
		for _, local := range slice {
			if local.Campus == foreign.Campus {
				local.R.CampusTBLSchedules = append(local.R.CampusTBLSchedules, foreign)
				if foreign.R == nil {
					foreign.R = &tblScheduleR{}
				}
				foreign.R.CampusDataCampuse = local
				break
			}
		}
	}

	return nil
}

// AddCampusDataLessons adds the given related objects to the existing relationships
// of the data_campuse, optionally inserting them as new records.
// Appends related to o.R.CampusDataLessons.
// Sets related.R.CampusDataCampuse appropriately.
func (o *DataCampuse) AddCampusDataLessons(ctx context.Context, exec boil.ContextExecutor, insert bool, related ...*DataLesson) error {
	var err error
	for _, rel := range related {
		if insert {
			rel.Campus = o.Campus
			if err = rel.Insert(ctx, exec, boil.Infer()); err != nil {
				return errors.Wrap(err, "failed to insert into foreign table")
			}
		} else {
			updateQuery := fmt.Sprintf(
				"UPDATE `data_lessons` SET %s WHERE %s",
				strmangle.SetParamNames("`", "`", 0, []string{"campus"}),
				strmangle.WhereClause("`", "`", 0, dataLessonPrimaryKeyColumns),
			)
			values := []interface{}{o.Campus, rel.ID}

			if boil.IsDebug(ctx) {
				writer := boil.DebugWriterFrom(ctx)
				fmt.Fprintln(writer, updateQuery)
				fmt.Fprintln(writer, values)
			}
			if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
				return errors.Wrap(err, "failed to update foreign table")
			}

			rel.Campus = o.Campus
		}
	}

	if o.R == nil {
		o.R = &dataCampuseR{
			CampusDataLessons: related,
		}
	} else {
		o.R.CampusDataLessons = append(o.R.CampusDataLessons, related...)
	}

	for _, rel := range related {
		if rel.R == nil {
			rel.R = &dataLessonR{
				CampusDataCampuse: o,
			}
		} else {
			rel.R.CampusDataCampuse = o
		}
	}
	return nil
}

// AddCampusDataRooms adds the given related objects to the existing relationships
// of the data_campuse, optionally inserting them as new records.
// Appends related to o.R.CampusDataRooms.
// Sets related.R.CampusDataCampuse appropriately.
func (o *DataCampuse) AddCampusDataRooms(ctx context.Context, exec boil.ContextExecutor, insert bool, related ...*DataRoom) error {
	var err error
	for _, rel := range related {
		if insert {
			rel.Campus = o.Campus
			if err = rel.Insert(ctx, exec, boil.Infer()); err != nil {
				return errors.Wrap(err, "failed to insert into foreign table")
			}
		} else {
			updateQuery := fmt.Sprintf(
				"UPDATE `data_rooms` SET %s WHERE %s",
				strmangle.SetParamNames("`", "`", 0, []string{"campus"}),
				strmangle.WhereClause("`", "`", 0, dataRoomPrimaryKeyColumns),
			)
			values := []interface{}{o.Campus, rel.ID}

			if boil.IsDebug(ctx) {
				writer := boil.DebugWriterFrom(ctx)
				fmt.Fprintln(writer, updateQuery)
				fmt.Fprintln(writer, values)
			}
			if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
				return errors.Wrap(err, "failed to update foreign table")
			}

			rel.Campus = o.Campus
		}
	}

	if o.R == nil {
		o.R = &dataCampuseR{
			CampusDataRooms: related,
		}
	} else {
		o.R.CampusDataRooms = append(o.R.CampusDataRooms, related...)
	}

	for _, rel := range related {
		if rel.R == nil {
			rel.R = &dataRoomR{
				CampusDataCampuse: o,
			}
		} else {
			rel.R.CampusDataCampuse = o
		}
	}
	return nil
}

// AddCampusTBLSchedules adds the given related objects to the existing relationships
// of the data_campuse, optionally inserting them as new records.
// Appends related to o.R.CampusTBLSchedules.
// Sets related.R.CampusDataCampuse appropriately.
func (o *DataCampuse) AddCampusTBLSchedules(ctx context.Context, exec boil.ContextExecutor, insert bool, related ...*TBLSchedule) error {
	var err error
	for _, rel := range related {
		if insert {
			rel.Campus = o.Campus
			if err = rel.Insert(ctx, exec, boil.Infer()); err != nil {
				return errors.Wrap(err, "failed to insert into foreign table")
			}
		} else {
			updateQuery := fmt.Sprintf(
				"UPDATE `tbl_schedules` SET %s WHERE %s",
				strmangle.SetParamNames("`", "`", 0, []string{"campus"}),
				strmangle.WhereClause("`", "`", 0, tblSchedulePrimaryKeyColumns),
			)
			values := []interface{}{o.Campus, rel.ID}

			if boil.IsDebug(ctx) {
				writer := boil.DebugWriterFrom(ctx)
				fmt.Fprintln(writer, updateQuery)
				fmt.Fprintln(writer, values)
			}
			if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
				return errors.Wrap(err, "failed to update foreign table")
			}

			rel.Campus = o.Campus
		}
	}

	if o.R == nil {
		o.R = &dataCampuseR{
			CampusTBLSchedules: related,
		}
	} else {
		o.R.CampusTBLSchedules = append(o.R.CampusTBLSchedules, related...)
	}

	for _, rel := range related {
		if rel.R == nil {
			rel.R = &tblScheduleR{
				CampusDataCampuse: o,
			}
		} else {
			rel.R.CampusDataCampuse = o
		}
	}
	return nil
}

// DataCampuses retrieves all the records using an executor.
func DataCampuses(mods ...qm.QueryMod) dataCampuseQuery {
	mods = append(mods, qm.From("`data_campuses`"))
	q := NewQuery(mods...)
	if len(queries.GetSelect(q)) == 0 {
		queries.SetSelect(q, []string{"`data_campuses`.*"})
	}

	return dataCampuseQuery{q}
}

// FindDataCampuse retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindDataCampuse(ctx context.Context, exec boil.ContextExecutor, iD int, selectCols ...string) (*DataCampuse, error) {
	dataCampuseObj := &DataCampuse{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from `data_campuses` where `id`=?", sel,
	)

	q := queries.Raw(query, iD)

	err := q.Bind(ctx, exec, dataCampuseObj)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "dto: unable to select from data_campuses")
	}

	if err = dataCampuseObj.doAfterSelectHooks(ctx, exec); err != nil {
		return dataCampuseObj, err
	}

	return dataCampuseObj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *DataCampuse) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("dto: no data_campuses provided for insertion")
	}

	var err error

	if err := o.doBeforeInsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(dataCampuseColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	dataCampuseInsertCacheMut.RLock()
	cache, cached := dataCampuseInsertCache[key]
	dataCampuseInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			dataCampuseAllColumns,
			dataCampuseColumnsWithDefault,
			dataCampuseColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(dataCampuseType, dataCampuseMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(dataCampuseType, dataCampuseMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO `data_campuses` (`%s`) %%sVALUES (%s)%%s", strings.Join(wl, "`,`"), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO `data_campuses` () VALUES ()%s%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			cache.retQuery = fmt.Sprintf("SELECT `%s` FROM `data_campuses` WHERE %s", strings.Join(returnColumns, "`,`"), strmangle.WhereClause("`", "`", 0, dataCampusePrimaryKeyColumns))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	result, err := exec.ExecContext(ctx, cache.query, vals...)

	if err != nil {
		return errors.Wrap(err, "dto: unable to insert into data_campuses")
	}

	var lastID int64
	var identifierCols []interface{}

	if len(cache.retMapping) == 0 {
		goto CacheNoHooks
	}

	lastID, err = result.LastInsertId()
	if err != nil {
		return ErrSyncFail
	}

	o.ID = int(lastID)
	if lastID != 0 && len(cache.retMapping) == 1 && cache.retMapping[0] == dataCampuseMapping["id"] {
		goto CacheNoHooks
	}

	identifierCols = []interface{}{
		o.ID,
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.retQuery)
		fmt.Fprintln(writer, identifierCols...)
	}
	err = exec.QueryRowContext(ctx, cache.retQuery, identifierCols...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	if err != nil {
		return errors.Wrap(err, "dto: unable to populate default values for data_campuses")
	}

CacheNoHooks:
	if !cached {
		dataCampuseInsertCacheMut.Lock()
		dataCampuseInsertCache[key] = cache
		dataCampuseInsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(ctx, exec)
}

// Update uses an executor to update the DataCampuse.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *DataCampuse) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	var err error
	if err = o.doBeforeUpdateHooks(ctx, exec); err != nil {
		return 0, err
	}
	key := makeCacheKey(columns, nil)
	dataCampuseUpdateCacheMut.RLock()
	cache, cached := dataCampuseUpdateCache[key]
	dataCampuseUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			dataCampuseAllColumns,
			dataCampusePrimaryKeyColumns,
		)
		if len(wl) == 0 {
			return 0, errors.New("dto: unable to update data_campuses, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE `data_campuses` SET %s WHERE %s",
			strmangle.SetParamNames("`", "`", 0, wl),
			strmangle.WhereClause("`", "`", 0, dataCampusePrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(dataCampuseType, dataCampuseMapping, append(wl, dataCampusePrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "dto: unable to update data_campuses row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "dto: failed to get rows affected by update for data_campuses")
	}

	if !cached {
		dataCampuseUpdateCacheMut.Lock()
		dataCampuseUpdateCache[key] = cache
		dataCampuseUpdateCacheMut.Unlock()
	}

	return rowsAff, o.doAfterUpdateHooks(ctx, exec)
}

// UpdateAll updates all rows with the specified column values.
func (q dataCampuseQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "dto: unable to update all for data_campuses")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "dto: unable to retrieve rows affected for data_campuses")
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o DataCampuseSlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("dto: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), dataCampusePrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE `data_campuses` SET %s WHERE %s",
		strmangle.SetParamNames("`", "`", 0, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, dataCampusePrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "dto: unable to update all in dataCampuse slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "dto: unable to retrieve rows affected all in update all dataCampuse")
	}
	return rowsAff, nil
}

var mySQLDataCampuseUniqueColumns = []string{
	"id",
	"campus",
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *DataCampuse) Upsert(ctx context.Context, exec boil.ContextExecutor, updateColumns, insertColumns boil.Columns) error {
	if o == nil {
		return errors.New("dto: no data_campuses provided for upsert")
	}

	if err := o.doBeforeUpsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(dataCampuseColumnsWithDefault, o)
	nzUniques := queries.NonZeroDefaultSet(mySQLDataCampuseUniqueColumns, o)

	if len(nzUniques) == 0 {
		return errors.New("cannot upsert with a table that cannot conflict on a unique column")
	}

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzUniques {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	dataCampuseUpsertCacheMut.RLock()
	cache, cached := dataCampuseUpsertCache[key]
	dataCampuseUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, _ := insertColumns.InsertColumnSet(
			dataCampuseAllColumns,
			dataCampuseColumnsWithDefault,
			dataCampuseColumnsWithoutDefault,
			nzDefaults,
		)

		update := updateColumns.UpdateColumnSet(
			dataCampuseAllColumns,
			dataCampusePrimaryKeyColumns,
		)

		if !updateColumns.IsNone() && len(update) == 0 {
			return errors.New("dto: unable to upsert data_campuses, could not build update column list")
		}

		ret := strmangle.SetComplement(dataCampuseAllColumns, strmangle.SetIntersect(insert, update))

		cache.query = buildUpsertQueryMySQL(dialect, "`data_campuses`", update, insert)
		cache.retQuery = fmt.Sprintf(
			"SELECT %s FROM `data_campuses` WHERE %s",
			strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, ret), ","),
			strmangle.WhereClause("`", "`", 0, nzUniques),
		)

		cache.valueMapping, err = queries.BindMapping(dataCampuseType, dataCampuseMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(dataCampuseType, dataCampuseMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	result, err := exec.ExecContext(ctx, cache.query, vals...)

	if err != nil {
		return errors.Wrap(err, "dto: unable to upsert for data_campuses")
	}

	var lastID int64
	var uniqueMap []uint64
	var nzUniqueCols []interface{}

	if len(cache.retMapping) == 0 {
		goto CacheNoHooks
	}

	lastID, err = result.LastInsertId()
	if err != nil {
		return ErrSyncFail
	}

	o.ID = int(lastID)
	if lastID != 0 && len(cache.retMapping) == 1 && cache.retMapping[0] == dataCampuseMapping["id"] {
		goto CacheNoHooks
	}

	uniqueMap, err = queries.BindMapping(dataCampuseType, dataCampuseMapping, nzUniques)
	if err != nil {
		return errors.Wrap(err, "dto: unable to retrieve unique values for data_campuses")
	}
	nzUniqueCols = queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), uniqueMap)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.retQuery)
		fmt.Fprintln(writer, nzUniqueCols...)
	}
	err = exec.QueryRowContext(ctx, cache.retQuery, nzUniqueCols...).Scan(returns...)
	if err != nil {
		return errors.Wrap(err, "dto: unable to populate default values for data_campuses")
	}

CacheNoHooks:
	if !cached {
		dataCampuseUpsertCacheMut.Lock()
		dataCampuseUpsertCache[key] = cache
		dataCampuseUpsertCacheMut.Unlock()
	}

	return o.doAfterUpsertHooks(ctx, exec)
}

// Delete deletes a single DataCampuse record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *DataCampuse) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("dto: no DataCampuse provided for delete")
	}

	if err := o.doBeforeDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), dataCampusePrimaryKeyMapping)
	sql := "DELETE FROM `data_campuses` WHERE `id`=?"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "dto: unable to delete from data_campuses")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "dto: failed to get rows affected by delete for data_campuses")
	}

	if err := o.doAfterDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	return rowsAff, nil
}

// DeleteAll deletes all matching rows.
func (q dataCampuseQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("dto: no dataCampuseQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "dto: unable to delete all from data_campuses")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "dto: failed to get rows affected by deleteall for data_campuses")
	}

	return rowsAff, nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o DataCampuseSlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	if len(dataCampuseBeforeDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doBeforeDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), dataCampusePrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM `data_campuses` WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, dataCampusePrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "dto: unable to delete all from dataCampuse slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "dto: failed to get rows affected by deleteall for data_campuses")
	}

	if len(dataCampuseAfterDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	return rowsAff, nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *DataCampuse) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindDataCampuse(ctx, exec, o.ID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *DataCampuseSlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := DataCampuseSlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), dataCampusePrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT `data_campuses`.* FROM `data_campuses` WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, dataCampusePrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "dto: unable to reload all in DataCampuseSlice")
	}

	*o = slice

	return nil
}

// DataCampuseExists checks if the DataCampuse row exists.
func DataCampuseExists(ctx context.Context, exec boil.ContextExecutor, iD int) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from `data_campuses` where `id`=? limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, iD)
	}
	row := exec.QueryRowContext(ctx, sql, iD)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "dto: unable to check if data_campuses exists")
	}

	return exists, nil
}

// Exists checks if the DataCampuse row exists.
func (o *DataCampuse) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	return DataCampuseExists(ctx, exec, o.ID)
}
