// Code generated by SQLBoiler 4.19.5 (https://github.com/aarondl/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dto

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/aarondl/sqlboiler/v4/boil"
	"github.com/aarondl/sqlboiler/v4/queries"
	"github.com/aarondl/sqlboiler/v4/queries/qm"
	"github.com/aarondl/sqlboiler/v4/queries/qmhelper"
	"github.com/aarondl/strmangle"
	"github.com/friendsofgo/errors"
)

// DataRoom is an object representing the database table.
type DataRoom struct {
	ID        int       `boil:"id" json:"id" toml:"id" yaml:"id"`
	Campus    string    `boil:"campus" json:"campus" toml:"campus" yaml:"campus"`
	RoomIndex int       `boil:"room_index" json:"room_index" toml:"room_index" yaml:"room_index"`
	Name      string    `boil:"name" json:"name" toml:"name" yaml:"name"`
	CreatedAt time.Time `boil:"created_at" json:"created_at" toml:"created_at" yaml:"created_at"`
	UpdatedAt time.Time `boil:"updated_at" json:"updated_at" toml:"updated_at" yaml:"updated_at"`

	R *dataRoomR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L dataRoomL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var DataRoomColumns = struct {
	ID        string
	Campus    string
	RoomIndex string
	Name      string
	CreatedAt string
	UpdatedAt string
}{
	ID:        "id",
	Campus:    "campus",
	RoomIndex: "room_index",
	Name:      "name",
	CreatedAt: "created_at",
	UpdatedAt: "updated_at",
}

var DataRoomTableColumns = struct {
	ID        string
	Campus    string
	RoomIndex string
	Name      string
	CreatedAt string
	UpdatedAt string
}{
	ID:        "data_rooms.id",
	Campus:    "data_rooms.campus",
	RoomIndex: "data_rooms.room_index",
	Name:      "data_rooms.name",
	CreatedAt: "data_rooms.created_at",
	UpdatedAt: "data_rooms.updated_at",
}

// Generated where

var DataRoomWhere = struct {
	ID        whereHelperint
	Campus    whereHelperstring
	RoomIndex whereHelperint
	Name      whereHelperstring
	CreatedAt whereHelpertime_Time
	UpdatedAt whereHelpertime_Time
}{
	ID:        whereHelperint{field: "`data_rooms`.`id`"},
	Campus:    whereHelperstring{field: "`data_rooms`.`campus`"},
	RoomIndex: whereHelperint{field: "`data_rooms`.`room_index`"},
	Name:      whereHelperstring{field: "`data_rooms`.`name`"},
	CreatedAt: whereHelpertime_Time{field: "`data_rooms`.`created_at`"},
	UpdatedAt: whereHelpertime_Time{field: "`data_rooms`.`updated_at`"},
}

// DataRoomRels is where relationship names are stored.
var DataRoomRels = struct {
	CampusDataCampuse string
}{
	CampusDataCampuse: "CampusDataCampuse",
}

// dataRoomR is where relationships are stored.
type dataRoomR struct {
	CampusDataCampuse *DataCampuse `boil:"CampusDataCampuse" json:"CampusDataCampuse" toml:"CampusDataCampuse" yaml:"CampusDataCampuse"`
}

// NewStruct creates a new relationship struct
func (*dataRoomR) NewStruct() *dataRoomR {
	return &dataRoomR{}
}

func (o *DataRoom) GetCampusDataCampuse() *DataCampuse {
	if o == nil {
		return nil
	}

	return o.R.GetCampusDataCampuse()
}

func (r *dataRoomR) GetCampusDataCampuse() *DataCampuse {
	if r == nil {
		return nil
	}

	return r.CampusDataCampuse
}

// dataRoomL is where Load methods for each relationship are stored.
type dataRoomL struct{}

var (
	dataRoomAllColumns            = []string{"id", "campus", "room_index", "name", "created_at", "updated_at"}
	dataRoomColumnsWithoutDefault = []string{"campus", "room_index", "name"}
	dataRoomColumnsWithDefault    = []string{"id", "created_at", "updated_at"}
	dataRoomPrimaryKeyColumns     = []string{"id"}
	dataRoomGeneratedColumns      = []string{}
)

type (
	// DataRoomSlice is an alias for a slice of pointers to DataRoom.
	// This should almost always be used instead of []DataRoom.
	DataRoomSlice []*DataRoom
	// DataRoomHook is the signature for custom DataRoom hook methods
	DataRoomHook func(context.Context, boil.ContextExecutor, *DataRoom) error

	dataRoomQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	dataRoomType                 = reflect.TypeOf(&DataRoom{})
	dataRoomMapping              = queries.MakeStructMapping(dataRoomType)
	dataRoomPrimaryKeyMapping, _ = queries.BindMapping(dataRoomType, dataRoomMapping, dataRoomPrimaryKeyColumns)
	dataRoomInsertCacheMut       sync.RWMutex
	dataRoomInsertCache          = make(map[string]insertCache)
	dataRoomUpdateCacheMut       sync.RWMutex
	dataRoomUpdateCache          = make(map[string]updateCache)
	dataRoomUpsertCacheMut       sync.RWMutex
	dataRoomUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

var dataRoomAfterSelectMu sync.Mutex
var dataRoomAfterSelectHooks []DataRoomHook

var dataRoomBeforeInsertMu sync.Mutex
var dataRoomBeforeInsertHooks []DataRoomHook
var dataRoomAfterInsertMu sync.Mutex
var dataRoomAfterInsertHooks []DataRoomHook

var dataRoomBeforeUpdateMu sync.Mutex
var dataRoomBeforeUpdateHooks []DataRoomHook
var dataRoomAfterUpdateMu sync.Mutex
var dataRoomAfterUpdateHooks []DataRoomHook

var dataRoomBeforeDeleteMu sync.Mutex
var dataRoomBeforeDeleteHooks []DataRoomHook
var dataRoomAfterDeleteMu sync.Mutex
var dataRoomAfterDeleteHooks []DataRoomHook

var dataRoomBeforeUpsertMu sync.Mutex
var dataRoomBeforeUpsertHooks []DataRoomHook
var dataRoomAfterUpsertMu sync.Mutex
var dataRoomAfterUpsertHooks []DataRoomHook

// doAfterSelectHooks executes all "after Select" hooks.
func (o *DataRoom) doAfterSelectHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range dataRoomAfterSelectHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *DataRoom) doBeforeInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range dataRoomBeforeInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *DataRoom) doAfterInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range dataRoomAfterInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpdateHooks executes all "before Update" hooks.
func (o *DataRoom) doBeforeUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range dataRoomBeforeUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpdateHooks executes all "after Update" hooks.
func (o *DataRoom) doAfterUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range dataRoomAfterUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeDeleteHooks executes all "before Delete" hooks.
func (o *DataRoom) doBeforeDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range dataRoomBeforeDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterDeleteHooks executes all "after Delete" hooks.
func (o *DataRoom) doAfterDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range dataRoomAfterDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *DataRoom) doBeforeUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range dataRoomBeforeUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *DataRoom) doAfterUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range dataRoomAfterUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddDataRoomHook registers your hook function for all future operations.
func AddDataRoomHook(hookPoint boil.HookPoint, dataRoomHook DataRoomHook) {
	switch hookPoint {
	case boil.AfterSelectHook:
		dataRoomAfterSelectMu.Lock()
		dataRoomAfterSelectHooks = append(dataRoomAfterSelectHooks, dataRoomHook)
		dataRoomAfterSelectMu.Unlock()
	case boil.BeforeInsertHook:
		dataRoomBeforeInsertMu.Lock()
		dataRoomBeforeInsertHooks = append(dataRoomBeforeInsertHooks, dataRoomHook)
		dataRoomBeforeInsertMu.Unlock()
	case boil.AfterInsertHook:
		dataRoomAfterInsertMu.Lock()
		dataRoomAfterInsertHooks = append(dataRoomAfterInsertHooks, dataRoomHook)
		dataRoomAfterInsertMu.Unlock()
	case boil.BeforeUpdateHook:
		dataRoomBeforeUpdateMu.Lock()
		dataRoomBeforeUpdateHooks = append(dataRoomBeforeUpdateHooks, dataRoomHook)
		dataRoomBeforeUpdateMu.Unlock()
	case boil.AfterUpdateHook:
		dataRoomAfterUpdateMu.Lock()
		dataRoomAfterUpdateHooks = append(dataRoomAfterUpdateHooks, dataRoomHook)
		dataRoomAfterUpdateMu.Unlock()
	case boil.BeforeDeleteHook:
		dataRoomBeforeDeleteMu.Lock()
		dataRoomBeforeDeleteHooks = append(dataRoomBeforeDeleteHooks, dataRoomHook)
		dataRoomBeforeDeleteMu.Unlock()
	case boil.AfterDeleteHook:
		dataRoomAfterDeleteMu.Lock()
		dataRoomAfterDeleteHooks = append(dataRoomAfterDeleteHooks, dataRoomHook)
		dataRoomAfterDeleteMu.Unlock()
	case boil.BeforeUpsertHook:
		dataRoomBeforeUpsertMu.Lock()
		dataRoomBeforeUpsertHooks = append(dataRoomBeforeUpsertHooks, dataRoomHook)
		dataRoomBeforeUpsertMu.Unlock()
	case boil.AfterUpsertHook:
		dataRoomAfterUpsertMu.Lock()
		dataRoomAfterUpsertHooks = append(dataRoomAfterUpsertHooks, dataRoomHook)
		dataRoomAfterUpsertMu.Unlock()
	}
}

// One returns a single dataRoom record from the query.
func (q dataRoomQuery) One(ctx context.Context, exec boil.ContextExecutor) (*DataRoom, error) {
	o := &DataRoom{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "dto: failed to execute a one query for data_rooms")
	}

	if err := o.doAfterSelectHooks(ctx, exec); err != nil {
		return o, err
	}

	return o, nil
}

// All returns all DataRoom records from the query.
func (q dataRoomQuery) All(ctx context.Context, exec boil.ContextExecutor) (DataRoomSlice, error) {
	var o []*DataRoom

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "dto: failed to assign all query results to DataRoom slice")
	}

	if len(dataRoomAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(ctx, exec); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// Count returns the count of all DataRoom records in the query.
func (q dataRoomQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "dto: failed to count data_rooms rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q dataRoomQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "dto: failed to check if data_rooms exists")
	}

	return count > 0, nil
}

// CampusDataCampuse pointed to by the foreign key.
func (o *DataRoom) CampusDataCampuse(mods ...qm.QueryMod) dataCampuseQuery {
	queryMods := []qm.QueryMod{
		qm.Where("`campus` = ?", o.Campus),
	}

	queryMods = append(queryMods, mods...)

	return DataCampuses(queryMods...)
}

// LoadCampusDataCampuse allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (dataRoomL) LoadCampusDataCampuse(ctx context.Context, e boil.ContextExecutor, singular bool, maybeDataRoom interface{}, mods queries.Applicator) error {
	var slice []*DataRoom
	var object *DataRoom

	if singular {
		var ok bool
		object, ok = maybeDataRoom.(*DataRoom)
		if !ok {
			object = new(DataRoom)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeDataRoom)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeDataRoom))
			}
		}
	} else {
		s, ok := maybeDataRoom.(*[]*DataRoom)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeDataRoom)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeDataRoom))
			}
		}
	}

	args := make(map[interface{}]struct{})
	if singular {
		if object.R == nil {
			object.R = &dataRoomR{}
		}
		args[object.Campus] = struct{}{}

	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &dataRoomR{}
			}

			args[obj.Campus] = struct{}{}

		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]interface{}, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`data_campuses`),
		qm.WhereIn(`data_campuses.campus in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load DataCampuse")
	}

	var resultSlice []*DataCampuse
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice DataCampuse")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for data_campuses")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for data_campuses")
	}

	if len(dataCampuseAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.CampusDataCampuse = foreign
		if foreign.R == nil {
			foreign.R = &dataCampuseR{}
		}
		foreign.R.CampusDataRooms = append(foreign.R.CampusDataRooms, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if local.Campus == foreign.Campus {
				local.R.CampusDataCampuse = foreign
				if foreign.R == nil {
					foreign.R = &dataCampuseR{}
				}
				foreign.R.CampusDataRooms = append(foreign.R.CampusDataRooms, local)
				break
			}
		}
	}

	return nil
}

// SetCampusDataCampuse of the dataRoom to the related item.
// Sets o.R.CampusDataCampuse to related.
// Adds o to related.R.CampusDataRooms.
func (o *DataRoom) SetCampusDataCampuse(ctx context.Context, exec boil.ContextExecutor, insert bool, related *DataCampuse) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE `data_rooms` SET %s WHERE %s",
		strmangle.SetParamNames("`", "`", 0, []string{"campus"}),
		strmangle.WhereClause("`", "`", 0, dataRoomPrimaryKeyColumns),
	)
	values := []interface{}{related.Campus, o.ID}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, updateQuery)
		fmt.Fprintln(writer, values)
	}
	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	o.Campus = related.Campus
	if o.R == nil {
		o.R = &dataRoomR{
			CampusDataCampuse: related,
		}
	} else {
		o.R.CampusDataCampuse = related
	}

	if related.R == nil {
		related.R = &dataCampuseR{
			CampusDataRooms: DataRoomSlice{o},
		}
	} else {
		related.R.CampusDataRooms = append(related.R.CampusDataRooms, o)
	}

	return nil
}

// DataRooms retrieves all the records using an executor.
func DataRooms(mods ...qm.QueryMod) dataRoomQuery {
	mods = append(mods, qm.From("`data_rooms`"))
	q := NewQuery(mods...)
	if len(queries.GetSelect(q)) == 0 {
		queries.SetSelect(q, []string{"`data_rooms`.*"})
	}

	return dataRoomQuery{q}
}

// FindDataRoom retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindDataRoom(ctx context.Context, exec boil.ContextExecutor, iD int, selectCols ...string) (*DataRoom, error) {
	dataRoomObj := &DataRoom{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from `data_rooms` where `id`=?", sel,
	)

	q := queries.Raw(query, iD)

	err := q.Bind(ctx, exec, dataRoomObj)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "dto: unable to select from data_rooms")
	}

	if err = dataRoomObj.doAfterSelectHooks(ctx, exec); err != nil {
		return dataRoomObj, err
	}

	return dataRoomObj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *DataRoom) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("dto: no data_rooms provided for insertion")
	}

	var err error

	if err := o.doBeforeInsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(dataRoomColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	dataRoomInsertCacheMut.RLock()
	cache, cached := dataRoomInsertCache[key]
	dataRoomInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			dataRoomAllColumns,
			dataRoomColumnsWithDefault,
			dataRoomColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(dataRoomType, dataRoomMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(dataRoomType, dataRoomMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO `data_rooms` (`%s`) %%sVALUES (%s)%%s", strings.Join(wl, "`,`"), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO `data_rooms` () VALUES ()%s%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			cache.retQuery = fmt.Sprintf("SELECT `%s` FROM `data_rooms` WHERE %s", strings.Join(returnColumns, "`,`"), strmangle.WhereClause("`", "`", 0, dataRoomPrimaryKeyColumns))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	result, err := exec.ExecContext(ctx, cache.query, vals...)

	if err != nil {
		return errors.Wrap(err, "dto: unable to insert into data_rooms")
	}

	var lastID int64
	var identifierCols []interface{}

	if len(cache.retMapping) == 0 {
		goto CacheNoHooks
	}

	lastID, err = result.LastInsertId()
	if err != nil {
		return ErrSyncFail
	}

	o.ID = int(lastID)
	if lastID != 0 && len(cache.retMapping) == 1 && cache.retMapping[0] == dataRoomMapping["id"] {
		goto CacheNoHooks
	}

	identifierCols = []interface{}{
		o.ID,
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.retQuery)
		fmt.Fprintln(writer, identifierCols...)
	}
	err = exec.QueryRowContext(ctx, cache.retQuery, identifierCols...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	if err != nil {
		return errors.Wrap(err, "dto: unable to populate default values for data_rooms")
	}

CacheNoHooks:
	if !cached {
		dataRoomInsertCacheMut.Lock()
		dataRoomInsertCache[key] = cache
		dataRoomInsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(ctx, exec)
}

// Update uses an executor to update the DataRoom.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *DataRoom) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	var err error
	if err = o.doBeforeUpdateHooks(ctx, exec); err != nil {
		return 0, err
	}
	key := makeCacheKey(columns, nil)
	dataRoomUpdateCacheMut.RLock()
	cache, cached := dataRoomUpdateCache[key]
	dataRoomUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			dataRoomAllColumns,
			dataRoomPrimaryKeyColumns,
		)
		if len(wl) == 0 {
			return 0, errors.New("dto: unable to update data_rooms, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE `data_rooms` SET %s WHERE %s",
			strmangle.SetParamNames("`", "`", 0, wl),
			strmangle.WhereClause("`", "`", 0, dataRoomPrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(dataRoomType, dataRoomMapping, append(wl, dataRoomPrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "dto: unable to update data_rooms row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "dto: failed to get rows affected by update for data_rooms")
	}

	if !cached {
		dataRoomUpdateCacheMut.Lock()
		dataRoomUpdateCache[key] = cache
		dataRoomUpdateCacheMut.Unlock()
	}

	return rowsAff, o.doAfterUpdateHooks(ctx, exec)
}

// UpdateAll updates all rows with the specified column values.
func (q dataRoomQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "dto: unable to update all for data_rooms")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "dto: unable to retrieve rows affected for data_rooms")
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o DataRoomSlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("dto: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), dataRoomPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE `data_rooms` SET %s WHERE %s",
		strmangle.SetParamNames("`", "`", 0, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, dataRoomPrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "dto: unable to update all in dataRoom slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "dto: unable to retrieve rows affected all in update all dataRoom")
	}
	return rowsAff, nil
}

var mySQLDataRoomUniqueColumns = []string{
	"id",
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *DataRoom) Upsert(ctx context.Context, exec boil.ContextExecutor, updateColumns, insertColumns boil.Columns) error {
	if o == nil {
		return errors.New("dto: no data_rooms provided for upsert")
	}

	if err := o.doBeforeUpsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(dataRoomColumnsWithDefault, o)
	nzUniques := queries.NonZeroDefaultSet(mySQLDataRoomUniqueColumns, o)

	if len(nzUniques) == 0 {
		return errors.New("cannot upsert with a table that cannot conflict on a unique column")
	}

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzUniques {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	dataRoomUpsertCacheMut.RLock()
	cache, cached := dataRoomUpsertCache[key]
	dataRoomUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, _ := insertColumns.InsertColumnSet(
			dataRoomAllColumns,
			dataRoomColumnsWithDefault,
			dataRoomColumnsWithoutDefault,
			nzDefaults,
		)

		update := updateColumns.UpdateColumnSet(
			dataRoomAllColumns,
			dataRoomPrimaryKeyColumns,
		)

		if !updateColumns.IsNone() && len(update) == 0 {
			return errors.New("dto: unable to upsert data_rooms, could not build update column list")
		}

		ret := strmangle.SetComplement(dataRoomAllColumns, strmangle.SetIntersect(insert, update))

		cache.query = buildUpsertQueryMySQL(dialect, "`data_rooms`", update, insert)
		cache.retQuery = fmt.Sprintf(
			"SELECT %s FROM `data_rooms` WHERE %s",
			strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, ret), ","),
			strmangle.WhereClause("`", "`", 0, nzUniques),
		)

		cache.valueMapping, err = queries.BindMapping(dataRoomType, dataRoomMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(dataRoomType, dataRoomMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	result, err := exec.ExecContext(ctx, cache.query, vals...)

	if err != nil {
		return errors.Wrap(err, "dto: unable to upsert for data_rooms")
	}

	var lastID int64
	var uniqueMap []uint64
	var nzUniqueCols []interface{}

	if len(cache.retMapping) == 0 {
		goto CacheNoHooks
	}

	lastID, err = result.LastInsertId()
	if err != nil {
		return ErrSyncFail
	}

	o.ID = int(lastID)
	if lastID != 0 && len(cache.retMapping) == 1 && cache.retMapping[0] == dataRoomMapping["id"] {
		goto CacheNoHooks
	}

	uniqueMap, err = queries.BindMapping(dataRoomType, dataRoomMapping, nzUniques)
	if err != nil {
		return errors.Wrap(err, "dto: unable to retrieve unique values for data_rooms")
	}
	nzUniqueCols = queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), uniqueMap)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.retQuery)
		fmt.Fprintln(writer, nzUniqueCols...)
	}
	err = exec.QueryRowContext(ctx, cache.retQuery, nzUniqueCols...).Scan(returns...)
	if err != nil {
		return errors.Wrap(err, "dto: unable to populate default values for data_rooms")
	}

CacheNoHooks:
	if !cached {
		dataRoomUpsertCacheMut.Lock()
		dataRoomUpsertCache[key] = cache
		dataRoomUpsertCacheMut.Unlock()
	}

	return o.doAfterUpsertHooks(ctx, exec)
}

// Delete deletes a single DataRoom record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *DataRoom) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("dto: no DataRoom provided for delete")
	}

	if err := o.doBeforeDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), dataRoomPrimaryKeyMapping)
	sql := "DELETE FROM `data_rooms` WHERE `id`=?"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "dto: unable to delete from data_rooms")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "dto: failed to get rows affected by delete for data_rooms")
	}

	if err := o.doAfterDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	return rowsAff, nil
}

// DeleteAll deletes all matching rows.
func (q dataRoomQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("dto: no dataRoomQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "dto: unable to delete all from data_rooms")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "dto: failed to get rows affected by deleteall for data_rooms")
	}

	return rowsAff, nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o DataRoomSlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	if len(dataRoomBeforeDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doBeforeDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), dataRoomPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM `data_rooms` WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, dataRoomPrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "dto: unable to delete all from dataRoom slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "dto: failed to get rows affected by deleteall for data_rooms")
	}

	if len(dataRoomAfterDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	return rowsAff, nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *DataRoom) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindDataRoom(ctx, exec, o.ID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *DataRoomSlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := DataRoomSlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), dataRoomPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT `data_rooms`.* FROM `data_rooms` WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, dataRoomPrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "dto: unable to reload all in DataRoomSlice")
	}

	*o = slice

	return nil
}

// DataRoomExists checks if the DataRoom row exists.
func DataRoomExists(ctx context.Context, exec boil.ContextExecutor, iD int) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from `data_rooms` where `id`=? limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, iD)
	}
	row := exec.QueryRowContext(ctx, sql, iD)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "dto: unable to check if data_rooms exists")
	}

	return exists, nil
}

// Exists checks if the DataRoom row exists.
func (o *DataRoom) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	return DataRoomExists(ctx, exec, o.ID)
}
