// Code generated by SQLBoiler 4.19.5 (https://github.com/aarondl/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dto

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/aarondl/sqlboiler/v4/boil"
	"github.com/aarondl/sqlboiler/v4/queries"
	"github.com/aarondl/sqlboiler/v4/queries/qm"
	"github.com/aarondl/sqlboiler/v4/queries/qmhelper"
	"github.com/aarondl/strmangle"
	"github.com/friendsofgo/errors"
)

// DataRole is an object representing the database table.
type DataRole struct {
	ID        int       `boil:"id" json:"id" toml:"id" yaml:"id"`
	RoleKey   string    `boil:"role_key" json:"role_key" toml:"role_key" yaml:"role_key"`
	RoleName  string    `boil:"role_name" json:"role_name" toml:"role_name" yaml:"role_name"`
	CreatedAt time.Time `boil:"created_at" json:"created_at" toml:"created_at" yaml:"created_at"`
	UpdatedAt time.Time `boil:"updated_at" json:"updated_at" toml:"updated_at" yaml:"updated_at"`

	R *dataRoleR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L dataRoleL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var DataRoleColumns = struct {
	ID        string
	RoleKey   string
	RoleName  string
	CreatedAt string
	UpdatedAt string
}{
	ID:        "id",
	RoleKey:   "role_key",
	RoleName:  "role_name",
	CreatedAt: "created_at",
	UpdatedAt: "updated_at",
}

var DataRoleTableColumns = struct {
	ID        string
	RoleKey   string
	RoleName  string
	CreatedAt string
	UpdatedAt string
}{
	ID:        "data_roles.id",
	RoleKey:   "data_roles.role_key",
	RoleName:  "data_roles.role_name",
	CreatedAt: "data_roles.created_at",
	UpdatedAt: "data_roles.updated_at",
}

// Generated where

var DataRoleWhere = struct {
	ID        whereHelperint
	RoleKey   whereHelperstring
	RoleName  whereHelperstring
	CreatedAt whereHelpertime_Time
	UpdatedAt whereHelpertime_Time
}{
	ID:        whereHelperint{field: "`data_roles`.`id`"},
	RoleKey:   whereHelperstring{field: "`data_roles`.`role_key`"},
	RoleName:  whereHelperstring{field: "`data_roles`.`role_name`"},
	CreatedAt: whereHelpertime_Time{field: "`data_roles`.`created_at`"},
	UpdatedAt: whereHelpertime_Time{field: "`data_roles`.`updated_at`"},
}

// DataRoleRels is where relationship names are stored.
var DataRoleRels = struct {
	RoleKeyTBLUsers string
}{
	RoleKeyTBLUsers: "RoleKeyTBLUsers",
}

// dataRoleR is where relationships are stored.
type dataRoleR struct {
	RoleKeyTBLUsers TBLUserSlice `boil:"RoleKeyTBLUsers" json:"RoleKeyTBLUsers" toml:"RoleKeyTBLUsers" yaml:"RoleKeyTBLUsers"`
}

// NewStruct creates a new relationship struct
func (*dataRoleR) NewStruct() *dataRoleR {
	return &dataRoleR{}
}

func (o *DataRole) GetRoleKeyTBLUsers() TBLUserSlice {
	if o == nil {
		return nil
	}

	return o.R.GetRoleKeyTBLUsers()
}

func (r *dataRoleR) GetRoleKeyTBLUsers() TBLUserSlice {
	if r == nil {
		return nil
	}

	return r.RoleKeyTBLUsers
}

// dataRoleL is where Load methods for each relationship are stored.
type dataRoleL struct{}

var (
	dataRoleAllColumns            = []string{"id", "role_key", "role_name", "created_at", "updated_at"}
	dataRoleColumnsWithoutDefault = []string{"role_key", "role_name"}
	dataRoleColumnsWithDefault    = []string{"id", "created_at", "updated_at"}
	dataRolePrimaryKeyColumns     = []string{"id"}
	dataRoleGeneratedColumns      = []string{}
)

type (
	// DataRoleSlice is an alias for a slice of pointers to DataRole.
	// This should almost always be used instead of []DataRole.
	DataRoleSlice []*DataRole
	// DataRoleHook is the signature for custom DataRole hook methods
	DataRoleHook func(context.Context, boil.ContextExecutor, *DataRole) error

	dataRoleQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	dataRoleType                 = reflect.TypeOf(&DataRole{})
	dataRoleMapping              = queries.MakeStructMapping(dataRoleType)
	dataRolePrimaryKeyMapping, _ = queries.BindMapping(dataRoleType, dataRoleMapping, dataRolePrimaryKeyColumns)
	dataRoleInsertCacheMut       sync.RWMutex
	dataRoleInsertCache          = make(map[string]insertCache)
	dataRoleUpdateCacheMut       sync.RWMutex
	dataRoleUpdateCache          = make(map[string]updateCache)
	dataRoleUpsertCacheMut       sync.RWMutex
	dataRoleUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

var dataRoleAfterSelectMu sync.Mutex
var dataRoleAfterSelectHooks []DataRoleHook

var dataRoleBeforeInsertMu sync.Mutex
var dataRoleBeforeInsertHooks []DataRoleHook
var dataRoleAfterInsertMu sync.Mutex
var dataRoleAfterInsertHooks []DataRoleHook

var dataRoleBeforeUpdateMu sync.Mutex
var dataRoleBeforeUpdateHooks []DataRoleHook
var dataRoleAfterUpdateMu sync.Mutex
var dataRoleAfterUpdateHooks []DataRoleHook

var dataRoleBeforeDeleteMu sync.Mutex
var dataRoleBeforeDeleteHooks []DataRoleHook
var dataRoleAfterDeleteMu sync.Mutex
var dataRoleAfterDeleteHooks []DataRoleHook

var dataRoleBeforeUpsertMu sync.Mutex
var dataRoleBeforeUpsertHooks []DataRoleHook
var dataRoleAfterUpsertMu sync.Mutex
var dataRoleAfterUpsertHooks []DataRoleHook

// doAfterSelectHooks executes all "after Select" hooks.
func (o *DataRole) doAfterSelectHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range dataRoleAfterSelectHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *DataRole) doBeforeInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range dataRoleBeforeInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *DataRole) doAfterInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range dataRoleAfterInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpdateHooks executes all "before Update" hooks.
func (o *DataRole) doBeforeUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range dataRoleBeforeUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpdateHooks executes all "after Update" hooks.
func (o *DataRole) doAfterUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range dataRoleAfterUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeDeleteHooks executes all "before Delete" hooks.
func (o *DataRole) doBeforeDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range dataRoleBeforeDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterDeleteHooks executes all "after Delete" hooks.
func (o *DataRole) doAfterDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range dataRoleAfterDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *DataRole) doBeforeUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range dataRoleBeforeUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *DataRole) doAfterUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range dataRoleAfterUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddDataRoleHook registers your hook function for all future operations.
func AddDataRoleHook(hookPoint boil.HookPoint, dataRoleHook DataRoleHook) {
	switch hookPoint {
	case boil.AfterSelectHook:
		dataRoleAfterSelectMu.Lock()
		dataRoleAfterSelectHooks = append(dataRoleAfterSelectHooks, dataRoleHook)
		dataRoleAfterSelectMu.Unlock()
	case boil.BeforeInsertHook:
		dataRoleBeforeInsertMu.Lock()
		dataRoleBeforeInsertHooks = append(dataRoleBeforeInsertHooks, dataRoleHook)
		dataRoleBeforeInsertMu.Unlock()
	case boil.AfterInsertHook:
		dataRoleAfterInsertMu.Lock()
		dataRoleAfterInsertHooks = append(dataRoleAfterInsertHooks, dataRoleHook)
		dataRoleAfterInsertMu.Unlock()
	case boil.BeforeUpdateHook:
		dataRoleBeforeUpdateMu.Lock()
		dataRoleBeforeUpdateHooks = append(dataRoleBeforeUpdateHooks, dataRoleHook)
		dataRoleBeforeUpdateMu.Unlock()
	case boil.AfterUpdateHook:
		dataRoleAfterUpdateMu.Lock()
		dataRoleAfterUpdateHooks = append(dataRoleAfterUpdateHooks, dataRoleHook)
		dataRoleAfterUpdateMu.Unlock()
	case boil.BeforeDeleteHook:
		dataRoleBeforeDeleteMu.Lock()
		dataRoleBeforeDeleteHooks = append(dataRoleBeforeDeleteHooks, dataRoleHook)
		dataRoleBeforeDeleteMu.Unlock()
	case boil.AfterDeleteHook:
		dataRoleAfterDeleteMu.Lock()
		dataRoleAfterDeleteHooks = append(dataRoleAfterDeleteHooks, dataRoleHook)
		dataRoleAfterDeleteMu.Unlock()
	case boil.BeforeUpsertHook:
		dataRoleBeforeUpsertMu.Lock()
		dataRoleBeforeUpsertHooks = append(dataRoleBeforeUpsertHooks, dataRoleHook)
		dataRoleBeforeUpsertMu.Unlock()
	case boil.AfterUpsertHook:
		dataRoleAfterUpsertMu.Lock()
		dataRoleAfterUpsertHooks = append(dataRoleAfterUpsertHooks, dataRoleHook)
		dataRoleAfterUpsertMu.Unlock()
	}
}

// One returns a single dataRole record from the query.
func (q dataRoleQuery) One(ctx context.Context, exec boil.ContextExecutor) (*DataRole, error) {
	o := &DataRole{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "dto: failed to execute a one query for data_roles")
	}

	if err := o.doAfterSelectHooks(ctx, exec); err != nil {
		return o, err
	}

	return o, nil
}

// All returns all DataRole records from the query.
func (q dataRoleQuery) All(ctx context.Context, exec boil.ContextExecutor) (DataRoleSlice, error) {
	var o []*DataRole

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "dto: failed to assign all query results to DataRole slice")
	}

	if len(dataRoleAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(ctx, exec); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// Count returns the count of all DataRole records in the query.
func (q dataRoleQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "dto: failed to count data_roles rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q dataRoleQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "dto: failed to check if data_roles exists")
	}

	return count > 0, nil
}

// RoleKeyTBLUsers retrieves all the tbl_user's TBLUsers with an executor via role_key column.
func (o *DataRole) RoleKeyTBLUsers(mods ...qm.QueryMod) tblUserQuery {
	var queryMods []qm.QueryMod
	if len(mods) != 0 {
		queryMods = append(queryMods, mods...)
	}

	queryMods = append(queryMods,
		qm.Where("`tbl_users`.`role_key`=?", o.RoleKey),
	)

	return TBLUsers(queryMods...)
}

// LoadRoleKeyTBLUsers allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for a 1-M or N-M relationship.
func (dataRoleL) LoadRoleKeyTBLUsers(ctx context.Context, e boil.ContextExecutor, singular bool, maybeDataRole interface{}, mods queries.Applicator) error {
	var slice []*DataRole
	var object *DataRole

	if singular {
		var ok bool
		object, ok = maybeDataRole.(*DataRole)
		if !ok {
			object = new(DataRole)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeDataRole)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeDataRole))
			}
		}
	} else {
		s, ok := maybeDataRole.(*[]*DataRole)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeDataRole)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeDataRole))
			}
		}
	}

	args := make(map[interface{}]struct{})
	if singular {
		if object.R == nil {
			object.R = &dataRoleR{}
		}
		args[object.RoleKey] = struct{}{}
	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &dataRoleR{}
			}
			args[obj.RoleKey] = struct{}{}
		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]interface{}, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`tbl_users`),
		qm.WhereIn(`tbl_users.role_key in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load tbl_users")
	}

	var resultSlice []*TBLUser
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice tbl_users")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results in eager load on tbl_users")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for tbl_users")
	}

	if len(tblUserAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}
	if singular {
		object.R.RoleKeyTBLUsers = resultSlice
		for _, foreign := range resultSlice {
			if foreign.R == nil {
				foreign.R = &tblUserR{}
			}
			foreign.R.RoleKeyDataRole = object
		}
		return nil
	}

	for _, foreign := range resultSlice {
		for _, local := range slice {
			if local.RoleKey == foreign.RoleKey {
				local.R.RoleKeyTBLUsers = append(local.R.RoleKeyTBLUsers, foreign)
				if foreign.R == nil {
					foreign.R = &tblUserR{}
				}
				foreign.R.RoleKeyDataRole = local
				break
			}
		}
	}

	return nil
}

// AddRoleKeyTBLUsers adds the given related objects to the existing relationships
// of the data_role, optionally inserting them as new records.
// Appends related to o.R.RoleKeyTBLUsers.
// Sets related.R.RoleKeyDataRole appropriately.
func (o *DataRole) AddRoleKeyTBLUsers(ctx context.Context, exec boil.ContextExecutor, insert bool, related ...*TBLUser) error {
	var err error
	for _, rel := range related {
		if insert {
			rel.RoleKey = o.RoleKey
			if err = rel.Insert(ctx, exec, boil.Infer()); err != nil {
				return errors.Wrap(err, "failed to insert into foreign table")
			}
		} else {
			updateQuery := fmt.Sprintf(
				"UPDATE `tbl_users` SET %s WHERE %s",
				strmangle.SetParamNames("`", "`", 0, []string{"role_key"}),
				strmangle.WhereClause("`", "`", 0, tblUserPrimaryKeyColumns),
			)
			values := []interface{}{o.RoleKey, rel.ID}

			if boil.IsDebug(ctx) {
				writer := boil.DebugWriterFrom(ctx)
				fmt.Fprintln(writer, updateQuery)
				fmt.Fprintln(writer, values)
			}
			if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
				return errors.Wrap(err, "failed to update foreign table")
			}

			rel.RoleKey = o.RoleKey
		}
	}

	if o.R == nil {
		o.R = &dataRoleR{
			RoleKeyTBLUsers: related,
		}
	} else {
		o.R.RoleKeyTBLUsers = append(o.R.RoleKeyTBLUsers, related...)
	}

	for _, rel := range related {
		if rel.R == nil {
			rel.R = &tblUserR{
				RoleKeyDataRole: o,
			}
		} else {
			rel.R.RoleKeyDataRole = o
		}
	}
	return nil
}

// DataRoles retrieves all the records using an executor.
func DataRoles(mods ...qm.QueryMod) dataRoleQuery {
	mods = append(mods, qm.From("`data_roles`"))
	q := NewQuery(mods...)
	if len(queries.GetSelect(q)) == 0 {
		queries.SetSelect(q, []string{"`data_roles`.*"})
	}

	return dataRoleQuery{q}
}

// FindDataRole retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindDataRole(ctx context.Context, exec boil.ContextExecutor, iD int, selectCols ...string) (*DataRole, error) {
	dataRoleObj := &DataRole{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from `data_roles` where `id`=?", sel,
	)

	q := queries.Raw(query, iD)

	err := q.Bind(ctx, exec, dataRoleObj)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "dto: unable to select from data_roles")
	}

	if err = dataRoleObj.doAfterSelectHooks(ctx, exec); err != nil {
		return dataRoleObj, err
	}

	return dataRoleObj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *DataRole) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("dto: no data_roles provided for insertion")
	}

	var err error

	if err := o.doBeforeInsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(dataRoleColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	dataRoleInsertCacheMut.RLock()
	cache, cached := dataRoleInsertCache[key]
	dataRoleInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			dataRoleAllColumns,
			dataRoleColumnsWithDefault,
			dataRoleColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(dataRoleType, dataRoleMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(dataRoleType, dataRoleMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO `data_roles` (`%s`) %%sVALUES (%s)%%s", strings.Join(wl, "`,`"), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO `data_roles` () VALUES ()%s%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			cache.retQuery = fmt.Sprintf("SELECT `%s` FROM `data_roles` WHERE %s", strings.Join(returnColumns, "`,`"), strmangle.WhereClause("`", "`", 0, dataRolePrimaryKeyColumns))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	result, err := exec.ExecContext(ctx, cache.query, vals...)

	if err != nil {
		return errors.Wrap(err, "dto: unable to insert into data_roles")
	}

	var lastID int64
	var identifierCols []interface{}

	if len(cache.retMapping) == 0 {
		goto CacheNoHooks
	}

	lastID, err = result.LastInsertId()
	if err != nil {
		return ErrSyncFail
	}

	o.ID = int(lastID)
	if lastID != 0 && len(cache.retMapping) == 1 && cache.retMapping[0] == dataRoleMapping["id"] {
		goto CacheNoHooks
	}

	identifierCols = []interface{}{
		o.ID,
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.retQuery)
		fmt.Fprintln(writer, identifierCols...)
	}
	err = exec.QueryRowContext(ctx, cache.retQuery, identifierCols...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	if err != nil {
		return errors.Wrap(err, "dto: unable to populate default values for data_roles")
	}

CacheNoHooks:
	if !cached {
		dataRoleInsertCacheMut.Lock()
		dataRoleInsertCache[key] = cache
		dataRoleInsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(ctx, exec)
}

// Update uses an executor to update the DataRole.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *DataRole) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	var err error
	if err = o.doBeforeUpdateHooks(ctx, exec); err != nil {
		return 0, err
	}
	key := makeCacheKey(columns, nil)
	dataRoleUpdateCacheMut.RLock()
	cache, cached := dataRoleUpdateCache[key]
	dataRoleUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			dataRoleAllColumns,
			dataRolePrimaryKeyColumns,
		)
		if len(wl) == 0 {
			return 0, errors.New("dto: unable to update data_roles, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE `data_roles` SET %s WHERE %s",
			strmangle.SetParamNames("`", "`", 0, wl),
			strmangle.WhereClause("`", "`", 0, dataRolePrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(dataRoleType, dataRoleMapping, append(wl, dataRolePrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "dto: unable to update data_roles row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "dto: failed to get rows affected by update for data_roles")
	}

	if !cached {
		dataRoleUpdateCacheMut.Lock()
		dataRoleUpdateCache[key] = cache
		dataRoleUpdateCacheMut.Unlock()
	}

	return rowsAff, o.doAfterUpdateHooks(ctx, exec)
}

// UpdateAll updates all rows with the specified column values.
func (q dataRoleQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "dto: unable to update all for data_roles")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "dto: unable to retrieve rows affected for data_roles")
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o DataRoleSlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("dto: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), dataRolePrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE `data_roles` SET %s WHERE %s",
		strmangle.SetParamNames("`", "`", 0, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, dataRolePrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "dto: unable to update all in dataRole slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "dto: unable to retrieve rows affected all in update all dataRole")
	}
	return rowsAff, nil
}

var mySQLDataRoleUniqueColumns = []string{
	"id",
	"role_key",
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *DataRole) Upsert(ctx context.Context, exec boil.ContextExecutor, updateColumns, insertColumns boil.Columns) error {
	if o == nil {
		return errors.New("dto: no data_roles provided for upsert")
	}

	if err := o.doBeforeUpsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(dataRoleColumnsWithDefault, o)
	nzUniques := queries.NonZeroDefaultSet(mySQLDataRoleUniqueColumns, o)

	if len(nzUniques) == 0 {
		return errors.New("cannot upsert with a table that cannot conflict on a unique column")
	}

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzUniques {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	dataRoleUpsertCacheMut.RLock()
	cache, cached := dataRoleUpsertCache[key]
	dataRoleUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, _ := insertColumns.InsertColumnSet(
			dataRoleAllColumns,
			dataRoleColumnsWithDefault,
			dataRoleColumnsWithoutDefault,
			nzDefaults,
		)

		update := updateColumns.UpdateColumnSet(
			dataRoleAllColumns,
			dataRolePrimaryKeyColumns,
		)

		if !updateColumns.IsNone() && len(update) == 0 {
			return errors.New("dto: unable to upsert data_roles, could not build update column list")
		}

		ret := strmangle.SetComplement(dataRoleAllColumns, strmangle.SetIntersect(insert, update))

		cache.query = buildUpsertQueryMySQL(dialect, "`data_roles`", update, insert)
		cache.retQuery = fmt.Sprintf(
			"SELECT %s FROM `data_roles` WHERE %s",
			strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, ret), ","),
			strmangle.WhereClause("`", "`", 0, nzUniques),
		)

		cache.valueMapping, err = queries.BindMapping(dataRoleType, dataRoleMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(dataRoleType, dataRoleMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	result, err := exec.ExecContext(ctx, cache.query, vals...)

	if err != nil {
		return errors.Wrap(err, "dto: unable to upsert for data_roles")
	}

	var lastID int64
	var uniqueMap []uint64
	var nzUniqueCols []interface{}

	if len(cache.retMapping) == 0 {
		goto CacheNoHooks
	}

	lastID, err = result.LastInsertId()
	if err != nil {
		return ErrSyncFail
	}

	o.ID = int(lastID)
	if lastID != 0 && len(cache.retMapping) == 1 && cache.retMapping[0] == dataRoleMapping["id"] {
		goto CacheNoHooks
	}

	uniqueMap, err = queries.BindMapping(dataRoleType, dataRoleMapping, nzUniques)
	if err != nil {
		return errors.Wrap(err, "dto: unable to retrieve unique values for data_roles")
	}
	nzUniqueCols = queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), uniqueMap)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.retQuery)
		fmt.Fprintln(writer, nzUniqueCols...)
	}
	err = exec.QueryRowContext(ctx, cache.retQuery, nzUniqueCols...).Scan(returns...)
	if err != nil {
		return errors.Wrap(err, "dto: unable to populate default values for data_roles")
	}

CacheNoHooks:
	if !cached {
		dataRoleUpsertCacheMut.Lock()
		dataRoleUpsertCache[key] = cache
		dataRoleUpsertCacheMut.Unlock()
	}

	return o.doAfterUpsertHooks(ctx, exec)
}

// Delete deletes a single DataRole record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *DataRole) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("dto: no DataRole provided for delete")
	}

	if err := o.doBeforeDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), dataRolePrimaryKeyMapping)
	sql := "DELETE FROM `data_roles` WHERE `id`=?"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "dto: unable to delete from data_roles")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "dto: failed to get rows affected by delete for data_roles")
	}

	if err := o.doAfterDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	return rowsAff, nil
}

// DeleteAll deletes all matching rows.
func (q dataRoleQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("dto: no dataRoleQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "dto: unable to delete all from data_roles")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "dto: failed to get rows affected by deleteall for data_roles")
	}

	return rowsAff, nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o DataRoleSlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	if len(dataRoleBeforeDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doBeforeDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), dataRolePrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM `data_roles` WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, dataRolePrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "dto: unable to delete all from dataRole slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "dto: failed to get rows affected by deleteall for data_roles")
	}

	if len(dataRoleAfterDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	return rowsAff, nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *DataRole) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindDataRole(ctx, exec, o.ID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *DataRoleSlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := DataRoleSlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), dataRolePrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT `data_roles`.* FROM `data_roles` WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, dataRolePrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "dto: unable to reload all in DataRoleSlice")
	}

	*o = slice

	return nil
}

// DataRoleExists checks if the DataRole row exists.
func DataRoleExists(ctx context.Context, exec boil.ContextExecutor, iD int) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from `data_roles` where `id`=? limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, iD)
	}
	row := exec.QueryRowContext(ctx, sql, iD)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "dto: unable to check if data_roles exists")
	}

	return exists, nil
}

// Exists checks if the DataRole row exists.
func (o *DataRole) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	return DataRoleExists(ctx, exec, o.ID)
}
