// Code generated by SQLBoiler 4.19.5 (https://github.com/aarondl/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dto

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/aarondl/sqlboiler/v4/boil"
	"github.com/aarondl/sqlboiler/v4/queries"
	"github.com/aarondl/sqlboiler/v4/queries/qm"
	"github.com/aarondl/sqlboiler/v4/queries/qmhelper"
	"github.com/aarondl/strmangle"
	"github.com/friendsofgo/errors"
)

// TBLSchedule is an object representing the database table.
type TBLSchedule struct {
	ID             int       `boil:"id" json:"id" toml:"id" yaml:"id"`
	Campus         string    `boil:"campus" json:"campus" toml:"campus" yaml:"campus"`
	Title          string    `boil:"title" json:"title" toml:"title" yaml:"title"`
	HistoryIndex   int       `boil:"history_index" json:"history_index" toml:"history_index" yaml:"history_index"`
	StartTime      int       `boil:"start_time" json:"start_time" toml:"start_time" yaml:"start_time"`
	EndTime        int       `boil:"end_time" json:"end_time" toml:"end_time" yaml:"end_time"`
	CreateUser     int       `boil:"create_user" json:"create_user" toml:"create_user" yaml:"create_user"`
	LastUpdateUser int       `boil:"last_update_user" json:"last_update_user" toml:"last_update_user" yaml:"last_update_user"`
	CreatedAt      time.Time `boil:"created_at" json:"created_at" toml:"created_at" yaml:"created_at"`
	UpdatedAt      time.Time `boil:"updated_at" json:"updated_at" toml:"updated_at" yaml:"updated_at"`

	R *tblScheduleR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L tblScheduleL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var TBLScheduleColumns = struct {
	ID             string
	Campus         string
	Title          string
	HistoryIndex   string
	StartTime      string
	EndTime        string
	CreateUser     string
	LastUpdateUser string
	CreatedAt      string
	UpdatedAt      string
}{
	ID:             "id",
	Campus:         "campus",
	Title:          "title",
	HistoryIndex:   "history_index",
	StartTime:      "start_time",
	EndTime:        "end_time",
	CreateUser:     "create_user",
	LastUpdateUser: "last_update_user",
	CreatedAt:      "created_at",
	UpdatedAt:      "updated_at",
}

var TBLScheduleTableColumns = struct {
	ID             string
	Campus         string
	Title          string
	HistoryIndex   string
	StartTime      string
	EndTime        string
	CreateUser     string
	LastUpdateUser string
	CreatedAt      string
	UpdatedAt      string
}{
	ID:             "tbl_schedules.id",
	Campus:         "tbl_schedules.campus",
	Title:          "tbl_schedules.title",
	HistoryIndex:   "tbl_schedules.history_index",
	StartTime:      "tbl_schedules.start_time",
	EndTime:        "tbl_schedules.end_time",
	CreateUser:     "tbl_schedules.create_user",
	LastUpdateUser: "tbl_schedules.last_update_user",
	CreatedAt:      "tbl_schedules.created_at",
	UpdatedAt:      "tbl_schedules.updated_at",
}

// Generated where

var TBLScheduleWhere = struct {
	ID             whereHelperint
	Campus         whereHelperstring
	Title          whereHelperstring
	HistoryIndex   whereHelperint
	StartTime      whereHelperint
	EndTime        whereHelperint
	CreateUser     whereHelperint
	LastUpdateUser whereHelperint
	CreatedAt      whereHelpertime_Time
	UpdatedAt      whereHelpertime_Time
}{
	ID:             whereHelperint{field: "`tbl_schedules`.`id`"},
	Campus:         whereHelperstring{field: "`tbl_schedules`.`campus`"},
	Title:          whereHelperstring{field: "`tbl_schedules`.`title`"},
	HistoryIndex:   whereHelperint{field: "`tbl_schedules`.`history_index`"},
	StartTime:      whereHelperint{field: "`tbl_schedules`.`start_time`"},
	EndTime:        whereHelperint{field: "`tbl_schedules`.`end_time`"},
	CreateUser:     whereHelperint{field: "`tbl_schedules`.`create_user`"},
	LastUpdateUser: whereHelperint{field: "`tbl_schedules`.`last_update_user`"},
	CreatedAt:      whereHelpertime_Time{field: "`tbl_schedules`.`created_at`"},
	UpdatedAt:      whereHelpertime_Time{field: "`tbl_schedules`.`updated_at`"},
}

// TBLScheduleRels is where relationship names are stored.
var TBLScheduleRels = struct {
	CampusDataCampuse            string
	CreateUserTBLUser            string
	LastUpdateUserTBLUser        string
	ScheduleTBLScheduleItems     string
	ScheduleTBLScheduleRoomItems string
}{
	CampusDataCampuse:            "CampusDataCampuse",
	CreateUserTBLUser:            "CreateUserTBLUser",
	LastUpdateUserTBLUser:        "LastUpdateUserTBLUser",
	ScheduleTBLScheduleItems:     "ScheduleTBLScheduleItems",
	ScheduleTBLScheduleRoomItems: "ScheduleTBLScheduleRoomItems",
}

// tblScheduleR is where relationships are stored.
type tblScheduleR struct {
	CampusDataCampuse            *DataCampuse             `boil:"CampusDataCampuse" json:"CampusDataCampuse" toml:"CampusDataCampuse" yaml:"CampusDataCampuse"`
	CreateUserTBLUser            *TBLUser                 `boil:"CreateUserTBLUser" json:"CreateUserTBLUser" toml:"CreateUserTBLUser" yaml:"CreateUserTBLUser"`
	LastUpdateUserTBLUser        *TBLUser                 `boil:"LastUpdateUserTBLUser" json:"LastUpdateUserTBLUser" toml:"LastUpdateUserTBLUser" yaml:"LastUpdateUserTBLUser"`
	ScheduleTBLScheduleItems     TBLScheduleItemSlice     `boil:"ScheduleTBLScheduleItems" json:"ScheduleTBLScheduleItems" toml:"ScheduleTBLScheduleItems" yaml:"ScheduleTBLScheduleItems"`
	ScheduleTBLScheduleRoomItems TBLScheduleRoomItemSlice `boil:"ScheduleTBLScheduleRoomItems" json:"ScheduleTBLScheduleRoomItems" toml:"ScheduleTBLScheduleRoomItems" yaml:"ScheduleTBLScheduleRoomItems"`
}

// NewStruct creates a new relationship struct
func (*tblScheduleR) NewStruct() *tblScheduleR {
	return &tblScheduleR{}
}

func (o *TBLSchedule) GetCampusDataCampuse() *DataCampuse {
	if o == nil {
		return nil
	}

	return o.R.GetCampusDataCampuse()
}

func (r *tblScheduleR) GetCampusDataCampuse() *DataCampuse {
	if r == nil {
		return nil
	}

	return r.CampusDataCampuse
}

func (o *TBLSchedule) GetCreateUserTBLUser() *TBLUser {
	if o == nil {
		return nil
	}

	return o.R.GetCreateUserTBLUser()
}

func (r *tblScheduleR) GetCreateUserTBLUser() *TBLUser {
	if r == nil {
		return nil
	}

	return r.CreateUserTBLUser
}

func (o *TBLSchedule) GetLastUpdateUserTBLUser() *TBLUser {
	if o == nil {
		return nil
	}

	return o.R.GetLastUpdateUserTBLUser()
}

func (r *tblScheduleR) GetLastUpdateUserTBLUser() *TBLUser {
	if r == nil {
		return nil
	}

	return r.LastUpdateUserTBLUser
}

func (o *TBLSchedule) GetScheduleTBLScheduleItems() TBLScheduleItemSlice {
	if o == nil {
		return nil
	}

	return o.R.GetScheduleTBLScheduleItems()
}

func (r *tblScheduleR) GetScheduleTBLScheduleItems() TBLScheduleItemSlice {
	if r == nil {
		return nil
	}

	return r.ScheduleTBLScheduleItems
}

func (o *TBLSchedule) GetScheduleTBLScheduleRoomItems() TBLScheduleRoomItemSlice {
	if o == nil {
		return nil
	}

	return o.R.GetScheduleTBLScheduleRoomItems()
}

func (r *tblScheduleR) GetScheduleTBLScheduleRoomItems() TBLScheduleRoomItemSlice {
	if r == nil {
		return nil
	}

	return r.ScheduleTBLScheduleRoomItems
}

// tblScheduleL is where Load methods for each relationship are stored.
type tblScheduleL struct{}

var (
	tblScheduleAllColumns            = []string{"id", "campus", "title", "history_index", "start_time", "end_time", "create_user", "last_update_user", "created_at", "updated_at"}
	tblScheduleColumnsWithoutDefault = []string{"campus", "title", "history_index", "start_time", "end_time", "create_user", "last_update_user"}
	tblScheduleColumnsWithDefault    = []string{"id", "created_at", "updated_at"}
	tblSchedulePrimaryKeyColumns     = []string{"id"}
	tblScheduleGeneratedColumns      = []string{}
)

type (
	// TBLScheduleSlice is an alias for a slice of pointers to TBLSchedule.
	// This should almost always be used instead of []TBLSchedule.
	TBLScheduleSlice []*TBLSchedule
	// TBLScheduleHook is the signature for custom TBLSchedule hook methods
	TBLScheduleHook func(context.Context, boil.ContextExecutor, *TBLSchedule) error

	tblScheduleQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	tblScheduleType                 = reflect.TypeOf(&TBLSchedule{})
	tblScheduleMapping              = queries.MakeStructMapping(tblScheduleType)
	tblSchedulePrimaryKeyMapping, _ = queries.BindMapping(tblScheduleType, tblScheduleMapping, tblSchedulePrimaryKeyColumns)
	tblScheduleInsertCacheMut       sync.RWMutex
	tblScheduleInsertCache          = make(map[string]insertCache)
	tblScheduleUpdateCacheMut       sync.RWMutex
	tblScheduleUpdateCache          = make(map[string]updateCache)
	tblScheduleUpsertCacheMut       sync.RWMutex
	tblScheduleUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

var tblScheduleAfterSelectMu sync.Mutex
var tblScheduleAfterSelectHooks []TBLScheduleHook

var tblScheduleBeforeInsertMu sync.Mutex
var tblScheduleBeforeInsertHooks []TBLScheduleHook
var tblScheduleAfterInsertMu sync.Mutex
var tblScheduleAfterInsertHooks []TBLScheduleHook

var tblScheduleBeforeUpdateMu sync.Mutex
var tblScheduleBeforeUpdateHooks []TBLScheduleHook
var tblScheduleAfterUpdateMu sync.Mutex
var tblScheduleAfterUpdateHooks []TBLScheduleHook

var tblScheduleBeforeDeleteMu sync.Mutex
var tblScheduleBeforeDeleteHooks []TBLScheduleHook
var tblScheduleAfterDeleteMu sync.Mutex
var tblScheduleAfterDeleteHooks []TBLScheduleHook

var tblScheduleBeforeUpsertMu sync.Mutex
var tblScheduleBeforeUpsertHooks []TBLScheduleHook
var tblScheduleAfterUpsertMu sync.Mutex
var tblScheduleAfterUpsertHooks []TBLScheduleHook

// doAfterSelectHooks executes all "after Select" hooks.
func (o *TBLSchedule) doAfterSelectHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range tblScheduleAfterSelectHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *TBLSchedule) doBeforeInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range tblScheduleBeforeInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *TBLSchedule) doAfterInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range tblScheduleAfterInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpdateHooks executes all "before Update" hooks.
func (o *TBLSchedule) doBeforeUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range tblScheduleBeforeUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpdateHooks executes all "after Update" hooks.
func (o *TBLSchedule) doAfterUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range tblScheduleAfterUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeDeleteHooks executes all "before Delete" hooks.
func (o *TBLSchedule) doBeforeDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range tblScheduleBeforeDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterDeleteHooks executes all "after Delete" hooks.
func (o *TBLSchedule) doAfterDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range tblScheduleAfterDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *TBLSchedule) doBeforeUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range tblScheduleBeforeUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *TBLSchedule) doAfterUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range tblScheduleAfterUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddTBLScheduleHook registers your hook function for all future operations.
func AddTBLScheduleHook(hookPoint boil.HookPoint, tblScheduleHook TBLScheduleHook) {
	switch hookPoint {
	case boil.AfterSelectHook:
		tblScheduleAfterSelectMu.Lock()
		tblScheduleAfterSelectHooks = append(tblScheduleAfterSelectHooks, tblScheduleHook)
		tblScheduleAfterSelectMu.Unlock()
	case boil.BeforeInsertHook:
		tblScheduleBeforeInsertMu.Lock()
		tblScheduleBeforeInsertHooks = append(tblScheduleBeforeInsertHooks, tblScheduleHook)
		tblScheduleBeforeInsertMu.Unlock()
	case boil.AfterInsertHook:
		tblScheduleAfterInsertMu.Lock()
		tblScheduleAfterInsertHooks = append(tblScheduleAfterInsertHooks, tblScheduleHook)
		tblScheduleAfterInsertMu.Unlock()
	case boil.BeforeUpdateHook:
		tblScheduleBeforeUpdateMu.Lock()
		tblScheduleBeforeUpdateHooks = append(tblScheduleBeforeUpdateHooks, tblScheduleHook)
		tblScheduleBeforeUpdateMu.Unlock()
	case boil.AfterUpdateHook:
		tblScheduleAfterUpdateMu.Lock()
		tblScheduleAfterUpdateHooks = append(tblScheduleAfterUpdateHooks, tblScheduleHook)
		tblScheduleAfterUpdateMu.Unlock()
	case boil.BeforeDeleteHook:
		tblScheduleBeforeDeleteMu.Lock()
		tblScheduleBeforeDeleteHooks = append(tblScheduleBeforeDeleteHooks, tblScheduleHook)
		tblScheduleBeforeDeleteMu.Unlock()
	case boil.AfterDeleteHook:
		tblScheduleAfterDeleteMu.Lock()
		tblScheduleAfterDeleteHooks = append(tblScheduleAfterDeleteHooks, tblScheduleHook)
		tblScheduleAfterDeleteMu.Unlock()
	case boil.BeforeUpsertHook:
		tblScheduleBeforeUpsertMu.Lock()
		tblScheduleBeforeUpsertHooks = append(tblScheduleBeforeUpsertHooks, tblScheduleHook)
		tblScheduleBeforeUpsertMu.Unlock()
	case boil.AfterUpsertHook:
		tblScheduleAfterUpsertMu.Lock()
		tblScheduleAfterUpsertHooks = append(tblScheduleAfterUpsertHooks, tblScheduleHook)
		tblScheduleAfterUpsertMu.Unlock()
	}
}

// One returns a single tblSchedule record from the query.
func (q tblScheduleQuery) One(ctx context.Context, exec boil.ContextExecutor) (*TBLSchedule, error) {
	o := &TBLSchedule{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "dto: failed to execute a one query for tbl_schedules")
	}

	if err := o.doAfterSelectHooks(ctx, exec); err != nil {
		return o, err
	}

	return o, nil
}

// All returns all TBLSchedule records from the query.
func (q tblScheduleQuery) All(ctx context.Context, exec boil.ContextExecutor) (TBLScheduleSlice, error) {
	var o []*TBLSchedule

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "dto: failed to assign all query results to TBLSchedule slice")
	}

	if len(tblScheduleAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(ctx, exec); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// Count returns the count of all TBLSchedule records in the query.
func (q tblScheduleQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "dto: failed to count tbl_schedules rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q tblScheduleQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "dto: failed to check if tbl_schedules exists")
	}

	return count > 0, nil
}

// CampusDataCampuse pointed to by the foreign key.
func (o *TBLSchedule) CampusDataCampuse(mods ...qm.QueryMod) dataCampuseQuery {
	queryMods := []qm.QueryMod{
		qm.Where("`campus` = ?", o.Campus),
	}

	queryMods = append(queryMods, mods...)

	return DataCampuses(queryMods...)
}

// CreateUserTBLUser pointed to by the foreign key.
func (o *TBLSchedule) CreateUserTBLUser(mods ...qm.QueryMod) tblUserQuery {
	queryMods := []qm.QueryMod{
		qm.Where("`id` = ?", o.CreateUser),
	}

	queryMods = append(queryMods, mods...)

	return TBLUsers(queryMods...)
}

// LastUpdateUserTBLUser pointed to by the foreign key.
func (o *TBLSchedule) LastUpdateUserTBLUser(mods ...qm.QueryMod) tblUserQuery {
	queryMods := []qm.QueryMod{
		qm.Where("`id` = ?", o.LastUpdateUser),
	}

	queryMods = append(queryMods, mods...)

	return TBLUsers(queryMods...)
}

// ScheduleTBLScheduleItems retrieves all the tbl_schedule_item's TBLScheduleItems with an executor via schedule_id column.
func (o *TBLSchedule) ScheduleTBLScheduleItems(mods ...qm.QueryMod) tblScheduleItemQuery {
	var queryMods []qm.QueryMod
	if len(mods) != 0 {
		queryMods = append(queryMods, mods...)
	}

	queryMods = append(queryMods,
		qm.Where("`tbl_schedule_items`.`schedule_id`=?", o.ID),
	)

	return TBLScheduleItems(queryMods...)
}

// ScheduleTBLScheduleRoomItems retrieves all the tbl_schedule_room_item's TBLScheduleRoomItems with an executor via schedule_id column.
func (o *TBLSchedule) ScheduleTBLScheduleRoomItems(mods ...qm.QueryMod) tblScheduleRoomItemQuery {
	var queryMods []qm.QueryMod
	if len(mods) != 0 {
		queryMods = append(queryMods, mods...)
	}

	queryMods = append(queryMods,
		qm.Where("`tbl_schedule_room_items`.`schedule_id`=?", o.ID),
	)

	return TBLScheduleRoomItems(queryMods...)
}

// LoadCampusDataCampuse allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (tblScheduleL) LoadCampusDataCampuse(ctx context.Context, e boil.ContextExecutor, singular bool, maybeTBLSchedule interface{}, mods queries.Applicator) error {
	var slice []*TBLSchedule
	var object *TBLSchedule

	if singular {
		var ok bool
		object, ok = maybeTBLSchedule.(*TBLSchedule)
		if !ok {
			object = new(TBLSchedule)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeTBLSchedule)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeTBLSchedule))
			}
		}
	} else {
		s, ok := maybeTBLSchedule.(*[]*TBLSchedule)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeTBLSchedule)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeTBLSchedule))
			}
		}
	}

	args := make(map[interface{}]struct{})
	if singular {
		if object.R == nil {
			object.R = &tblScheduleR{}
		}
		args[object.Campus] = struct{}{}

	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &tblScheduleR{}
			}

			args[obj.Campus] = struct{}{}

		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]interface{}, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`data_campuses`),
		qm.WhereIn(`data_campuses.campus in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load DataCampuse")
	}

	var resultSlice []*DataCampuse
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice DataCampuse")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for data_campuses")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for data_campuses")
	}

	if len(dataCampuseAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.CampusDataCampuse = foreign
		if foreign.R == nil {
			foreign.R = &dataCampuseR{}
		}
		foreign.R.CampusTBLSchedules = append(foreign.R.CampusTBLSchedules, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if local.Campus == foreign.Campus {
				local.R.CampusDataCampuse = foreign
				if foreign.R == nil {
					foreign.R = &dataCampuseR{}
				}
				foreign.R.CampusTBLSchedules = append(foreign.R.CampusTBLSchedules, local)
				break
			}
		}
	}

	return nil
}

// LoadCreateUserTBLUser allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (tblScheduleL) LoadCreateUserTBLUser(ctx context.Context, e boil.ContextExecutor, singular bool, maybeTBLSchedule interface{}, mods queries.Applicator) error {
	var slice []*TBLSchedule
	var object *TBLSchedule

	if singular {
		var ok bool
		object, ok = maybeTBLSchedule.(*TBLSchedule)
		if !ok {
			object = new(TBLSchedule)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeTBLSchedule)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeTBLSchedule))
			}
		}
	} else {
		s, ok := maybeTBLSchedule.(*[]*TBLSchedule)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeTBLSchedule)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeTBLSchedule))
			}
		}
	}

	args := make(map[interface{}]struct{})
	if singular {
		if object.R == nil {
			object.R = &tblScheduleR{}
		}
		args[object.CreateUser] = struct{}{}

	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &tblScheduleR{}
			}

			args[obj.CreateUser] = struct{}{}

		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]interface{}, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`tbl_users`),
		qm.WhereIn(`tbl_users.id in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load TBLUser")
	}

	var resultSlice []*TBLUser
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice TBLUser")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for tbl_users")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for tbl_users")
	}

	if len(tblUserAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.CreateUserTBLUser = foreign
		if foreign.R == nil {
			foreign.R = &tblUserR{}
		}
		foreign.R.CreateUserTBLSchedules = append(foreign.R.CreateUserTBLSchedules, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if local.CreateUser == foreign.ID {
				local.R.CreateUserTBLUser = foreign
				if foreign.R == nil {
					foreign.R = &tblUserR{}
				}
				foreign.R.CreateUserTBLSchedules = append(foreign.R.CreateUserTBLSchedules, local)
				break
			}
		}
	}

	return nil
}

// LoadLastUpdateUserTBLUser allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (tblScheduleL) LoadLastUpdateUserTBLUser(ctx context.Context, e boil.ContextExecutor, singular bool, maybeTBLSchedule interface{}, mods queries.Applicator) error {
	var slice []*TBLSchedule
	var object *TBLSchedule

	if singular {
		var ok bool
		object, ok = maybeTBLSchedule.(*TBLSchedule)
		if !ok {
			object = new(TBLSchedule)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeTBLSchedule)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeTBLSchedule))
			}
		}
	} else {
		s, ok := maybeTBLSchedule.(*[]*TBLSchedule)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeTBLSchedule)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeTBLSchedule))
			}
		}
	}

	args := make(map[interface{}]struct{})
	if singular {
		if object.R == nil {
			object.R = &tblScheduleR{}
		}
		args[object.LastUpdateUser] = struct{}{}

	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &tblScheduleR{}
			}

			args[obj.LastUpdateUser] = struct{}{}

		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]interface{}, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`tbl_users`),
		qm.WhereIn(`tbl_users.id in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load TBLUser")
	}

	var resultSlice []*TBLUser
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice TBLUser")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for tbl_users")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for tbl_users")
	}

	if len(tblUserAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.LastUpdateUserTBLUser = foreign
		if foreign.R == nil {
			foreign.R = &tblUserR{}
		}
		foreign.R.LastUpdateUserTBLSchedules = append(foreign.R.LastUpdateUserTBLSchedules, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if local.LastUpdateUser == foreign.ID {
				local.R.LastUpdateUserTBLUser = foreign
				if foreign.R == nil {
					foreign.R = &tblUserR{}
				}
				foreign.R.LastUpdateUserTBLSchedules = append(foreign.R.LastUpdateUserTBLSchedules, local)
				break
			}
		}
	}

	return nil
}

// LoadScheduleTBLScheduleItems allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for a 1-M or N-M relationship.
func (tblScheduleL) LoadScheduleTBLScheduleItems(ctx context.Context, e boil.ContextExecutor, singular bool, maybeTBLSchedule interface{}, mods queries.Applicator) error {
	var slice []*TBLSchedule
	var object *TBLSchedule

	if singular {
		var ok bool
		object, ok = maybeTBLSchedule.(*TBLSchedule)
		if !ok {
			object = new(TBLSchedule)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeTBLSchedule)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeTBLSchedule))
			}
		}
	} else {
		s, ok := maybeTBLSchedule.(*[]*TBLSchedule)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeTBLSchedule)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeTBLSchedule))
			}
		}
	}

	args := make(map[interface{}]struct{})
	if singular {
		if object.R == nil {
			object.R = &tblScheduleR{}
		}
		args[object.ID] = struct{}{}
	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &tblScheduleR{}
			}
			args[obj.ID] = struct{}{}
		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]interface{}, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`tbl_schedule_items`),
		qm.WhereIn(`tbl_schedule_items.schedule_id in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load tbl_schedule_items")
	}

	var resultSlice []*TBLScheduleItem
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice tbl_schedule_items")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results in eager load on tbl_schedule_items")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for tbl_schedule_items")
	}

	if len(tblScheduleItemAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}
	if singular {
		object.R.ScheduleTBLScheduleItems = resultSlice
		for _, foreign := range resultSlice {
			if foreign.R == nil {
				foreign.R = &tblScheduleItemR{}
			}
			foreign.R.Schedule = object
		}
		return nil
	}

	for _, foreign := range resultSlice {
		for _, local := range slice {
			if local.ID == foreign.ScheduleID {
				local.R.ScheduleTBLScheduleItems = append(local.R.ScheduleTBLScheduleItems, foreign)
				if foreign.R == nil {
					foreign.R = &tblScheduleItemR{}
				}
				foreign.R.Schedule = local
				break
			}
		}
	}

	return nil
}

// LoadScheduleTBLScheduleRoomItems allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for a 1-M or N-M relationship.
func (tblScheduleL) LoadScheduleTBLScheduleRoomItems(ctx context.Context, e boil.ContextExecutor, singular bool, maybeTBLSchedule interface{}, mods queries.Applicator) error {
	var slice []*TBLSchedule
	var object *TBLSchedule

	if singular {
		var ok bool
		object, ok = maybeTBLSchedule.(*TBLSchedule)
		if !ok {
			object = new(TBLSchedule)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeTBLSchedule)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeTBLSchedule))
			}
		}
	} else {
		s, ok := maybeTBLSchedule.(*[]*TBLSchedule)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeTBLSchedule)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeTBLSchedule))
			}
		}
	}

	args := make(map[interface{}]struct{})
	if singular {
		if object.R == nil {
			object.R = &tblScheduleR{}
		}
		args[object.ID] = struct{}{}
	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &tblScheduleR{}
			}
			args[obj.ID] = struct{}{}
		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]interface{}, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`tbl_schedule_room_items`),
		qm.WhereIn(`tbl_schedule_room_items.schedule_id in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load tbl_schedule_room_items")
	}

	var resultSlice []*TBLScheduleRoomItem
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice tbl_schedule_room_items")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results in eager load on tbl_schedule_room_items")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for tbl_schedule_room_items")
	}

	if len(tblScheduleRoomItemAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}
	if singular {
		object.R.ScheduleTBLScheduleRoomItems = resultSlice
		for _, foreign := range resultSlice {
			if foreign.R == nil {
				foreign.R = &tblScheduleRoomItemR{}
			}
			foreign.R.Schedule = object
		}
		return nil
	}

	for _, foreign := range resultSlice {
		for _, local := range slice {
			if local.ID == foreign.ScheduleID {
				local.R.ScheduleTBLScheduleRoomItems = append(local.R.ScheduleTBLScheduleRoomItems, foreign)
				if foreign.R == nil {
					foreign.R = &tblScheduleRoomItemR{}
				}
				foreign.R.Schedule = local
				break
			}
		}
	}

	return nil
}

// SetCampusDataCampuse of the tblSchedule to the related item.
// Sets o.R.CampusDataCampuse to related.
// Adds o to related.R.CampusTBLSchedules.
func (o *TBLSchedule) SetCampusDataCampuse(ctx context.Context, exec boil.ContextExecutor, insert bool, related *DataCampuse) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE `tbl_schedules` SET %s WHERE %s",
		strmangle.SetParamNames("`", "`", 0, []string{"campus"}),
		strmangle.WhereClause("`", "`", 0, tblSchedulePrimaryKeyColumns),
	)
	values := []interface{}{related.Campus, o.ID}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, updateQuery)
		fmt.Fprintln(writer, values)
	}
	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	o.Campus = related.Campus
	if o.R == nil {
		o.R = &tblScheduleR{
			CampusDataCampuse: related,
		}
	} else {
		o.R.CampusDataCampuse = related
	}

	if related.R == nil {
		related.R = &dataCampuseR{
			CampusTBLSchedules: TBLScheduleSlice{o},
		}
	} else {
		related.R.CampusTBLSchedules = append(related.R.CampusTBLSchedules, o)
	}

	return nil
}

// SetCreateUserTBLUser of the tblSchedule to the related item.
// Sets o.R.CreateUserTBLUser to related.
// Adds o to related.R.CreateUserTBLSchedules.
func (o *TBLSchedule) SetCreateUserTBLUser(ctx context.Context, exec boil.ContextExecutor, insert bool, related *TBLUser) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE `tbl_schedules` SET %s WHERE %s",
		strmangle.SetParamNames("`", "`", 0, []string{"create_user"}),
		strmangle.WhereClause("`", "`", 0, tblSchedulePrimaryKeyColumns),
	)
	values := []interface{}{related.ID, o.ID}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, updateQuery)
		fmt.Fprintln(writer, values)
	}
	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	o.CreateUser = related.ID
	if o.R == nil {
		o.R = &tblScheduleR{
			CreateUserTBLUser: related,
		}
	} else {
		o.R.CreateUserTBLUser = related
	}

	if related.R == nil {
		related.R = &tblUserR{
			CreateUserTBLSchedules: TBLScheduleSlice{o},
		}
	} else {
		related.R.CreateUserTBLSchedules = append(related.R.CreateUserTBLSchedules, o)
	}

	return nil
}

// SetLastUpdateUserTBLUser of the tblSchedule to the related item.
// Sets o.R.LastUpdateUserTBLUser to related.
// Adds o to related.R.LastUpdateUserTBLSchedules.
func (o *TBLSchedule) SetLastUpdateUserTBLUser(ctx context.Context, exec boil.ContextExecutor, insert bool, related *TBLUser) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE `tbl_schedules` SET %s WHERE %s",
		strmangle.SetParamNames("`", "`", 0, []string{"last_update_user"}),
		strmangle.WhereClause("`", "`", 0, tblSchedulePrimaryKeyColumns),
	)
	values := []interface{}{related.ID, o.ID}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, updateQuery)
		fmt.Fprintln(writer, values)
	}
	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	o.LastUpdateUser = related.ID
	if o.R == nil {
		o.R = &tblScheduleR{
			LastUpdateUserTBLUser: related,
		}
	} else {
		o.R.LastUpdateUserTBLUser = related
	}

	if related.R == nil {
		related.R = &tblUserR{
			LastUpdateUserTBLSchedules: TBLScheduleSlice{o},
		}
	} else {
		related.R.LastUpdateUserTBLSchedules = append(related.R.LastUpdateUserTBLSchedules, o)
	}

	return nil
}

// AddScheduleTBLScheduleItems adds the given related objects to the existing relationships
// of the tbl_schedule, optionally inserting them as new records.
// Appends related to o.R.ScheduleTBLScheduleItems.
// Sets related.R.Schedule appropriately.
func (o *TBLSchedule) AddScheduleTBLScheduleItems(ctx context.Context, exec boil.ContextExecutor, insert bool, related ...*TBLScheduleItem) error {
	var err error
	for _, rel := range related {
		if insert {
			rel.ScheduleID = o.ID
			if err = rel.Insert(ctx, exec, boil.Infer()); err != nil {
				return errors.Wrap(err, "failed to insert into foreign table")
			}
		} else {
			updateQuery := fmt.Sprintf(
				"UPDATE `tbl_schedule_items` SET %s WHERE %s",
				strmangle.SetParamNames("`", "`", 0, []string{"schedule_id"}),
				strmangle.WhereClause("`", "`", 0, tblScheduleItemPrimaryKeyColumns),
			)
			values := []interface{}{o.ID, rel.ID}

			if boil.IsDebug(ctx) {
				writer := boil.DebugWriterFrom(ctx)
				fmt.Fprintln(writer, updateQuery)
				fmt.Fprintln(writer, values)
			}
			if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
				return errors.Wrap(err, "failed to update foreign table")
			}

			rel.ScheduleID = o.ID
		}
	}

	if o.R == nil {
		o.R = &tblScheduleR{
			ScheduleTBLScheduleItems: related,
		}
	} else {
		o.R.ScheduleTBLScheduleItems = append(o.R.ScheduleTBLScheduleItems, related...)
	}

	for _, rel := range related {
		if rel.R == nil {
			rel.R = &tblScheduleItemR{
				Schedule: o,
			}
		} else {
			rel.R.Schedule = o
		}
	}
	return nil
}

// AddScheduleTBLScheduleRoomItems adds the given related objects to the existing relationships
// of the tbl_schedule, optionally inserting them as new records.
// Appends related to o.R.ScheduleTBLScheduleRoomItems.
// Sets related.R.Schedule appropriately.
func (o *TBLSchedule) AddScheduleTBLScheduleRoomItems(ctx context.Context, exec boil.ContextExecutor, insert bool, related ...*TBLScheduleRoomItem) error {
	var err error
	for _, rel := range related {
		if insert {
			rel.ScheduleID = o.ID
			if err = rel.Insert(ctx, exec, boil.Infer()); err != nil {
				return errors.Wrap(err, "failed to insert into foreign table")
			}
		} else {
			updateQuery := fmt.Sprintf(
				"UPDATE `tbl_schedule_room_items` SET %s WHERE %s",
				strmangle.SetParamNames("`", "`", 0, []string{"schedule_id"}),
				strmangle.WhereClause("`", "`", 0, tblScheduleRoomItemPrimaryKeyColumns),
			)
			values := []interface{}{o.ID, rel.ID}

			if boil.IsDebug(ctx) {
				writer := boil.DebugWriterFrom(ctx)
				fmt.Fprintln(writer, updateQuery)
				fmt.Fprintln(writer, values)
			}
			if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
				return errors.Wrap(err, "failed to update foreign table")
			}

			rel.ScheduleID = o.ID
		}
	}

	if o.R == nil {
		o.R = &tblScheduleR{
			ScheduleTBLScheduleRoomItems: related,
		}
	} else {
		o.R.ScheduleTBLScheduleRoomItems = append(o.R.ScheduleTBLScheduleRoomItems, related...)
	}

	for _, rel := range related {
		if rel.R == nil {
			rel.R = &tblScheduleRoomItemR{
				Schedule: o,
			}
		} else {
			rel.R.Schedule = o
		}
	}
	return nil
}

// TBLSchedules retrieves all the records using an executor.
func TBLSchedules(mods ...qm.QueryMod) tblScheduleQuery {
	mods = append(mods, qm.From("`tbl_schedules`"))
	q := NewQuery(mods...)
	if len(queries.GetSelect(q)) == 0 {
		queries.SetSelect(q, []string{"`tbl_schedules`.*"})
	}

	return tblScheduleQuery{q}
}

// FindTBLSchedule retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindTBLSchedule(ctx context.Context, exec boil.ContextExecutor, iD int, selectCols ...string) (*TBLSchedule, error) {
	tblScheduleObj := &TBLSchedule{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from `tbl_schedules` where `id`=?", sel,
	)

	q := queries.Raw(query, iD)

	err := q.Bind(ctx, exec, tblScheduleObj)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "dto: unable to select from tbl_schedules")
	}

	if err = tblScheduleObj.doAfterSelectHooks(ctx, exec); err != nil {
		return tblScheduleObj, err
	}

	return tblScheduleObj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *TBLSchedule) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("dto: no tbl_schedules provided for insertion")
	}

	var err error

	if err := o.doBeforeInsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(tblScheduleColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	tblScheduleInsertCacheMut.RLock()
	cache, cached := tblScheduleInsertCache[key]
	tblScheduleInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			tblScheduleAllColumns,
			tblScheduleColumnsWithDefault,
			tblScheduleColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(tblScheduleType, tblScheduleMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(tblScheduleType, tblScheduleMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO `tbl_schedules` (`%s`) %%sVALUES (%s)%%s", strings.Join(wl, "`,`"), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO `tbl_schedules` () VALUES ()%s%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			cache.retQuery = fmt.Sprintf("SELECT `%s` FROM `tbl_schedules` WHERE %s", strings.Join(returnColumns, "`,`"), strmangle.WhereClause("`", "`", 0, tblSchedulePrimaryKeyColumns))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	result, err := exec.ExecContext(ctx, cache.query, vals...)

	if err != nil {
		return errors.Wrap(err, "dto: unable to insert into tbl_schedules")
	}

	var lastID int64
	var identifierCols []interface{}

	if len(cache.retMapping) == 0 {
		goto CacheNoHooks
	}

	lastID, err = result.LastInsertId()
	if err != nil {
		return ErrSyncFail
	}

	o.ID = int(lastID)
	if lastID != 0 && len(cache.retMapping) == 1 && cache.retMapping[0] == tblScheduleMapping["id"] {
		goto CacheNoHooks
	}

	identifierCols = []interface{}{
		o.ID,
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.retQuery)
		fmt.Fprintln(writer, identifierCols...)
	}
	err = exec.QueryRowContext(ctx, cache.retQuery, identifierCols...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	if err != nil {
		return errors.Wrap(err, "dto: unable to populate default values for tbl_schedules")
	}

CacheNoHooks:
	if !cached {
		tblScheduleInsertCacheMut.Lock()
		tblScheduleInsertCache[key] = cache
		tblScheduleInsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(ctx, exec)
}

// Update uses an executor to update the TBLSchedule.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *TBLSchedule) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	var err error
	if err = o.doBeforeUpdateHooks(ctx, exec); err != nil {
		return 0, err
	}
	key := makeCacheKey(columns, nil)
	tblScheduleUpdateCacheMut.RLock()
	cache, cached := tblScheduleUpdateCache[key]
	tblScheduleUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			tblScheduleAllColumns,
			tblSchedulePrimaryKeyColumns,
		)
		if len(wl) == 0 {
			return 0, errors.New("dto: unable to update tbl_schedules, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE `tbl_schedules` SET %s WHERE %s",
			strmangle.SetParamNames("`", "`", 0, wl),
			strmangle.WhereClause("`", "`", 0, tblSchedulePrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(tblScheduleType, tblScheduleMapping, append(wl, tblSchedulePrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "dto: unable to update tbl_schedules row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "dto: failed to get rows affected by update for tbl_schedules")
	}

	if !cached {
		tblScheduleUpdateCacheMut.Lock()
		tblScheduleUpdateCache[key] = cache
		tblScheduleUpdateCacheMut.Unlock()
	}

	return rowsAff, o.doAfterUpdateHooks(ctx, exec)
}

// UpdateAll updates all rows with the specified column values.
func (q tblScheduleQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "dto: unable to update all for tbl_schedules")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "dto: unable to retrieve rows affected for tbl_schedules")
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o TBLScheduleSlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("dto: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), tblSchedulePrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE `tbl_schedules` SET %s WHERE %s",
		strmangle.SetParamNames("`", "`", 0, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, tblSchedulePrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "dto: unable to update all in tblSchedule slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "dto: unable to retrieve rows affected all in update all tblSchedule")
	}
	return rowsAff, nil
}

var mySQLTBLScheduleUniqueColumns = []string{
	"id",
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *TBLSchedule) Upsert(ctx context.Context, exec boil.ContextExecutor, updateColumns, insertColumns boil.Columns) error {
	if o == nil {
		return errors.New("dto: no tbl_schedules provided for upsert")
	}

	if err := o.doBeforeUpsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(tblScheduleColumnsWithDefault, o)
	nzUniques := queries.NonZeroDefaultSet(mySQLTBLScheduleUniqueColumns, o)

	if len(nzUniques) == 0 {
		return errors.New("cannot upsert with a table that cannot conflict on a unique column")
	}

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzUniques {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	tblScheduleUpsertCacheMut.RLock()
	cache, cached := tblScheduleUpsertCache[key]
	tblScheduleUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, _ := insertColumns.InsertColumnSet(
			tblScheduleAllColumns,
			tblScheduleColumnsWithDefault,
			tblScheduleColumnsWithoutDefault,
			nzDefaults,
		)

		update := updateColumns.UpdateColumnSet(
			tblScheduleAllColumns,
			tblSchedulePrimaryKeyColumns,
		)

		if !updateColumns.IsNone() && len(update) == 0 {
			return errors.New("dto: unable to upsert tbl_schedules, could not build update column list")
		}

		ret := strmangle.SetComplement(tblScheduleAllColumns, strmangle.SetIntersect(insert, update))

		cache.query = buildUpsertQueryMySQL(dialect, "`tbl_schedules`", update, insert)
		cache.retQuery = fmt.Sprintf(
			"SELECT %s FROM `tbl_schedules` WHERE %s",
			strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, ret), ","),
			strmangle.WhereClause("`", "`", 0, nzUniques),
		)

		cache.valueMapping, err = queries.BindMapping(tblScheduleType, tblScheduleMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(tblScheduleType, tblScheduleMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	result, err := exec.ExecContext(ctx, cache.query, vals...)

	if err != nil {
		return errors.Wrap(err, "dto: unable to upsert for tbl_schedules")
	}

	var lastID int64
	var uniqueMap []uint64
	var nzUniqueCols []interface{}

	if len(cache.retMapping) == 0 {
		goto CacheNoHooks
	}

	lastID, err = result.LastInsertId()
	if err != nil {
		return ErrSyncFail
	}

	o.ID = int(lastID)
	if lastID != 0 && len(cache.retMapping) == 1 && cache.retMapping[0] == tblScheduleMapping["id"] {
		goto CacheNoHooks
	}

	uniqueMap, err = queries.BindMapping(tblScheduleType, tblScheduleMapping, nzUniques)
	if err != nil {
		return errors.Wrap(err, "dto: unable to retrieve unique values for tbl_schedules")
	}
	nzUniqueCols = queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), uniqueMap)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.retQuery)
		fmt.Fprintln(writer, nzUniqueCols...)
	}
	err = exec.QueryRowContext(ctx, cache.retQuery, nzUniqueCols...).Scan(returns...)
	if err != nil {
		return errors.Wrap(err, "dto: unable to populate default values for tbl_schedules")
	}

CacheNoHooks:
	if !cached {
		tblScheduleUpsertCacheMut.Lock()
		tblScheduleUpsertCache[key] = cache
		tblScheduleUpsertCacheMut.Unlock()
	}

	return o.doAfterUpsertHooks(ctx, exec)
}

// Delete deletes a single TBLSchedule record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *TBLSchedule) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("dto: no TBLSchedule provided for delete")
	}

	if err := o.doBeforeDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), tblSchedulePrimaryKeyMapping)
	sql := "DELETE FROM `tbl_schedules` WHERE `id`=?"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "dto: unable to delete from tbl_schedules")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "dto: failed to get rows affected by delete for tbl_schedules")
	}

	if err := o.doAfterDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	return rowsAff, nil
}

// DeleteAll deletes all matching rows.
func (q tblScheduleQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("dto: no tblScheduleQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "dto: unable to delete all from tbl_schedules")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "dto: failed to get rows affected by deleteall for tbl_schedules")
	}

	return rowsAff, nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o TBLScheduleSlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	if len(tblScheduleBeforeDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doBeforeDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), tblSchedulePrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM `tbl_schedules` WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, tblSchedulePrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "dto: unable to delete all from tblSchedule slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "dto: failed to get rows affected by deleteall for tbl_schedules")
	}

	if len(tblScheduleAfterDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	return rowsAff, nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *TBLSchedule) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindTBLSchedule(ctx, exec, o.ID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *TBLScheduleSlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := TBLScheduleSlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), tblSchedulePrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT `tbl_schedules`.* FROM `tbl_schedules` WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, tblSchedulePrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "dto: unable to reload all in TBLScheduleSlice")
	}

	*o = slice

	return nil
}

// TBLScheduleExists checks if the TBLSchedule row exists.
func TBLScheduleExists(ctx context.Context, exec boil.ContextExecutor, iD int) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from `tbl_schedules` where `id`=? limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, iD)
	}
	row := exec.QueryRowContext(ctx, sql, iD)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "dto: unable to check if tbl_schedules exists")
	}

	return exists, nil
}

// Exists checks if the TBLSchedule row exists.
func (o *TBLSchedule) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	return TBLScheduleExists(ctx, exec, o.ID)
}
