// Code generated by SQLBoiler 4.19.5 (https://github.com/aarondl/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dto

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/aarondl/sqlboiler/v4/boil"
	"github.com/aarondl/sqlboiler/v4/queries"
	"github.com/aarondl/sqlboiler/v4/queries/qm"
	"github.com/aarondl/sqlboiler/v4/queries/qmhelper"
	"github.com/aarondl/strmangle"
	"github.com/friendsofgo/errors"
)

// TBLScheduleInvisibleRoom is an object representing the database table.
type TBLScheduleInvisibleRoom struct {
	ID         int       `boil:"id" json:"id" toml:"id" yaml:"id"`
	ScheduleID int       `boil:"schedule_id" json:"schedule_id" toml:"schedule_id" yaml:"schedule_id"`
	RoomIndex  int       `boil:"room_index" json:"room_index" toml:"room_index" yaml:"room_index"`
	CreatedAt  time.Time `boil:"created_at" json:"created_at" toml:"created_at" yaml:"created_at"`

	R *tblScheduleInvisibleRoomR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L tblScheduleInvisibleRoomL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var TBLScheduleInvisibleRoomColumns = struct {
	ID         string
	ScheduleID string
	RoomIndex  string
	CreatedAt  string
}{
	ID:         "id",
	ScheduleID: "schedule_id",
	RoomIndex:  "room_index",
	CreatedAt:  "created_at",
}

var TBLScheduleInvisibleRoomTableColumns = struct {
	ID         string
	ScheduleID string
	RoomIndex  string
	CreatedAt  string
}{
	ID:         "tbl_schedule_invisible_rooms.id",
	ScheduleID: "tbl_schedule_invisible_rooms.schedule_id",
	RoomIndex:  "tbl_schedule_invisible_rooms.room_index",
	CreatedAt:  "tbl_schedule_invisible_rooms.created_at",
}

// Generated where

var TBLScheduleInvisibleRoomWhere = struct {
	ID         whereHelperint
	ScheduleID whereHelperint
	RoomIndex  whereHelperint
	CreatedAt  whereHelpertime_Time
}{
	ID:         whereHelperint{field: "`tbl_schedule_invisible_rooms`.`id`"},
	ScheduleID: whereHelperint{field: "`tbl_schedule_invisible_rooms`.`schedule_id`"},
	RoomIndex:  whereHelperint{field: "`tbl_schedule_invisible_rooms`.`room_index`"},
	CreatedAt:  whereHelpertime_Time{field: "`tbl_schedule_invisible_rooms`.`created_at`"},
}

// TBLScheduleInvisibleRoomRels is where relationship names are stored.
var TBLScheduleInvisibleRoomRels = struct {
}{}

// tblScheduleInvisibleRoomR is where relationships are stored.
type tblScheduleInvisibleRoomR struct {
}

// NewStruct creates a new relationship struct
func (*tblScheduleInvisibleRoomR) NewStruct() *tblScheduleInvisibleRoomR {
	return &tblScheduleInvisibleRoomR{}
}

// tblScheduleInvisibleRoomL is where Load methods for each relationship are stored.
type tblScheduleInvisibleRoomL struct{}

var (
	tblScheduleInvisibleRoomAllColumns            = []string{"id", "schedule_id", "room_index", "created_at"}
	tblScheduleInvisibleRoomColumnsWithoutDefault = []string{"schedule_id", "room_index"}
	tblScheduleInvisibleRoomColumnsWithDefault    = []string{"id", "created_at"}
	tblScheduleInvisibleRoomPrimaryKeyColumns     = []string{"id"}
	tblScheduleInvisibleRoomGeneratedColumns      = []string{}
)

type (
	// TBLScheduleInvisibleRoomSlice is an alias for a slice of pointers to TBLScheduleInvisibleRoom.
	// This should almost always be used instead of []TBLScheduleInvisibleRoom.
	TBLScheduleInvisibleRoomSlice []*TBLScheduleInvisibleRoom
	// TBLScheduleInvisibleRoomHook is the signature for custom TBLScheduleInvisibleRoom hook methods
	TBLScheduleInvisibleRoomHook func(context.Context, boil.ContextExecutor, *TBLScheduleInvisibleRoom) error

	tblScheduleInvisibleRoomQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	tblScheduleInvisibleRoomType                 = reflect.TypeOf(&TBLScheduleInvisibleRoom{})
	tblScheduleInvisibleRoomMapping              = queries.MakeStructMapping(tblScheduleInvisibleRoomType)
	tblScheduleInvisibleRoomPrimaryKeyMapping, _ = queries.BindMapping(tblScheduleInvisibleRoomType, tblScheduleInvisibleRoomMapping, tblScheduleInvisibleRoomPrimaryKeyColumns)
	tblScheduleInvisibleRoomInsertCacheMut       sync.RWMutex
	tblScheduleInvisibleRoomInsertCache          = make(map[string]insertCache)
	tblScheduleInvisibleRoomUpdateCacheMut       sync.RWMutex
	tblScheduleInvisibleRoomUpdateCache          = make(map[string]updateCache)
	tblScheduleInvisibleRoomUpsertCacheMut       sync.RWMutex
	tblScheduleInvisibleRoomUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

var tblScheduleInvisibleRoomAfterSelectMu sync.Mutex
var tblScheduleInvisibleRoomAfterSelectHooks []TBLScheduleInvisibleRoomHook

var tblScheduleInvisibleRoomBeforeInsertMu sync.Mutex
var tblScheduleInvisibleRoomBeforeInsertHooks []TBLScheduleInvisibleRoomHook
var tblScheduleInvisibleRoomAfterInsertMu sync.Mutex
var tblScheduleInvisibleRoomAfterInsertHooks []TBLScheduleInvisibleRoomHook

var tblScheduleInvisibleRoomBeforeUpdateMu sync.Mutex
var tblScheduleInvisibleRoomBeforeUpdateHooks []TBLScheduleInvisibleRoomHook
var tblScheduleInvisibleRoomAfterUpdateMu sync.Mutex
var tblScheduleInvisibleRoomAfterUpdateHooks []TBLScheduleInvisibleRoomHook

var tblScheduleInvisibleRoomBeforeDeleteMu sync.Mutex
var tblScheduleInvisibleRoomBeforeDeleteHooks []TBLScheduleInvisibleRoomHook
var tblScheduleInvisibleRoomAfterDeleteMu sync.Mutex
var tblScheduleInvisibleRoomAfterDeleteHooks []TBLScheduleInvisibleRoomHook

var tblScheduleInvisibleRoomBeforeUpsertMu sync.Mutex
var tblScheduleInvisibleRoomBeforeUpsertHooks []TBLScheduleInvisibleRoomHook
var tblScheduleInvisibleRoomAfterUpsertMu sync.Mutex
var tblScheduleInvisibleRoomAfterUpsertHooks []TBLScheduleInvisibleRoomHook

// doAfterSelectHooks executes all "after Select" hooks.
func (o *TBLScheduleInvisibleRoom) doAfterSelectHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range tblScheduleInvisibleRoomAfterSelectHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *TBLScheduleInvisibleRoom) doBeforeInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range tblScheduleInvisibleRoomBeforeInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *TBLScheduleInvisibleRoom) doAfterInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range tblScheduleInvisibleRoomAfterInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpdateHooks executes all "before Update" hooks.
func (o *TBLScheduleInvisibleRoom) doBeforeUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range tblScheduleInvisibleRoomBeforeUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpdateHooks executes all "after Update" hooks.
func (o *TBLScheduleInvisibleRoom) doAfterUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range tblScheduleInvisibleRoomAfterUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeDeleteHooks executes all "before Delete" hooks.
func (o *TBLScheduleInvisibleRoom) doBeforeDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range tblScheduleInvisibleRoomBeforeDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterDeleteHooks executes all "after Delete" hooks.
func (o *TBLScheduleInvisibleRoom) doAfterDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range tblScheduleInvisibleRoomAfterDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *TBLScheduleInvisibleRoom) doBeforeUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range tblScheduleInvisibleRoomBeforeUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *TBLScheduleInvisibleRoom) doAfterUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range tblScheduleInvisibleRoomAfterUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddTBLScheduleInvisibleRoomHook registers your hook function for all future operations.
func AddTBLScheduleInvisibleRoomHook(hookPoint boil.HookPoint, tblScheduleInvisibleRoomHook TBLScheduleInvisibleRoomHook) {
	switch hookPoint {
	case boil.AfterSelectHook:
		tblScheduleInvisibleRoomAfterSelectMu.Lock()
		tblScheduleInvisibleRoomAfterSelectHooks = append(tblScheduleInvisibleRoomAfterSelectHooks, tblScheduleInvisibleRoomHook)
		tblScheduleInvisibleRoomAfterSelectMu.Unlock()
	case boil.BeforeInsertHook:
		tblScheduleInvisibleRoomBeforeInsertMu.Lock()
		tblScheduleInvisibleRoomBeforeInsertHooks = append(tblScheduleInvisibleRoomBeforeInsertHooks, tblScheduleInvisibleRoomHook)
		tblScheduleInvisibleRoomBeforeInsertMu.Unlock()
	case boil.AfterInsertHook:
		tblScheduleInvisibleRoomAfterInsertMu.Lock()
		tblScheduleInvisibleRoomAfterInsertHooks = append(tblScheduleInvisibleRoomAfterInsertHooks, tblScheduleInvisibleRoomHook)
		tblScheduleInvisibleRoomAfterInsertMu.Unlock()
	case boil.BeforeUpdateHook:
		tblScheduleInvisibleRoomBeforeUpdateMu.Lock()
		tblScheduleInvisibleRoomBeforeUpdateHooks = append(tblScheduleInvisibleRoomBeforeUpdateHooks, tblScheduleInvisibleRoomHook)
		tblScheduleInvisibleRoomBeforeUpdateMu.Unlock()
	case boil.AfterUpdateHook:
		tblScheduleInvisibleRoomAfterUpdateMu.Lock()
		tblScheduleInvisibleRoomAfterUpdateHooks = append(tblScheduleInvisibleRoomAfterUpdateHooks, tblScheduleInvisibleRoomHook)
		tblScheduleInvisibleRoomAfterUpdateMu.Unlock()
	case boil.BeforeDeleteHook:
		tblScheduleInvisibleRoomBeforeDeleteMu.Lock()
		tblScheduleInvisibleRoomBeforeDeleteHooks = append(tblScheduleInvisibleRoomBeforeDeleteHooks, tblScheduleInvisibleRoomHook)
		tblScheduleInvisibleRoomBeforeDeleteMu.Unlock()
	case boil.AfterDeleteHook:
		tblScheduleInvisibleRoomAfterDeleteMu.Lock()
		tblScheduleInvisibleRoomAfterDeleteHooks = append(tblScheduleInvisibleRoomAfterDeleteHooks, tblScheduleInvisibleRoomHook)
		tblScheduleInvisibleRoomAfterDeleteMu.Unlock()
	case boil.BeforeUpsertHook:
		tblScheduleInvisibleRoomBeforeUpsertMu.Lock()
		tblScheduleInvisibleRoomBeforeUpsertHooks = append(tblScheduleInvisibleRoomBeforeUpsertHooks, tblScheduleInvisibleRoomHook)
		tblScheduleInvisibleRoomBeforeUpsertMu.Unlock()
	case boil.AfterUpsertHook:
		tblScheduleInvisibleRoomAfterUpsertMu.Lock()
		tblScheduleInvisibleRoomAfterUpsertHooks = append(tblScheduleInvisibleRoomAfterUpsertHooks, tblScheduleInvisibleRoomHook)
		tblScheduleInvisibleRoomAfterUpsertMu.Unlock()
	}
}

// One returns a single tblScheduleInvisibleRoom record from the query.
func (q tblScheduleInvisibleRoomQuery) One(ctx context.Context, exec boil.ContextExecutor) (*TBLScheduleInvisibleRoom, error) {
	o := &TBLScheduleInvisibleRoom{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "dto: failed to execute a one query for tbl_schedule_invisible_rooms")
	}

	if err := o.doAfterSelectHooks(ctx, exec); err != nil {
		return o, err
	}

	return o, nil
}

// All returns all TBLScheduleInvisibleRoom records from the query.
func (q tblScheduleInvisibleRoomQuery) All(ctx context.Context, exec boil.ContextExecutor) (TBLScheduleInvisibleRoomSlice, error) {
	var o []*TBLScheduleInvisibleRoom

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "dto: failed to assign all query results to TBLScheduleInvisibleRoom slice")
	}

	if len(tblScheduleInvisibleRoomAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(ctx, exec); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// Count returns the count of all TBLScheduleInvisibleRoom records in the query.
func (q tblScheduleInvisibleRoomQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "dto: failed to count tbl_schedule_invisible_rooms rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q tblScheduleInvisibleRoomQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "dto: failed to check if tbl_schedule_invisible_rooms exists")
	}

	return count > 0, nil
}

// TBLScheduleInvisibleRooms retrieves all the records using an executor.
func TBLScheduleInvisibleRooms(mods ...qm.QueryMod) tblScheduleInvisibleRoomQuery {
	mods = append(mods, qm.From("`tbl_schedule_invisible_rooms`"))
	q := NewQuery(mods...)
	if len(queries.GetSelect(q)) == 0 {
		queries.SetSelect(q, []string{"`tbl_schedule_invisible_rooms`.*"})
	}

	return tblScheduleInvisibleRoomQuery{q}
}

// FindTBLScheduleInvisibleRoom retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindTBLScheduleInvisibleRoom(ctx context.Context, exec boil.ContextExecutor, iD int, selectCols ...string) (*TBLScheduleInvisibleRoom, error) {
	tblScheduleInvisibleRoomObj := &TBLScheduleInvisibleRoom{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from `tbl_schedule_invisible_rooms` where `id`=?", sel,
	)

	q := queries.Raw(query, iD)

	err := q.Bind(ctx, exec, tblScheduleInvisibleRoomObj)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "dto: unable to select from tbl_schedule_invisible_rooms")
	}

	if err = tblScheduleInvisibleRoomObj.doAfterSelectHooks(ctx, exec); err != nil {
		return tblScheduleInvisibleRoomObj, err
	}

	return tblScheduleInvisibleRoomObj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *TBLScheduleInvisibleRoom) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("dto: no tbl_schedule_invisible_rooms provided for insertion")
	}

	var err error

	if err := o.doBeforeInsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(tblScheduleInvisibleRoomColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	tblScheduleInvisibleRoomInsertCacheMut.RLock()
	cache, cached := tblScheduleInvisibleRoomInsertCache[key]
	tblScheduleInvisibleRoomInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			tblScheduleInvisibleRoomAllColumns,
			tblScheduleInvisibleRoomColumnsWithDefault,
			tblScheduleInvisibleRoomColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(tblScheduleInvisibleRoomType, tblScheduleInvisibleRoomMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(tblScheduleInvisibleRoomType, tblScheduleInvisibleRoomMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO `tbl_schedule_invisible_rooms` (`%s`) %%sVALUES (%s)%%s", strings.Join(wl, "`,`"), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO `tbl_schedule_invisible_rooms` () VALUES ()%s%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			cache.retQuery = fmt.Sprintf("SELECT `%s` FROM `tbl_schedule_invisible_rooms` WHERE %s", strings.Join(returnColumns, "`,`"), strmangle.WhereClause("`", "`", 0, tblScheduleInvisibleRoomPrimaryKeyColumns))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	result, err := exec.ExecContext(ctx, cache.query, vals...)

	if err != nil {
		return errors.Wrap(err, "dto: unable to insert into tbl_schedule_invisible_rooms")
	}

	var lastID int64
	var identifierCols []interface{}

	if len(cache.retMapping) == 0 {
		goto CacheNoHooks
	}

	lastID, err = result.LastInsertId()
	if err != nil {
		return ErrSyncFail
	}

	o.ID = int(lastID)
	if lastID != 0 && len(cache.retMapping) == 1 && cache.retMapping[0] == tblScheduleInvisibleRoomMapping["id"] {
		goto CacheNoHooks
	}

	identifierCols = []interface{}{
		o.ID,
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.retQuery)
		fmt.Fprintln(writer, identifierCols...)
	}
	err = exec.QueryRowContext(ctx, cache.retQuery, identifierCols...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	if err != nil {
		return errors.Wrap(err, "dto: unable to populate default values for tbl_schedule_invisible_rooms")
	}

CacheNoHooks:
	if !cached {
		tblScheduleInvisibleRoomInsertCacheMut.Lock()
		tblScheduleInvisibleRoomInsertCache[key] = cache
		tblScheduleInvisibleRoomInsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(ctx, exec)
}

// Update uses an executor to update the TBLScheduleInvisibleRoom.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *TBLScheduleInvisibleRoom) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	var err error
	if err = o.doBeforeUpdateHooks(ctx, exec); err != nil {
		return 0, err
	}
	key := makeCacheKey(columns, nil)
	tblScheduleInvisibleRoomUpdateCacheMut.RLock()
	cache, cached := tblScheduleInvisibleRoomUpdateCache[key]
	tblScheduleInvisibleRoomUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			tblScheduleInvisibleRoomAllColumns,
			tblScheduleInvisibleRoomPrimaryKeyColumns,
		)
		if len(wl) == 0 {
			return 0, errors.New("dto: unable to update tbl_schedule_invisible_rooms, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE `tbl_schedule_invisible_rooms` SET %s WHERE %s",
			strmangle.SetParamNames("`", "`", 0, wl),
			strmangle.WhereClause("`", "`", 0, tblScheduleInvisibleRoomPrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(tblScheduleInvisibleRoomType, tblScheduleInvisibleRoomMapping, append(wl, tblScheduleInvisibleRoomPrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "dto: unable to update tbl_schedule_invisible_rooms row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "dto: failed to get rows affected by update for tbl_schedule_invisible_rooms")
	}

	if !cached {
		tblScheduleInvisibleRoomUpdateCacheMut.Lock()
		tblScheduleInvisibleRoomUpdateCache[key] = cache
		tblScheduleInvisibleRoomUpdateCacheMut.Unlock()
	}

	return rowsAff, o.doAfterUpdateHooks(ctx, exec)
}

// UpdateAll updates all rows with the specified column values.
func (q tblScheduleInvisibleRoomQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "dto: unable to update all for tbl_schedule_invisible_rooms")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "dto: unable to retrieve rows affected for tbl_schedule_invisible_rooms")
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o TBLScheduleInvisibleRoomSlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("dto: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), tblScheduleInvisibleRoomPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE `tbl_schedule_invisible_rooms` SET %s WHERE %s",
		strmangle.SetParamNames("`", "`", 0, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, tblScheduleInvisibleRoomPrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "dto: unable to update all in tblScheduleInvisibleRoom slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "dto: unable to retrieve rows affected all in update all tblScheduleInvisibleRoom")
	}
	return rowsAff, nil
}

var mySQLTBLScheduleInvisibleRoomUniqueColumns = []string{
	"id",
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *TBLScheduleInvisibleRoom) Upsert(ctx context.Context, exec boil.ContextExecutor, updateColumns, insertColumns boil.Columns) error {
	if o == nil {
		return errors.New("dto: no tbl_schedule_invisible_rooms provided for upsert")
	}

	if err := o.doBeforeUpsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(tblScheduleInvisibleRoomColumnsWithDefault, o)
	nzUniques := queries.NonZeroDefaultSet(mySQLTBLScheduleInvisibleRoomUniqueColumns, o)

	if len(nzUniques) == 0 {
		return errors.New("cannot upsert with a table that cannot conflict on a unique column")
	}

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzUniques {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	tblScheduleInvisibleRoomUpsertCacheMut.RLock()
	cache, cached := tblScheduleInvisibleRoomUpsertCache[key]
	tblScheduleInvisibleRoomUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, _ := insertColumns.InsertColumnSet(
			tblScheduleInvisibleRoomAllColumns,
			tblScheduleInvisibleRoomColumnsWithDefault,
			tblScheduleInvisibleRoomColumnsWithoutDefault,
			nzDefaults,
		)

		update := updateColumns.UpdateColumnSet(
			tblScheduleInvisibleRoomAllColumns,
			tblScheduleInvisibleRoomPrimaryKeyColumns,
		)

		if !updateColumns.IsNone() && len(update) == 0 {
			return errors.New("dto: unable to upsert tbl_schedule_invisible_rooms, could not build update column list")
		}

		ret := strmangle.SetComplement(tblScheduleInvisibleRoomAllColumns, strmangle.SetIntersect(insert, update))

		cache.query = buildUpsertQueryMySQL(dialect, "`tbl_schedule_invisible_rooms`", update, insert)
		cache.retQuery = fmt.Sprintf(
			"SELECT %s FROM `tbl_schedule_invisible_rooms` WHERE %s",
			strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, ret), ","),
			strmangle.WhereClause("`", "`", 0, nzUniques),
		)

		cache.valueMapping, err = queries.BindMapping(tblScheduleInvisibleRoomType, tblScheduleInvisibleRoomMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(tblScheduleInvisibleRoomType, tblScheduleInvisibleRoomMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	result, err := exec.ExecContext(ctx, cache.query, vals...)

	if err != nil {
		return errors.Wrap(err, "dto: unable to upsert for tbl_schedule_invisible_rooms")
	}

	var lastID int64
	var uniqueMap []uint64
	var nzUniqueCols []interface{}

	if len(cache.retMapping) == 0 {
		goto CacheNoHooks
	}

	lastID, err = result.LastInsertId()
	if err != nil {
		return ErrSyncFail
	}

	o.ID = int(lastID)
	if lastID != 0 && len(cache.retMapping) == 1 && cache.retMapping[0] == tblScheduleInvisibleRoomMapping["id"] {
		goto CacheNoHooks
	}

	uniqueMap, err = queries.BindMapping(tblScheduleInvisibleRoomType, tblScheduleInvisibleRoomMapping, nzUniques)
	if err != nil {
		return errors.Wrap(err, "dto: unable to retrieve unique values for tbl_schedule_invisible_rooms")
	}
	nzUniqueCols = queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), uniqueMap)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.retQuery)
		fmt.Fprintln(writer, nzUniqueCols...)
	}
	err = exec.QueryRowContext(ctx, cache.retQuery, nzUniqueCols...).Scan(returns...)
	if err != nil {
		return errors.Wrap(err, "dto: unable to populate default values for tbl_schedule_invisible_rooms")
	}

CacheNoHooks:
	if !cached {
		tblScheduleInvisibleRoomUpsertCacheMut.Lock()
		tblScheduleInvisibleRoomUpsertCache[key] = cache
		tblScheduleInvisibleRoomUpsertCacheMut.Unlock()
	}

	return o.doAfterUpsertHooks(ctx, exec)
}

// Delete deletes a single TBLScheduleInvisibleRoom record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *TBLScheduleInvisibleRoom) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("dto: no TBLScheduleInvisibleRoom provided for delete")
	}

	if err := o.doBeforeDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), tblScheduleInvisibleRoomPrimaryKeyMapping)
	sql := "DELETE FROM `tbl_schedule_invisible_rooms` WHERE `id`=?"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "dto: unable to delete from tbl_schedule_invisible_rooms")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "dto: failed to get rows affected by delete for tbl_schedule_invisible_rooms")
	}

	if err := o.doAfterDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	return rowsAff, nil
}

// DeleteAll deletes all matching rows.
func (q tblScheduleInvisibleRoomQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("dto: no tblScheduleInvisibleRoomQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "dto: unable to delete all from tbl_schedule_invisible_rooms")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "dto: failed to get rows affected by deleteall for tbl_schedule_invisible_rooms")
	}

	return rowsAff, nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o TBLScheduleInvisibleRoomSlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	if len(tblScheduleInvisibleRoomBeforeDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doBeforeDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), tblScheduleInvisibleRoomPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM `tbl_schedule_invisible_rooms` WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, tblScheduleInvisibleRoomPrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "dto: unable to delete all from tblScheduleInvisibleRoom slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "dto: failed to get rows affected by deleteall for tbl_schedule_invisible_rooms")
	}

	if len(tblScheduleInvisibleRoomAfterDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	return rowsAff, nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *TBLScheduleInvisibleRoom) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindTBLScheduleInvisibleRoom(ctx, exec, o.ID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *TBLScheduleInvisibleRoomSlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := TBLScheduleInvisibleRoomSlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), tblScheduleInvisibleRoomPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT `tbl_schedule_invisible_rooms`.* FROM `tbl_schedule_invisible_rooms` WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, tblScheduleInvisibleRoomPrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "dto: unable to reload all in TBLScheduleInvisibleRoomSlice")
	}

	*o = slice

	return nil
}

// TBLScheduleInvisibleRoomExists checks if the TBLScheduleInvisibleRoom row exists.
func TBLScheduleInvisibleRoomExists(ctx context.Context, exec boil.ContextExecutor, iD int) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from `tbl_schedule_invisible_rooms` where `id`=? limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, iD)
	}
	row := exec.QueryRowContext(ctx, sql, iD)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "dto: unable to check if tbl_schedule_invisible_rooms exists")
	}

	return exists, nil
}

// Exists checks if the TBLScheduleInvisibleRoom row exists.
func (o *TBLScheduleInvisibleRoom) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	return TBLScheduleInvisibleRoomExists(ctx, exec, o.ID)
}
