// Code generated by SQLBoiler 4.19.5 (https://github.com/aarondl/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dto

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/aarondl/sqlboiler/v4/boil"
	"github.com/aarondl/sqlboiler/v4/queries"
	"github.com/aarondl/sqlboiler/v4/queries/qm"
	"github.com/aarondl/sqlboiler/v4/queries/qmhelper"
	"github.com/aarondl/strmangle"
	"github.com/friendsofgo/errors"
)

// TBLUser is an object representing the database table.
type TBLUser struct {
	ID           int       `boil:"id" json:"id" toml:"id" yaml:"id"`
	RoleKey      string    `boil:"role_key" json:"role_key" toml:"role_key" yaml:"role_key"`
	UserName     string    `boil:"user_name" json:"user_name" toml:"user_name" yaml:"user_name"`
	Password     string    `boil:"password" json:"password" toml:"password" yaml:"password"`
	Name         string    `boil:"name" json:"name" toml:"name" yaml:"name"`
	UpdateUserID int       `boil:"update_user_id" json:"update_user_id" toml:"update_user_id" yaml:"update_user_id"`
	DeleteFlag   int       `boil:"delete_flag" json:"delete_flag" toml:"delete_flag" yaml:"delete_flag"`
	CreatedAt    time.Time `boil:"created_at" json:"created_at" toml:"created_at" yaml:"created_at"`
	UpdatedAt    time.Time `boil:"updated_at" json:"updated_at" toml:"updated_at" yaml:"updated_at"`

	R *tblUserR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L tblUserL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var TBLUserColumns = struct {
	ID           string
	RoleKey      string
	UserName     string
	Password     string
	Name         string
	UpdateUserID string
	DeleteFlag   string
	CreatedAt    string
	UpdatedAt    string
}{
	ID:           "id",
	RoleKey:      "role_key",
	UserName:     "user_name",
	Password:     "password",
	Name:         "name",
	UpdateUserID: "update_user_id",
	DeleteFlag:   "delete_flag",
	CreatedAt:    "created_at",
	UpdatedAt:    "updated_at",
}

var TBLUserTableColumns = struct {
	ID           string
	RoleKey      string
	UserName     string
	Password     string
	Name         string
	UpdateUserID string
	DeleteFlag   string
	CreatedAt    string
	UpdatedAt    string
}{
	ID:           "tbl_users.id",
	RoleKey:      "tbl_users.role_key",
	UserName:     "tbl_users.user_name",
	Password:     "tbl_users.password",
	Name:         "tbl_users.name",
	UpdateUserID: "tbl_users.update_user_id",
	DeleteFlag:   "tbl_users.delete_flag",
	CreatedAt:    "tbl_users.created_at",
	UpdatedAt:    "tbl_users.updated_at",
}

// Generated where

var TBLUserWhere = struct {
	ID           whereHelperint
	RoleKey      whereHelperstring
	UserName     whereHelperstring
	Password     whereHelperstring
	Name         whereHelperstring
	UpdateUserID whereHelperint
	DeleteFlag   whereHelperint
	CreatedAt    whereHelpertime_Time
	UpdatedAt    whereHelpertime_Time
}{
	ID:           whereHelperint{field: "`tbl_users`.`id`"},
	RoleKey:      whereHelperstring{field: "`tbl_users`.`role_key`"},
	UserName:     whereHelperstring{field: "`tbl_users`.`user_name`"},
	Password:     whereHelperstring{field: "`tbl_users`.`password`"},
	Name:         whereHelperstring{field: "`tbl_users`.`name`"},
	UpdateUserID: whereHelperint{field: "`tbl_users`.`update_user_id`"},
	DeleteFlag:   whereHelperint{field: "`tbl_users`.`delete_flag`"},
	CreatedAt:    whereHelpertime_Time{field: "`tbl_users`.`created_at`"},
	UpdatedAt:    whereHelpertime_Time{field: "`tbl_users`.`updated_at`"},
}

// TBLUserRels is where relationship names are stored.
var TBLUserRels = struct {
	RoleKeyDataRole            string
	UpdateUser                 string
	CreateUserTBLSchedules     string
	LastUpdateUserTBLSchedules string
	UpdateUserTBLUsers         string
}{
	RoleKeyDataRole:            "RoleKeyDataRole",
	UpdateUser:                 "UpdateUser",
	CreateUserTBLSchedules:     "CreateUserTBLSchedules",
	LastUpdateUserTBLSchedules: "LastUpdateUserTBLSchedules",
	UpdateUserTBLUsers:         "UpdateUserTBLUsers",
}

// tblUserR is where relationships are stored.
type tblUserR struct {
	RoleKeyDataRole            *DataRole        `boil:"RoleKeyDataRole" json:"RoleKeyDataRole" toml:"RoleKeyDataRole" yaml:"RoleKeyDataRole"`
	UpdateUser                 *TBLUser         `boil:"UpdateUser" json:"UpdateUser" toml:"UpdateUser" yaml:"UpdateUser"`
	CreateUserTBLSchedules     TBLScheduleSlice `boil:"CreateUserTBLSchedules" json:"CreateUserTBLSchedules" toml:"CreateUserTBLSchedules" yaml:"CreateUserTBLSchedules"`
	LastUpdateUserTBLSchedules TBLScheduleSlice `boil:"LastUpdateUserTBLSchedules" json:"LastUpdateUserTBLSchedules" toml:"LastUpdateUserTBLSchedules" yaml:"LastUpdateUserTBLSchedules"`
	UpdateUserTBLUsers         TBLUserSlice     `boil:"UpdateUserTBLUsers" json:"UpdateUserTBLUsers" toml:"UpdateUserTBLUsers" yaml:"UpdateUserTBLUsers"`
}

// NewStruct creates a new relationship struct
func (*tblUserR) NewStruct() *tblUserR {
	return &tblUserR{}
}

func (o *TBLUser) GetRoleKeyDataRole() *DataRole {
	if o == nil {
		return nil
	}

	return o.R.GetRoleKeyDataRole()
}

func (r *tblUserR) GetRoleKeyDataRole() *DataRole {
	if r == nil {
		return nil
	}

	return r.RoleKeyDataRole
}

func (o *TBLUser) GetUpdateUser() *TBLUser {
	if o == nil {
		return nil
	}

	return o.R.GetUpdateUser()
}

func (r *tblUserR) GetUpdateUser() *TBLUser {
	if r == nil {
		return nil
	}

	return r.UpdateUser
}

func (o *TBLUser) GetCreateUserTBLSchedules() TBLScheduleSlice {
	if o == nil {
		return nil
	}

	return o.R.GetCreateUserTBLSchedules()
}

func (r *tblUserR) GetCreateUserTBLSchedules() TBLScheduleSlice {
	if r == nil {
		return nil
	}

	return r.CreateUserTBLSchedules
}

func (o *TBLUser) GetLastUpdateUserTBLSchedules() TBLScheduleSlice {
	if o == nil {
		return nil
	}

	return o.R.GetLastUpdateUserTBLSchedules()
}

func (r *tblUserR) GetLastUpdateUserTBLSchedules() TBLScheduleSlice {
	if r == nil {
		return nil
	}

	return r.LastUpdateUserTBLSchedules
}

func (o *TBLUser) GetUpdateUserTBLUsers() TBLUserSlice {
	if o == nil {
		return nil
	}

	return o.R.GetUpdateUserTBLUsers()
}

func (r *tblUserR) GetUpdateUserTBLUsers() TBLUserSlice {
	if r == nil {
		return nil
	}

	return r.UpdateUserTBLUsers
}

// tblUserL is where Load methods for each relationship are stored.
type tblUserL struct{}

var (
	tblUserAllColumns            = []string{"id", "role_key", "user_name", "password", "name", "update_user_id", "delete_flag", "created_at", "updated_at"}
	tblUserColumnsWithoutDefault = []string{"role_key", "user_name", "password", "name", "update_user_id", "delete_flag"}
	tblUserColumnsWithDefault    = []string{"id", "created_at", "updated_at"}
	tblUserPrimaryKeyColumns     = []string{"id"}
	tblUserGeneratedColumns      = []string{}
)

type (
	// TBLUserSlice is an alias for a slice of pointers to TBLUser.
	// This should almost always be used instead of []TBLUser.
	TBLUserSlice []*TBLUser
	// TBLUserHook is the signature for custom TBLUser hook methods
	TBLUserHook func(context.Context, boil.ContextExecutor, *TBLUser) error

	tblUserQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	tblUserType                 = reflect.TypeOf(&TBLUser{})
	tblUserMapping              = queries.MakeStructMapping(tblUserType)
	tblUserPrimaryKeyMapping, _ = queries.BindMapping(tblUserType, tblUserMapping, tblUserPrimaryKeyColumns)
	tblUserInsertCacheMut       sync.RWMutex
	tblUserInsertCache          = make(map[string]insertCache)
	tblUserUpdateCacheMut       sync.RWMutex
	tblUserUpdateCache          = make(map[string]updateCache)
	tblUserUpsertCacheMut       sync.RWMutex
	tblUserUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

var tblUserAfterSelectMu sync.Mutex
var tblUserAfterSelectHooks []TBLUserHook

var tblUserBeforeInsertMu sync.Mutex
var tblUserBeforeInsertHooks []TBLUserHook
var tblUserAfterInsertMu sync.Mutex
var tblUserAfterInsertHooks []TBLUserHook

var tblUserBeforeUpdateMu sync.Mutex
var tblUserBeforeUpdateHooks []TBLUserHook
var tblUserAfterUpdateMu sync.Mutex
var tblUserAfterUpdateHooks []TBLUserHook

var tblUserBeforeDeleteMu sync.Mutex
var tblUserBeforeDeleteHooks []TBLUserHook
var tblUserAfterDeleteMu sync.Mutex
var tblUserAfterDeleteHooks []TBLUserHook

var tblUserBeforeUpsertMu sync.Mutex
var tblUserBeforeUpsertHooks []TBLUserHook
var tblUserAfterUpsertMu sync.Mutex
var tblUserAfterUpsertHooks []TBLUserHook

// doAfterSelectHooks executes all "after Select" hooks.
func (o *TBLUser) doAfterSelectHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range tblUserAfterSelectHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *TBLUser) doBeforeInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range tblUserBeforeInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *TBLUser) doAfterInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range tblUserAfterInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpdateHooks executes all "before Update" hooks.
func (o *TBLUser) doBeforeUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range tblUserBeforeUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpdateHooks executes all "after Update" hooks.
func (o *TBLUser) doAfterUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range tblUserAfterUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeDeleteHooks executes all "before Delete" hooks.
func (o *TBLUser) doBeforeDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range tblUserBeforeDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterDeleteHooks executes all "after Delete" hooks.
func (o *TBLUser) doAfterDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range tblUserAfterDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *TBLUser) doBeforeUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range tblUserBeforeUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *TBLUser) doAfterUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range tblUserAfterUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddTBLUserHook registers your hook function for all future operations.
func AddTBLUserHook(hookPoint boil.HookPoint, tblUserHook TBLUserHook) {
	switch hookPoint {
	case boil.AfterSelectHook:
		tblUserAfterSelectMu.Lock()
		tblUserAfterSelectHooks = append(tblUserAfterSelectHooks, tblUserHook)
		tblUserAfterSelectMu.Unlock()
	case boil.BeforeInsertHook:
		tblUserBeforeInsertMu.Lock()
		tblUserBeforeInsertHooks = append(tblUserBeforeInsertHooks, tblUserHook)
		tblUserBeforeInsertMu.Unlock()
	case boil.AfterInsertHook:
		tblUserAfterInsertMu.Lock()
		tblUserAfterInsertHooks = append(tblUserAfterInsertHooks, tblUserHook)
		tblUserAfterInsertMu.Unlock()
	case boil.BeforeUpdateHook:
		tblUserBeforeUpdateMu.Lock()
		tblUserBeforeUpdateHooks = append(tblUserBeforeUpdateHooks, tblUserHook)
		tblUserBeforeUpdateMu.Unlock()
	case boil.AfterUpdateHook:
		tblUserAfterUpdateMu.Lock()
		tblUserAfterUpdateHooks = append(tblUserAfterUpdateHooks, tblUserHook)
		tblUserAfterUpdateMu.Unlock()
	case boil.BeforeDeleteHook:
		tblUserBeforeDeleteMu.Lock()
		tblUserBeforeDeleteHooks = append(tblUserBeforeDeleteHooks, tblUserHook)
		tblUserBeforeDeleteMu.Unlock()
	case boil.AfterDeleteHook:
		tblUserAfterDeleteMu.Lock()
		tblUserAfterDeleteHooks = append(tblUserAfterDeleteHooks, tblUserHook)
		tblUserAfterDeleteMu.Unlock()
	case boil.BeforeUpsertHook:
		tblUserBeforeUpsertMu.Lock()
		tblUserBeforeUpsertHooks = append(tblUserBeforeUpsertHooks, tblUserHook)
		tblUserBeforeUpsertMu.Unlock()
	case boil.AfterUpsertHook:
		tblUserAfterUpsertMu.Lock()
		tblUserAfterUpsertHooks = append(tblUserAfterUpsertHooks, tblUserHook)
		tblUserAfterUpsertMu.Unlock()
	}
}

// One returns a single tblUser record from the query.
func (q tblUserQuery) One(ctx context.Context, exec boil.ContextExecutor) (*TBLUser, error) {
	o := &TBLUser{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "dto: failed to execute a one query for tbl_users")
	}

	if err := o.doAfterSelectHooks(ctx, exec); err != nil {
		return o, err
	}

	return o, nil
}

// All returns all TBLUser records from the query.
func (q tblUserQuery) All(ctx context.Context, exec boil.ContextExecutor) (TBLUserSlice, error) {
	var o []*TBLUser

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "dto: failed to assign all query results to TBLUser slice")
	}

	if len(tblUserAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(ctx, exec); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// Count returns the count of all TBLUser records in the query.
func (q tblUserQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "dto: failed to count tbl_users rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q tblUserQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "dto: failed to check if tbl_users exists")
	}

	return count > 0, nil
}

// RoleKeyDataRole pointed to by the foreign key.
func (o *TBLUser) RoleKeyDataRole(mods ...qm.QueryMod) dataRoleQuery {
	queryMods := []qm.QueryMod{
		qm.Where("`role_key` = ?", o.RoleKey),
	}

	queryMods = append(queryMods, mods...)

	return DataRoles(queryMods...)
}

// UpdateUser pointed to by the foreign key.
func (o *TBLUser) UpdateUser(mods ...qm.QueryMod) tblUserQuery {
	queryMods := []qm.QueryMod{
		qm.Where("`id` = ?", o.UpdateUserID),
	}

	queryMods = append(queryMods, mods...)

	return TBLUsers(queryMods...)
}

// CreateUserTBLSchedules retrieves all the tbl_schedule's TBLSchedules with an executor via create_user column.
func (o *TBLUser) CreateUserTBLSchedules(mods ...qm.QueryMod) tblScheduleQuery {
	var queryMods []qm.QueryMod
	if len(mods) != 0 {
		queryMods = append(queryMods, mods...)
	}

	queryMods = append(queryMods,
		qm.Where("`tbl_schedules`.`create_user`=?", o.ID),
	)

	return TBLSchedules(queryMods...)
}

// LastUpdateUserTBLSchedules retrieves all the tbl_schedule's TBLSchedules with an executor via last_update_user column.
func (o *TBLUser) LastUpdateUserTBLSchedules(mods ...qm.QueryMod) tblScheduleQuery {
	var queryMods []qm.QueryMod
	if len(mods) != 0 {
		queryMods = append(queryMods, mods...)
	}

	queryMods = append(queryMods,
		qm.Where("`tbl_schedules`.`last_update_user`=?", o.ID),
	)

	return TBLSchedules(queryMods...)
}

// UpdateUserTBLUsers retrieves all the tbl_user's TBLUsers with an executor via update_user_id column.
func (o *TBLUser) UpdateUserTBLUsers(mods ...qm.QueryMod) tblUserQuery {
	var queryMods []qm.QueryMod
	if len(mods) != 0 {
		queryMods = append(queryMods, mods...)
	}

	queryMods = append(queryMods,
		qm.Where("`tbl_users`.`update_user_id`=?", o.ID),
	)

	return TBLUsers(queryMods...)
}

// LoadRoleKeyDataRole allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (tblUserL) LoadRoleKeyDataRole(ctx context.Context, e boil.ContextExecutor, singular bool, maybeTBLUser interface{}, mods queries.Applicator) error {
	var slice []*TBLUser
	var object *TBLUser

	if singular {
		var ok bool
		object, ok = maybeTBLUser.(*TBLUser)
		if !ok {
			object = new(TBLUser)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeTBLUser)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeTBLUser))
			}
		}
	} else {
		s, ok := maybeTBLUser.(*[]*TBLUser)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeTBLUser)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeTBLUser))
			}
		}
	}

	args := make(map[interface{}]struct{})
	if singular {
		if object.R == nil {
			object.R = &tblUserR{}
		}
		args[object.RoleKey] = struct{}{}

	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &tblUserR{}
			}

			args[obj.RoleKey] = struct{}{}

		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]interface{}, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`data_roles`),
		qm.WhereIn(`data_roles.role_key in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load DataRole")
	}

	var resultSlice []*DataRole
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice DataRole")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for data_roles")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for data_roles")
	}

	if len(dataRoleAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.RoleKeyDataRole = foreign
		if foreign.R == nil {
			foreign.R = &dataRoleR{}
		}
		foreign.R.RoleKeyTBLUsers = append(foreign.R.RoleKeyTBLUsers, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if local.RoleKey == foreign.RoleKey {
				local.R.RoleKeyDataRole = foreign
				if foreign.R == nil {
					foreign.R = &dataRoleR{}
				}
				foreign.R.RoleKeyTBLUsers = append(foreign.R.RoleKeyTBLUsers, local)
				break
			}
		}
	}

	return nil
}

// LoadUpdateUser allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (tblUserL) LoadUpdateUser(ctx context.Context, e boil.ContextExecutor, singular bool, maybeTBLUser interface{}, mods queries.Applicator) error {
	var slice []*TBLUser
	var object *TBLUser

	if singular {
		var ok bool
		object, ok = maybeTBLUser.(*TBLUser)
		if !ok {
			object = new(TBLUser)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeTBLUser)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeTBLUser))
			}
		}
	} else {
		s, ok := maybeTBLUser.(*[]*TBLUser)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeTBLUser)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeTBLUser))
			}
		}
	}

	args := make(map[interface{}]struct{})
	if singular {
		if object.R == nil {
			object.R = &tblUserR{}
		}
		args[object.UpdateUserID] = struct{}{}

	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &tblUserR{}
			}

			args[obj.UpdateUserID] = struct{}{}

		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]interface{}, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`tbl_users`),
		qm.WhereIn(`tbl_users.id in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load TBLUser")
	}

	var resultSlice []*TBLUser
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice TBLUser")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for tbl_users")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for tbl_users")
	}

	if len(tblUserAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.UpdateUser = foreign
		if foreign.R == nil {
			foreign.R = &tblUserR{}
		}
		foreign.R.UpdateUserTBLUsers = append(foreign.R.UpdateUserTBLUsers, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if local.UpdateUserID == foreign.ID {
				local.R.UpdateUser = foreign
				if foreign.R == nil {
					foreign.R = &tblUserR{}
				}
				foreign.R.UpdateUserTBLUsers = append(foreign.R.UpdateUserTBLUsers, local)
				break
			}
		}
	}

	return nil
}

// LoadCreateUserTBLSchedules allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for a 1-M or N-M relationship.
func (tblUserL) LoadCreateUserTBLSchedules(ctx context.Context, e boil.ContextExecutor, singular bool, maybeTBLUser interface{}, mods queries.Applicator) error {
	var slice []*TBLUser
	var object *TBLUser

	if singular {
		var ok bool
		object, ok = maybeTBLUser.(*TBLUser)
		if !ok {
			object = new(TBLUser)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeTBLUser)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeTBLUser))
			}
		}
	} else {
		s, ok := maybeTBLUser.(*[]*TBLUser)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeTBLUser)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeTBLUser))
			}
		}
	}

	args := make(map[interface{}]struct{})
	if singular {
		if object.R == nil {
			object.R = &tblUserR{}
		}
		args[object.ID] = struct{}{}
	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &tblUserR{}
			}
			args[obj.ID] = struct{}{}
		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]interface{}, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`tbl_schedules`),
		qm.WhereIn(`tbl_schedules.create_user in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load tbl_schedules")
	}

	var resultSlice []*TBLSchedule
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice tbl_schedules")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results in eager load on tbl_schedules")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for tbl_schedules")
	}

	if len(tblScheduleAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}
	if singular {
		object.R.CreateUserTBLSchedules = resultSlice
		for _, foreign := range resultSlice {
			if foreign.R == nil {
				foreign.R = &tblScheduleR{}
			}
			foreign.R.CreateUserTBLUser = object
		}
		return nil
	}

	for _, foreign := range resultSlice {
		for _, local := range slice {
			if local.ID == foreign.CreateUser {
				local.R.CreateUserTBLSchedules = append(local.R.CreateUserTBLSchedules, foreign)
				if foreign.R == nil {
					foreign.R = &tblScheduleR{}
				}
				foreign.R.CreateUserTBLUser = local
				break
			}
		}
	}

	return nil
}

// LoadLastUpdateUserTBLSchedules allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for a 1-M or N-M relationship.
func (tblUserL) LoadLastUpdateUserTBLSchedules(ctx context.Context, e boil.ContextExecutor, singular bool, maybeTBLUser interface{}, mods queries.Applicator) error {
	var slice []*TBLUser
	var object *TBLUser

	if singular {
		var ok bool
		object, ok = maybeTBLUser.(*TBLUser)
		if !ok {
			object = new(TBLUser)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeTBLUser)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeTBLUser))
			}
		}
	} else {
		s, ok := maybeTBLUser.(*[]*TBLUser)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeTBLUser)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeTBLUser))
			}
		}
	}

	args := make(map[interface{}]struct{})
	if singular {
		if object.R == nil {
			object.R = &tblUserR{}
		}
		args[object.ID] = struct{}{}
	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &tblUserR{}
			}
			args[obj.ID] = struct{}{}
		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]interface{}, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`tbl_schedules`),
		qm.WhereIn(`tbl_schedules.last_update_user in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load tbl_schedules")
	}

	var resultSlice []*TBLSchedule
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice tbl_schedules")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results in eager load on tbl_schedules")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for tbl_schedules")
	}

	if len(tblScheduleAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}
	if singular {
		object.R.LastUpdateUserTBLSchedules = resultSlice
		for _, foreign := range resultSlice {
			if foreign.R == nil {
				foreign.R = &tblScheduleR{}
			}
			foreign.R.LastUpdateUserTBLUser = object
		}
		return nil
	}

	for _, foreign := range resultSlice {
		for _, local := range slice {
			if local.ID == foreign.LastUpdateUser {
				local.R.LastUpdateUserTBLSchedules = append(local.R.LastUpdateUserTBLSchedules, foreign)
				if foreign.R == nil {
					foreign.R = &tblScheduleR{}
				}
				foreign.R.LastUpdateUserTBLUser = local
				break
			}
		}
	}

	return nil
}

// LoadUpdateUserTBLUsers allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for a 1-M or N-M relationship.
func (tblUserL) LoadUpdateUserTBLUsers(ctx context.Context, e boil.ContextExecutor, singular bool, maybeTBLUser interface{}, mods queries.Applicator) error {
	var slice []*TBLUser
	var object *TBLUser

	if singular {
		var ok bool
		object, ok = maybeTBLUser.(*TBLUser)
		if !ok {
			object = new(TBLUser)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeTBLUser)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeTBLUser))
			}
		}
	} else {
		s, ok := maybeTBLUser.(*[]*TBLUser)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeTBLUser)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeTBLUser))
			}
		}
	}

	args := make(map[interface{}]struct{})
	if singular {
		if object.R == nil {
			object.R = &tblUserR{}
		}
		args[object.ID] = struct{}{}
	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &tblUserR{}
			}
			args[obj.ID] = struct{}{}
		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]interface{}, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`tbl_users`),
		qm.WhereIn(`tbl_users.update_user_id in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load tbl_users")
	}

	var resultSlice []*TBLUser
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice tbl_users")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results in eager load on tbl_users")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for tbl_users")
	}

	if len(tblUserAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}
	if singular {
		object.R.UpdateUserTBLUsers = resultSlice
		for _, foreign := range resultSlice {
			if foreign.R == nil {
				foreign.R = &tblUserR{}
			}
			foreign.R.UpdateUser = object
		}
		return nil
	}

	for _, foreign := range resultSlice {
		for _, local := range slice {
			if local.ID == foreign.UpdateUserID {
				local.R.UpdateUserTBLUsers = append(local.R.UpdateUserTBLUsers, foreign)
				if foreign.R == nil {
					foreign.R = &tblUserR{}
				}
				foreign.R.UpdateUser = local
				break
			}
		}
	}

	return nil
}

// SetRoleKeyDataRole of the tblUser to the related item.
// Sets o.R.RoleKeyDataRole to related.
// Adds o to related.R.RoleKeyTBLUsers.
func (o *TBLUser) SetRoleKeyDataRole(ctx context.Context, exec boil.ContextExecutor, insert bool, related *DataRole) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE `tbl_users` SET %s WHERE %s",
		strmangle.SetParamNames("`", "`", 0, []string{"role_key"}),
		strmangle.WhereClause("`", "`", 0, tblUserPrimaryKeyColumns),
	)
	values := []interface{}{related.RoleKey, o.ID}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, updateQuery)
		fmt.Fprintln(writer, values)
	}
	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	o.RoleKey = related.RoleKey
	if o.R == nil {
		o.R = &tblUserR{
			RoleKeyDataRole: related,
		}
	} else {
		o.R.RoleKeyDataRole = related
	}

	if related.R == nil {
		related.R = &dataRoleR{
			RoleKeyTBLUsers: TBLUserSlice{o},
		}
	} else {
		related.R.RoleKeyTBLUsers = append(related.R.RoleKeyTBLUsers, o)
	}

	return nil
}

// SetUpdateUser of the tblUser to the related item.
// Sets o.R.UpdateUser to related.
// Adds o to related.R.UpdateUserTBLUsers.
func (o *TBLUser) SetUpdateUser(ctx context.Context, exec boil.ContextExecutor, insert bool, related *TBLUser) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE `tbl_users` SET %s WHERE %s",
		strmangle.SetParamNames("`", "`", 0, []string{"update_user_id"}),
		strmangle.WhereClause("`", "`", 0, tblUserPrimaryKeyColumns),
	)
	values := []interface{}{related.ID, o.ID}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, updateQuery)
		fmt.Fprintln(writer, values)
	}
	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	o.UpdateUserID = related.ID
	if o.R == nil {
		o.R = &tblUserR{
			UpdateUser: related,
		}
	} else {
		o.R.UpdateUser = related
	}

	if related.R == nil {
		related.R = &tblUserR{
			UpdateUserTBLUsers: TBLUserSlice{o},
		}
	} else {
		related.R.UpdateUserTBLUsers = append(related.R.UpdateUserTBLUsers, o)
	}

	return nil
}

// AddCreateUserTBLSchedules adds the given related objects to the existing relationships
// of the tbl_user, optionally inserting them as new records.
// Appends related to o.R.CreateUserTBLSchedules.
// Sets related.R.CreateUserTBLUser appropriately.
func (o *TBLUser) AddCreateUserTBLSchedules(ctx context.Context, exec boil.ContextExecutor, insert bool, related ...*TBLSchedule) error {
	var err error
	for _, rel := range related {
		if insert {
			rel.CreateUser = o.ID
			if err = rel.Insert(ctx, exec, boil.Infer()); err != nil {
				return errors.Wrap(err, "failed to insert into foreign table")
			}
		} else {
			updateQuery := fmt.Sprintf(
				"UPDATE `tbl_schedules` SET %s WHERE %s",
				strmangle.SetParamNames("`", "`", 0, []string{"create_user"}),
				strmangle.WhereClause("`", "`", 0, tblSchedulePrimaryKeyColumns),
			)
			values := []interface{}{o.ID, rel.ID}

			if boil.IsDebug(ctx) {
				writer := boil.DebugWriterFrom(ctx)
				fmt.Fprintln(writer, updateQuery)
				fmt.Fprintln(writer, values)
			}
			if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
				return errors.Wrap(err, "failed to update foreign table")
			}

			rel.CreateUser = o.ID
		}
	}

	if o.R == nil {
		o.R = &tblUserR{
			CreateUserTBLSchedules: related,
		}
	} else {
		o.R.CreateUserTBLSchedules = append(o.R.CreateUserTBLSchedules, related...)
	}

	for _, rel := range related {
		if rel.R == nil {
			rel.R = &tblScheduleR{
				CreateUserTBLUser: o,
			}
		} else {
			rel.R.CreateUserTBLUser = o
		}
	}
	return nil
}

// AddLastUpdateUserTBLSchedules adds the given related objects to the existing relationships
// of the tbl_user, optionally inserting them as new records.
// Appends related to o.R.LastUpdateUserTBLSchedules.
// Sets related.R.LastUpdateUserTBLUser appropriately.
func (o *TBLUser) AddLastUpdateUserTBLSchedules(ctx context.Context, exec boil.ContextExecutor, insert bool, related ...*TBLSchedule) error {
	var err error
	for _, rel := range related {
		if insert {
			rel.LastUpdateUser = o.ID
			if err = rel.Insert(ctx, exec, boil.Infer()); err != nil {
				return errors.Wrap(err, "failed to insert into foreign table")
			}
		} else {
			updateQuery := fmt.Sprintf(
				"UPDATE `tbl_schedules` SET %s WHERE %s",
				strmangle.SetParamNames("`", "`", 0, []string{"last_update_user"}),
				strmangle.WhereClause("`", "`", 0, tblSchedulePrimaryKeyColumns),
			)
			values := []interface{}{o.ID, rel.ID}

			if boil.IsDebug(ctx) {
				writer := boil.DebugWriterFrom(ctx)
				fmt.Fprintln(writer, updateQuery)
				fmt.Fprintln(writer, values)
			}
			if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
				return errors.Wrap(err, "failed to update foreign table")
			}

			rel.LastUpdateUser = o.ID
		}
	}

	if o.R == nil {
		o.R = &tblUserR{
			LastUpdateUserTBLSchedules: related,
		}
	} else {
		o.R.LastUpdateUserTBLSchedules = append(o.R.LastUpdateUserTBLSchedules, related...)
	}

	for _, rel := range related {
		if rel.R == nil {
			rel.R = &tblScheduleR{
				LastUpdateUserTBLUser: o,
			}
		} else {
			rel.R.LastUpdateUserTBLUser = o
		}
	}
	return nil
}

// AddUpdateUserTBLUsers adds the given related objects to the existing relationships
// of the tbl_user, optionally inserting them as new records.
// Appends related to o.R.UpdateUserTBLUsers.
// Sets related.R.UpdateUser appropriately.
func (o *TBLUser) AddUpdateUserTBLUsers(ctx context.Context, exec boil.ContextExecutor, insert bool, related ...*TBLUser) error {
	var err error
	for _, rel := range related {
		if insert {
			rel.UpdateUserID = o.ID
			if err = rel.Insert(ctx, exec, boil.Infer()); err != nil {
				return errors.Wrap(err, "failed to insert into foreign table")
			}
		} else {
			updateQuery := fmt.Sprintf(
				"UPDATE `tbl_users` SET %s WHERE %s",
				strmangle.SetParamNames("`", "`", 0, []string{"update_user_id"}),
				strmangle.WhereClause("`", "`", 0, tblUserPrimaryKeyColumns),
			)
			values := []interface{}{o.ID, rel.ID}

			if boil.IsDebug(ctx) {
				writer := boil.DebugWriterFrom(ctx)
				fmt.Fprintln(writer, updateQuery)
				fmt.Fprintln(writer, values)
			}
			if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
				return errors.Wrap(err, "failed to update foreign table")
			}

			rel.UpdateUserID = o.ID
		}
	}

	if o.R == nil {
		o.R = &tblUserR{
			UpdateUserTBLUsers: related,
		}
	} else {
		o.R.UpdateUserTBLUsers = append(o.R.UpdateUserTBLUsers, related...)
	}

	for _, rel := range related {
		if rel.R == nil {
			rel.R = &tblUserR{
				UpdateUser: o,
			}
		} else {
			rel.R.UpdateUser = o
		}
	}
	return nil
}

// TBLUsers retrieves all the records using an executor.
func TBLUsers(mods ...qm.QueryMod) tblUserQuery {
	mods = append(mods, qm.From("`tbl_users`"))
	q := NewQuery(mods...)
	if len(queries.GetSelect(q)) == 0 {
		queries.SetSelect(q, []string{"`tbl_users`.*"})
	}

	return tblUserQuery{q}
}

// FindTBLUser retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindTBLUser(ctx context.Context, exec boil.ContextExecutor, iD int, selectCols ...string) (*TBLUser, error) {
	tblUserObj := &TBLUser{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from `tbl_users` where `id`=?", sel,
	)

	q := queries.Raw(query, iD)

	err := q.Bind(ctx, exec, tblUserObj)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "dto: unable to select from tbl_users")
	}

	if err = tblUserObj.doAfterSelectHooks(ctx, exec); err != nil {
		return tblUserObj, err
	}

	return tblUserObj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *TBLUser) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("dto: no tbl_users provided for insertion")
	}

	var err error

	if err := o.doBeforeInsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(tblUserColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	tblUserInsertCacheMut.RLock()
	cache, cached := tblUserInsertCache[key]
	tblUserInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			tblUserAllColumns,
			tblUserColumnsWithDefault,
			tblUserColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(tblUserType, tblUserMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(tblUserType, tblUserMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO `tbl_users` (`%s`) %%sVALUES (%s)%%s", strings.Join(wl, "`,`"), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO `tbl_users` () VALUES ()%s%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			cache.retQuery = fmt.Sprintf("SELECT `%s` FROM `tbl_users` WHERE %s", strings.Join(returnColumns, "`,`"), strmangle.WhereClause("`", "`", 0, tblUserPrimaryKeyColumns))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	result, err := exec.ExecContext(ctx, cache.query, vals...)

	if err != nil {
		return errors.Wrap(err, "dto: unable to insert into tbl_users")
	}

	var lastID int64
	var identifierCols []interface{}

	if len(cache.retMapping) == 0 {
		goto CacheNoHooks
	}

	lastID, err = result.LastInsertId()
	if err != nil {
		return ErrSyncFail
	}

	o.ID = int(lastID)
	if lastID != 0 && len(cache.retMapping) == 1 && cache.retMapping[0] == tblUserMapping["id"] {
		goto CacheNoHooks
	}

	identifierCols = []interface{}{
		o.ID,
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.retQuery)
		fmt.Fprintln(writer, identifierCols...)
	}
	err = exec.QueryRowContext(ctx, cache.retQuery, identifierCols...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	if err != nil {
		return errors.Wrap(err, "dto: unable to populate default values for tbl_users")
	}

CacheNoHooks:
	if !cached {
		tblUserInsertCacheMut.Lock()
		tblUserInsertCache[key] = cache
		tblUserInsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(ctx, exec)
}

// Update uses an executor to update the TBLUser.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *TBLUser) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	var err error
	if err = o.doBeforeUpdateHooks(ctx, exec); err != nil {
		return 0, err
	}
	key := makeCacheKey(columns, nil)
	tblUserUpdateCacheMut.RLock()
	cache, cached := tblUserUpdateCache[key]
	tblUserUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			tblUserAllColumns,
			tblUserPrimaryKeyColumns,
		)
		if len(wl) == 0 {
			return 0, errors.New("dto: unable to update tbl_users, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE `tbl_users` SET %s WHERE %s",
			strmangle.SetParamNames("`", "`", 0, wl),
			strmangle.WhereClause("`", "`", 0, tblUserPrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(tblUserType, tblUserMapping, append(wl, tblUserPrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "dto: unable to update tbl_users row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "dto: failed to get rows affected by update for tbl_users")
	}

	if !cached {
		tblUserUpdateCacheMut.Lock()
		tblUserUpdateCache[key] = cache
		tblUserUpdateCacheMut.Unlock()
	}

	return rowsAff, o.doAfterUpdateHooks(ctx, exec)
}

// UpdateAll updates all rows with the specified column values.
func (q tblUserQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "dto: unable to update all for tbl_users")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "dto: unable to retrieve rows affected for tbl_users")
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o TBLUserSlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("dto: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), tblUserPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE `tbl_users` SET %s WHERE %s",
		strmangle.SetParamNames("`", "`", 0, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, tblUserPrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "dto: unable to update all in tblUser slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "dto: unable to retrieve rows affected all in update all tblUser")
	}
	return rowsAff, nil
}

var mySQLTBLUserUniqueColumns = []string{
	"id",
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *TBLUser) Upsert(ctx context.Context, exec boil.ContextExecutor, updateColumns, insertColumns boil.Columns) error {
	if o == nil {
		return errors.New("dto: no tbl_users provided for upsert")
	}

	if err := o.doBeforeUpsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(tblUserColumnsWithDefault, o)
	nzUniques := queries.NonZeroDefaultSet(mySQLTBLUserUniqueColumns, o)

	if len(nzUniques) == 0 {
		return errors.New("cannot upsert with a table that cannot conflict on a unique column")
	}

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzUniques {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	tblUserUpsertCacheMut.RLock()
	cache, cached := tblUserUpsertCache[key]
	tblUserUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, _ := insertColumns.InsertColumnSet(
			tblUserAllColumns,
			tblUserColumnsWithDefault,
			tblUserColumnsWithoutDefault,
			nzDefaults,
		)

		update := updateColumns.UpdateColumnSet(
			tblUserAllColumns,
			tblUserPrimaryKeyColumns,
		)

		if !updateColumns.IsNone() && len(update) == 0 {
			return errors.New("dto: unable to upsert tbl_users, could not build update column list")
		}

		ret := strmangle.SetComplement(tblUserAllColumns, strmangle.SetIntersect(insert, update))

		cache.query = buildUpsertQueryMySQL(dialect, "`tbl_users`", update, insert)
		cache.retQuery = fmt.Sprintf(
			"SELECT %s FROM `tbl_users` WHERE %s",
			strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, ret), ","),
			strmangle.WhereClause("`", "`", 0, nzUniques),
		)

		cache.valueMapping, err = queries.BindMapping(tblUserType, tblUserMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(tblUserType, tblUserMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	result, err := exec.ExecContext(ctx, cache.query, vals...)

	if err != nil {
		return errors.Wrap(err, "dto: unable to upsert for tbl_users")
	}

	var lastID int64
	var uniqueMap []uint64
	var nzUniqueCols []interface{}

	if len(cache.retMapping) == 0 {
		goto CacheNoHooks
	}

	lastID, err = result.LastInsertId()
	if err != nil {
		return ErrSyncFail
	}

	o.ID = int(lastID)
	if lastID != 0 && len(cache.retMapping) == 1 && cache.retMapping[0] == tblUserMapping["id"] {
		goto CacheNoHooks
	}

	uniqueMap, err = queries.BindMapping(tblUserType, tblUserMapping, nzUniques)
	if err != nil {
		return errors.Wrap(err, "dto: unable to retrieve unique values for tbl_users")
	}
	nzUniqueCols = queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), uniqueMap)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.retQuery)
		fmt.Fprintln(writer, nzUniqueCols...)
	}
	err = exec.QueryRowContext(ctx, cache.retQuery, nzUniqueCols...).Scan(returns...)
	if err != nil {
		return errors.Wrap(err, "dto: unable to populate default values for tbl_users")
	}

CacheNoHooks:
	if !cached {
		tblUserUpsertCacheMut.Lock()
		tblUserUpsertCache[key] = cache
		tblUserUpsertCacheMut.Unlock()
	}

	return o.doAfterUpsertHooks(ctx, exec)
}

// Delete deletes a single TBLUser record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *TBLUser) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("dto: no TBLUser provided for delete")
	}

	if err := o.doBeforeDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), tblUserPrimaryKeyMapping)
	sql := "DELETE FROM `tbl_users` WHERE `id`=?"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "dto: unable to delete from tbl_users")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "dto: failed to get rows affected by delete for tbl_users")
	}

	if err := o.doAfterDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	return rowsAff, nil
}

// DeleteAll deletes all matching rows.
func (q tblUserQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("dto: no tblUserQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "dto: unable to delete all from tbl_users")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "dto: failed to get rows affected by deleteall for tbl_users")
	}

	return rowsAff, nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o TBLUserSlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	if len(tblUserBeforeDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doBeforeDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), tblUserPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM `tbl_users` WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, tblUserPrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "dto: unable to delete all from tblUser slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "dto: failed to get rows affected by deleteall for tbl_users")
	}

	if len(tblUserAfterDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	return rowsAff, nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *TBLUser) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindTBLUser(ctx, exec, o.ID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *TBLUserSlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := TBLUserSlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), tblUserPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT `tbl_users`.* FROM `tbl_users` WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, tblUserPrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "dto: unable to reload all in TBLUserSlice")
	}

	*o = slice

	return nil
}

// TBLUserExists checks if the TBLUser row exists.
func TBLUserExists(ctx context.Context, exec boil.ContextExecutor, iD int) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from `tbl_users` where `id`=? limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, iD)
	}
	row := exec.QueryRowContext(ctx, sql, iD)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "dto: unable to check if tbl_users exists")
	}

	return exists, nil
}

// Exists checks if the TBLUser row exists.
func (o *TBLUser) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	return TBLUserExists(ctx, exec, o.ID)
}
